<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Limen.Site.Wasm</RootNamespace>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Limen.Site.Engine/Limen.Site.Engine.fsproj" />
    <SupportedPlatform Include="browser" />
  </ItemGroup>
</Project>
