// limen-contract-gen: the only writer of generated contract bindings.
//
//   node --experimental-strip-types tools/contract-gen/main.ts generate
//   node --experimental-strip-types tools/contract-gen/main.ts check
//
// `check` regenerates in memory and compares byte-for-byte with what is on
// disk. It classifies every difference so an agent is told what happened and
// what to do, rather than just "files differ".

import { readFile, readdir, writeFile, mkdir } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { parseUnit, sha256, type ContractUnit } from "./model.ts";
import { emitTypeScriptCodec, emitTypeScriptTypes } from "./emit-typescript.ts";
import { FSHARP_RUNTIME, emitFSharpUnit } from "./emit-fsharp.ts";
import { CSHARP_RUNTIME, emitCSharpUnit } from "./emit-csharp.ts";
import { RUST_RUNTIME, emitRustUnit } from "./emit-rust.ts";
import { OUTPUT_KINDS, parseTargets, type OutputKind, type Target } from "./targets.ts";

export const GENERATOR_ID = "limen-contract-gen/1";
export const GENERATED_MARKER = "<auto-generated by limen-contract-gen>";
const HEADER_END = "// </auto-generated>";

// A unit emitter needs the contract unit; a runtime emitter needs nothing.
type Emitter =
  | { readonly needs: "unit"; readonly emit: (unit: ContractUnit, target: Target) => string }
  | { readonly needs: "nothing"; readonly emit: () => string };

// Closed on purpose: a target naming an emitter that does not exist fails
// target validation, and adding an emitter is a code change reviewed here.
const EMITTERS: Readonly<Record<OutputKind, Emitter>> = {
  "typescript-types": { needs: "unit", emit: (unit) => emitTypeScriptTypes(unit) },
  "typescript-codec": { needs: "unit", emit: (unit, target) => emitTypeScriptCodec(unit, target.typesModule ?? "./types.js") },
  "fsharp-runtime": { needs: "nothing", emit: () => FSHARP_RUNTIME },
  "fsharp-unit": { needs: "unit", emit: (unit) => emitFSharpUnit(unit) },
  "csharp-runtime": { needs: "nothing", emit: () => CSHARP_RUNTIME },
  "csharp-unit": { needs: "unit", emit: (unit) => emitCSharpUnit(unit) },
  "rust-runtime": { needs: "nothing", emit: () => RUST_RUNTIME },
  "rust-unit": { needs: "unit", emit: (unit) => emitRustUnit(unit) },
};

type Provenance = { readonly source: string; readonly unit: string; readonly fingerprint: string };

const provenanceOf = (unit: ContractUnit | undefined): Provenance =>
  unit === undefined
    ? { source: "tools/contract-gen", unit: "(runtime: shared by every unit)", fingerprint: "(none)" }
    : { source: unit.source, unit: `${unit.unit}@${unit.version}`, fingerprint: unit.fingerprint };

export const withHeader = (unit: ContractUnit | undefined, target: Target, body: string): string => lines([
  `// ${GENERATED_MARKER}`,
  "// GENERATED FILE — DO NOT EDIT. Change the contract and run `npm run contract:generate`.",
  `// source: ${provenanceOf(unit).source}`,
  `// unit: ${provenanceOf(unit).unit}`,
  `// contract-fingerprint: ${provenanceOf(unit).fingerprint}`,
  `// generator: ${GENERATOR_ID} (${target.kind})`,
  `// content-hash: ${sha256(body)}`,
  HEADER_END,
  body,
]);

const lines = (parts: readonly string[]): string => parts.join("\n");

export type Rendered = { readonly path: string; readonly content: string };

export type Finding =
  | { readonly kind: "missing"; readonly path: string }
  | { readonly kind: "hand-edited"; readonly path: string }
  | { readonly kind: "stale"; readonly path: string }
  | { readonly kind: "orphan"; readonly path: string };

const splitHeader = (content: string): { readonly declaredHash: string | undefined; readonly body: string } => {
  const end = content.indexOf(`${HEADER_END}\n`);
  if (end < 0) return { declaredHash: undefined, body: content };
  const header = content.slice(0, end);
  const match = /^\/\/ content-hash: (sha256:[0-9a-f]{64})$/m.exec(header);
  return { declaredHash: match?.[1], body: content.slice(end + HEADER_END.length + 1) };
};

// Pure classification of one expected output against what is on disk.
export const classify = (expected: Rendered, actual: string | undefined): Finding | undefined => {
  if (actual === undefined) return { kind: "missing", path: expected.path };
  if (actual === expected.content) return undefined;
  const { declaredHash, body } = splitHeader(actual);
  return declaredHash !== undefined && declaredHash === sha256(body)
    ? { kind: "stale", path: expected.path }
    : { kind: "hand-edited", path: expected.path };
};

export const describe = (finding: Finding): string => {
  switch (finding.kind) {
    case "missing": return `${finding.path}: generated binding is missing. Run \`npm run contract:generate\`.`;
    case "stale": return `${finding.path}: generated binding is stale — the contract or generator changed without regenerating. Run \`npm run contract:generate\` and commit the result.`;
    case "hand-edited": return `${finding.path}: generated binding was edited by hand. Generated files are read-only: revert the edit, change contract/*.contract.json (or the generator) instead, then run \`npm run contract:generate\`.`;
    case "orphan": return `${finding.path}: carries the generated marker but no contract target produces it. Delete it, or add a target in contract/targets.json.`;
  }
};

export const loadUnits = async (root: string, paths: readonly string[]): Promise<readonly ContractUnit[]> => {
  const parsed = await Promise.all(paths.map(async (path) => parseUnit(JSON.parse(await readFile(join(root, path), "utf8")) as unknown, path)));
  const errors = parsed.flatMap((result) => (result.ok ? [] : result.errors));
  if (errors.length > 0) throw new Error(`Contract is not well-formed:\n${errors.join("\n")}`);
  return parsed.flatMap((result) => (result.ok ? [result.value] : []));
};

export const render = async (root: string): Promise<readonly Rendered[]> => {
  const targets = parseTargets(JSON.parse(await readFile(join(root, "contract/targets.json"), "utf8")) as unknown);
  if (!targets.ok) throw new Error(`contract/targets.json is invalid:\n${targets.errors.join("\n")}`);
  const units = await loadUnits(root, targets.value.units);
  const byName = new Map(units.map((unit) => [unit.unit, unit] as const));
  return targets.value.outputs.map((target) => {
    const emitter = EMITTERS[target.kind];
    if (emitter.needs === "nothing") return { path: target.path, content: withHeader(undefined, target, emitter.emit()) };
    const unit = target.unit === undefined ? undefined : byName.get(target.unit);
    if (unit === undefined) throw new Error(`contract/targets.json: output ${target.path} names unknown unit ${String(target.unit)}`);
    return { path: target.path, content: withHeader(unit, target, emitter.emit(unit, target)) };
  });
};

const readIfPresent = async (path: string): Promise<string | undefined> => {
  try {
    return await readFile(path, "utf8");
  } catch {
    return undefined;
  }
};

const walk = async (directory: string): Promise<readonly string[]> => {
  const entries = await readdir(directory, { withFileTypes: true }).catch(() => []);
  const nested = await Promise.all(entries.map((entry) => {
    const path = join(directory, entry.name);
    return entry.isDirectory() ? walk(path) : Promise.resolve([path]);
  }));
  return nested.flat();
};

// Files that claim to be generated but that no target produces — e.g. a
// binding left behind after a target was removed, or one copied by hand.
const orphans = async (root: string, rendered: readonly Rendered[]): Promise<readonly Finding[]> => {
  const directories = [...new Set(rendered.map((output) => dirname(output.path)))];
  const expected = new Set(rendered.map((output) => output.path));
  const files = (await Promise.all(directories.map((directory) => walk(join(root, directory))))).flat();
  const marked = await Promise.all(files.map(async (file) => ({ file: relative(root, file), marked: (await readIfPresent(file))?.includes(GENERATED_MARKER) === true })));
  return marked.filter(({ file, marked: isMarked }) => isMarked && !expected.has(file)).map(({ file }) => ({ kind: "orphan", path: file }));
};

export const check = async (root: string): Promise<readonly Finding[]> => {
  const rendered = await render(root);
  const findings = await Promise.all(rendered.map(async (output) => classify(output, await readIfPresent(join(root, output.path)))));
  return [...findings.flatMap((finding) => (finding === undefined ? [] : [finding])), ...(await orphans(root, rendered))];
};

export const generate = async (root: string): Promise<readonly string[]> => {
  const rendered = await render(root);
  await Promise.all(rendered.map(async (output) => {
    await mkdir(dirname(join(root, output.path)), { recursive: true });
    await writeFile(join(root, output.path), output.content, "utf8");
  }));
  return rendered.map((output) => output.path);
};

const main = async (argv: readonly string[]): Promise<number> => {
  const root = process.cwd();
  switch (argv[0]) {
    case "generate": {
      const written = await generate(root);
      console.log(`Generated ${written.length} binding(s):\n${written.map((path) => `  ${path}`).join("\n")}`);
      return 0;
    }
    case "check": {
      const findings = await check(root);
      if (findings.length === 0) {
        console.log("Generated contract bindings are current.");
        return 0;
      }
      console.error(`Generated contract bindings are not current (${findings.length} finding(s)):\n${findings.map(describe).join("\n")}`);
      return 1;
    }
    default:
      console.error(`usage: contract-gen <generate|check>\nknown output kinds: ${OUTPUT_KINDS.join(", ")}`);
      return 2;
  }
};

if (import.meta.url === `file://${process.argv[1]}`) {
  process.exitCode = await main(process.argv.slice(2));
}
