//! Generated Rust bindings for the Limen contract.
//!
//! Every module except this file is generated by `tools/contract-gen` from
//! `contract/*.contract.json`. Change the contract, run
//! `npm run contract:generate`, never edit the modules.

#![forbid(unsafe_code)]
#![deny(warnings)]

pub mod runtime;

pub mod limen_core;

/// The optional focus, selection and scroll capability (limen.focus).
pub mod limen_focus;

/// The optional scheduling capability (limen.schedule).
pub mod limen_schedule;

/// The optional measurement and observer capability (limen.measure).
pub mod limen_measure;

/// A test-only capability unit, compiled only for the conformance tests.
#[cfg(test)]
pub mod limen_fixture_echo;
