//! Generated Rust bindings for the Limen contract.
//!
//! Every module except this file is generated by `tools/contract-gen` from
//! `contract/*.contract.json`. Change the contract, run
//! `npm run contract:generate`, never edit the modules.

#![forbid(unsafe_code)]
#![deny(warnings)]

pub mod runtime;

pub mod limen_core;

/// The optional focus, selection and scroll capability (limen.focus).
pub mod limen_focus;

/// The optional scheduling capability (limen.schedule).
pub mod limen_schedule;

/// The optional measurement and observer capability (limen.measure).
pub mod limen_measure;

/// The optional rich browser event facts capability (limen.events).
pub mod limen_events;
pub mod limen_overlay;
pub mod limen_realtime;
pub mod limen_files;
pub mod limen_store;
pub mod limen_adapters;
pub mod limen_transfer;
pub mod limen_presentation;
pub mod limen_environment;
pub mod limen_lifecycle;
pub mod limen_offline;
pub mod limen_geolocation;
pub mod limen_credentials;
pub mod limen_coordination;

/// A test-only capability unit, compiled only for the conformance tests.
#[cfg(test)]
pub mod limen_fixture_echo;
