// <auto-generated by limen-contract-gen>
// GENERATED FILE — DO NOT EDIT. Change the contract and run `npm run contract:generate`.
// source: contract/events.contract.json
// unit: limen.events@1
// contract-fingerprint: sha256:d72c2fac6cfca243fd024e12f659e000a217863bc933f74d0cef089dcb0a19bd
// generator: limen-contract-gen/1 (rust-unit)
// content-hash: sha256:018bb2882c0cb18fe2e48d1a7560c8638e6887af096e6d73dc242fe403d60e0d
// </auto-generated>
//! Rich browser event facts without DOM Event objects (LCP-020). A listener is declared in HTML with data-rich-event and data-rich-on, and opts into exactly the fact groups it needs with data-rich-facts; everything the browser must decide synchronously (preventDefault, stopPropagation, capture, passive, once, pointer capture) is declared there too, so the engine is never asked for a synchronous DOM decision. The simple data-event path is untouched. The pack interprets no shortcut or gesture: it reports facts.


use serde_json::Value;

use crate::runtime::{wire, DecodeError};

/// The identity of this generated contract unit, exchanged in the handshake.
pub mod contract {
    pub const UNIT: &str = "limen.events";
    pub const VERSION: i64 = 1;
    pub const FINGERPRINT: &str = "sha256:d72c2fac6cfca243fd024e12f659e000a217863bc933f74d0cef089dcb0a19bd";
}

#[derive(Debug, Clone, PartialEq)]
pub struct Modifiers {
    pub alt: bool,
    pub ctrl: bool,
    pub meta: bool,
    pub shift: bool,
}

#[derive(Debug, Clone, PartialEq)]
pub struct KeyboardFacts {
    pub key: String,
    pub code: String,
    pub repeat: bool,
    pub composing: bool,
}

/// x and y (client CSS pixels) only when the listener asked for coordinates.
#[derive(Debug, Clone, PartialEq)]
pub struct PointerFacts {
    pub pointer_type: String,
    pub pointer_id: i64,
    pub button: i64,
    pub buttons: i64,
    pub is_primary: bool,
    pub x: Option<f64>,
    pub y: Option<f64>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum DragPhase {
    Start,
    Enter,
    Over,
    Leave,
    Drop,
    End,
}

impl DragPhase {
    /// The wire text of this value.
    pub fn as_wire(&self) -> &'static str {
        match self {
            DragPhase::Start => "start",
            DragPhase::Enter => "enter",
            DragPhase::Over => "over",
            DragPhase::Leave => "leave",
            DragPhase::Drop => "drop",
            DragPhase::End => "end",
        }
    }
}

/// What is being dragged, by type only: contents are not read. fileCount counts dropped files; reading one is a file capability's job.
#[derive(Debug, Clone, PartialEq)]
pub struct DragFacts {
    pub phase: DragPhase,
    pub types: Vec<String>,
    pub file_count: i64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum CompositionPhase {
    Start,
    Update,
    End,
}

impl CompositionPhase {
    /// The wire text of this value.
    pub fn as_wire(&self) -> &'static str {
        match self {
            CompositionPhase::Start => "start",
            CompositionPhase::Update => "update",
            CompositionPhase::End => "end",
        }
    }
}

/// committed is present only at end: text during composition is not the user's yet.
#[derive(Debug, Clone, PartialEq)]
pub struct CompositionFacts {
    pub phase: CompositionPhase,
    pub committed: Option<String>,
}

/// A text control's selection, in UTF-16 code units as the browser reports it.
#[derive(Debug, Clone, PartialEq)]
pub struct SelectionFacts {
    pub start: i64,
    pub end: i64,
    pub direction: String,
}

/// beforeinput / input: the kind of edit, and its data when not composing.
#[derive(Debug, Clone, PartialEq)]
pub struct InputFacts {
    pub input_type: String,
    pub data: Option<String>,
}

/// One declared listener fired. Only the groups the listener asked for are present.
#[derive(Debug, Clone, PartialEq)]
pub struct RichEvent {
    pub name: String,
    /// The DOM event type (keydown, pointermove, …).
    pub r#type: String,
    /// The row key from the nearest data-rich-key ancestor, projected by the engine.
    pub key: Option<String>,
    pub value: Option<String>,
    pub modifiers: Option<Modifiers>,
    pub keyboard: Option<KeyboardFacts>,
    pub pointer: Option<PointerFacts>,
    pub drag: Option<DragFacts>,
    pub composition: Option<CompositionFacts>,
    pub selection: Option<SelectionFacts>,
    pub input: Option<InputFacts>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Listener {
    pub name: String,
    pub r#type: String,
    /// Why the declaration was not bound, e.g. passive with preventDefault.
    pub refused: Option<String>,
}

#[derive(Debug, Clone, PartialEq)]
pub enum EventsRequest {
    /// The listeners currently declared and bound.
    Describe,
}

#[derive(Debug, Clone, PartialEq)]
pub enum EventsResult {
    Listening {
        listeners: Vec<Listener>,
    },
    Cancelled,
}

pub fn decode_modifiers(value: &Value, path: &str) -> Result<Modifiers, DecodeError> {
    let props = wire::closed(wire::properties(value, path)?, path, &["alt", "ctrl", "meta", "shift"])?;
    let f_alt = wire::required(props, path, "alt", |v0: &Value, p0: &str| wire::boolean(v0, p0))?;
    let f_ctrl = wire::required(props, path, "ctrl", |v0: &Value, p0: &str| wire::boolean(v0, p0))?;
    let f_meta = wire::required(props, path, "meta", |v0: &Value, p0: &str| wire::boolean(v0, p0))?;
    let f_shift = wire::required(props, path, "shift", |v0: &Value, p0: &str| wire::boolean(v0, p0))?;
    Ok(Modifiers { alt: f_alt, ctrl: f_ctrl, meta: f_meta, shift: f_shift })
}

pub fn decode_keyboard_facts(value: &Value, path: &str) -> Result<KeyboardFacts, DecodeError> {
    let props = wire::closed(wire::properties(value, path)?, path, &["key", "code", "repeat", "composing"])?;
    let f_key = wire::required(props, path, "key", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    let f_code = wire::required(props, path, "code", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    let f_repeat = wire::required(props, path, "repeat", |v0: &Value, p0: &str| wire::boolean(v0, p0))?;
    let f_composing = wire::required(props, path, "composing", |v0: &Value, p0: &str| wire::boolean(v0, p0))?;
    Ok(KeyboardFacts { key: f_key, code: f_code, repeat: f_repeat, composing: f_composing })
}

pub fn decode_pointer_facts(value: &Value, path: &str) -> Result<PointerFacts, DecodeError> {
    let props = wire::closed(wire::properties(value, path)?, path, &["pointerType", "pointerId", "button", "buttons", "isPrimary", "x", "y"])?;
    let f_pointer_type = wire::required(props, path, "pointerType", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    let f_pointer_id = wire::required(props, path, "pointerId", |v0: &Value, p0: &str| wire::int(v0, p0))?;
    let f_button = wire::required(props, path, "button", |v0: &Value, p0: &str| wire::int(v0, p0))?;
    let f_buttons = wire::required(props, path, "buttons", |v0: &Value, p0: &str| wire::int(v0, p0))?;
    let f_is_primary = wire::required(props, path, "isPrimary", |v0: &Value, p0: &str| wire::boolean(v0, p0))?;
    let f_x = wire::optional(props, path, "x", |v0: &Value, p0: &str| wire::number(v0, p0))?;
    let f_y = wire::optional(props, path, "y", |v0: &Value, p0: &str| wire::number(v0, p0))?;
    Ok(PointerFacts { pointer_type: f_pointer_type, pointer_id: f_pointer_id, button: f_button, buttons: f_buttons, is_primary: f_is_primary, x: f_x, y: f_y })
}

pub fn decode_drag_phase(value: &Value, path: &str) -> Result<DragPhase, DecodeError> {
    wire::enumeration(value, path, &[("start", DragPhase::Start), ("enter", DragPhase::Enter), ("over", DragPhase::Over), ("leave", DragPhase::Leave), ("drop", DragPhase::Drop), ("end", DragPhase::End)])
}

pub fn decode_drag_facts(value: &Value, path: &str) -> Result<DragFacts, DecodeError> {
    let props = wire::closed(wire::properties(value, path)?, path, &["phase", "types", "fileCount"])?;
    let f_phase = wire::required(props, path, "phase", |v0: &Value, p0: &str| decode_drag_phase(v0, p0))?;
    let f_types = wire::required(props, path, "types", |v0: &Value, p0: &str| wire::list(v0, p0, |v1: &Value, p1: &str| wire::string(v1, p1)))?;
    let f_file_count = wire::required(props, path, "fileCount", |v0: &Value, p0: &str| wire::int(v0, p0))?;
    Ok(DragFacts { phase: f_phase, types: f_types, file_count: f_file_count })
}

pub fn decode_composition_phase(value: &Value, path: &str) -> Result<CompositionPhase, DecodeError> {
    wire::enumeration(value, path, &[("start", CompositionPhase::Start), ("update", CompositionPhase::Update), ("end", CompositionPhase::End)])
}

pub fn decode_composition_facts(value: &Value, path: &str) -> Result<CompositionFacts, DecodeError> {
    let props = wire::closed(wire::properties(value, path)?, path, &["phase", "committed"])?;
    let f_phase = wire::required(props, path, "phase", |v0: &Value, p0: &str| decode_composition_phase(v0, p0))?;
    let f_committed = wire::optional(props, path, "committed", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    Ok(CompositionFacts { phase: f_phase, committed: f_committed })
}

pub fn decode_selection_facts(value: &Value, path: &str) -> Result<SelectionFacts, DecodeError> {
    let props = wire::closed(wire::properties(value, path)?, path, &["start", "end", "direction"])?;
    let f_start = wire::required(props, path, "start", |v0: &Value, p0: &str| wire::int(v0, p0))?;
    let f_end = wire::required(props, path, "end", |v0: &Value, p0: &str| wire::int(v0, p0))?;
    let f_direction = wire::required(props, path, "direction", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    Ok(SelectionFacts { start: f_start, end: f_end, direction: f_direction })
}

pub fn decode_input_facts(value: &Value, path: &str) -> Result<InputFacts, DecodeError> {
    let props = wire::closed(wire::properties(value, path)?, path, &["inputType", "data"])?;
    let f_input_type = wire::required(props, path, "inputType", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    let f_data = wire::optional(props, path, "data", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    Ok(InputFacts { input_type: f_input_type, data: f_data })
}

pub fn decode_rich_event(value: &Value, path: &str) -> Result<RichEvent, DecodeError> {
    let props = wire::closed(wire::properties(value, path)?, path, &["name", "type", "key", "value", "modifiers", "keyboard", "pointer", "drag", "composition", "selection", "input"])?;
    let f_name = wire::required(props, path, "name", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    let f_type = wire::required(props, path, "type", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    let f_key = wire::optional(props, path, "key", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    let f_value = wire::optional(props, path, "value", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    let f_modifiers = wire::optional(props, path, "modifiers", |v0: &Value, p0: &str| decode_modifiers(v0, p0))?;
    let f_keyboard = wire::optional(props, path, "keyboard", |v0: &Value, p0: &str| decode_keyboard_facts(v0, p0))?;
    let f_pointer = wire::optional(props, path, "pointer", |v0: &Value, p0: &str| decode_pointer_facts(v0, p0))?;
    let f_drag = wire::optional(props, path, "drag", |v0: &Value, p0: &str| decode_drag_facts(v0, p0))?;
    let f_composition = wire::optional(props, path, "composition", |v0: &Value, p0: &str| decode_composition_facts(v0, p0))?;
    let f_selection = wire::optional(props, path, "selection", |v0: &Value, p0: &str| decode_selection_facts(v0, p0))?;
    let f_input = wire::optional(props, path, "input", |v0: &Value, p0: &str| decode_input_facts(v0, p0))?;
    Ok(RichEvent { name: f_name, r#type: f_type, key: f_key, value: f_value, modifiers: f_modifiers, keyboard: f_keyboard, pointer: f_pointer, drag: f_drag, composition: f_composition, selection: f_selection, input: f_input })
}

pub fn decode_listener(value: &Value, path: &str) -> Result<Listener, DecodeError> {
    let props = wire::closed(wire::properties(value, path)?, path, &["name", "type", "refused"])?;
    let f_name = wire::required(props, path, "name", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    let f_type = wire::required(props, path, "type", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    let f_refused = wire::optional(props, path, "refused", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    Ok(Listener { name: f_name, r#type: f_type, refused: f_refused })
}

pub fn decode_events_request(value: &Value, path: &str) -> Result<EventsRequest, DecodeError> {
    match wire::tag(value, path, "operation")?.as_str() {
        "describe" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "describe"))?;
            Ok(EventsRequest::Describe)
        }
        other => Err(wire::unknown_variant(&format!("{}.operation", path), other)),
    }
}

pub fn decode_events_result(value: &Value, path: &str) -> Result<EventsResult, DecodeError> {
    match wire::tag(value, path, "kind")?.as_str() {
        "Listening" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "listeners"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Listening"))?;
            let f_listeners = wire::required(props, path, "listeners", |v0: &Value, p0: &str| wire::list(v0, p0, |v1: &Value, p1: &str| decode_listener(v1, p1)))?;
            Ok(EventsResult::Listening { listeners: f_listeners })
        }
        "Cancelled" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Cancelled"))?;
            Ok(EventsResult::Cancelled)
        }
        other => Err(wire::unknown_variant(&format!("{}.kind", path), other)),
    }
}

pub fn encode_modifiers(value: &Modifiers) -> Value {
    wire::of_object(vec![Some(("alt", wire::of_bool(*&value.alt))), Some(("ctrl", wire::of_bool(*&value.ctrl))), Some(("meta", wire::of_bool(*&value.meta))), Some(("shift", wire::of_bool(*&value.shift)))])
}

pub fn encode_keyboard_facts(value: &KeyboardFacts) -> Value {
    wire::of_object(vec![Some(("key", wire::of_string(&value.key))), Some(("code", wire::of_string(&value.code))), Some(("repeat", wire::of_bool(*&value.repeat))), Some(("composing", wire::of_bool(*&value.composing)))])
}

pub fn encode_pointer_facts(value: &PointerFacts) -> Value {
    wire::of_object(vec![Some(("pointerType", wire::of_string(&value.pointer_type))), Some(("pointerId", wire::of_int(*&value.pointer_id))), Some(("button", wire::of_int(*&value.button))), Some(("buttons", wire::of_int(*&value.buttons))), Some(("isPrimary", wire::of_bool(*&value.is_primary))), (&value.x).as_ref().map(|x0| ("x", wire::of_number(*x0))), (&value.y).as_ref().map(|x0| ("y", wire::of_number(*x0)))])
}

pub fn encode_drag_phase(value: &DragPhase) -> Value {
    match value {
        DragPhase::Start => wire::of_string("start"),
        DragPhase::Enter => wire::of_string("enter"),
        DragPhase::Over => wire::of_string("over"),
        DragPhase::Leave => wire::of_string("leave"),
        DragPhase::Drop => wire::of_string("drop"),
        DragPhase::End => wire::of_string("end"),
    }
}

pub fn encode_drag_facts(value: &DragFacts) -> Value {
    wire::of_object(vec![Some(("phase", encode_drag_phase(&value.phase))), Some(("types", wire::of_list(&value.types, |x0| wire::of_string(x0)))), Some(("fileCount", wire::of_int(*&value.file_count)))])
}

pub fn encode_composition_phase(value: &CompositionPhase) -> Value {
    match value {
        CompositionPhase::Start => wire::of_string("start"),
        CompositionPhase::Update => wire::of_string("update"),
        CompositionPhase::End => wire::of_string("end"),
    }
}

pub fn encode_composition_facts(value: &CompositionFacts) -> Value {
    wire::of_object(vec![Some(("phase", encode_composition_phase(&value.phase))), (&value.committed).as_ref().map(|x0| ("committed", wire::of_string(x0)))])
}

pub fn encode_selection_facts(value: &SelectionFacts) -> Value {
    wire::of_object(vec![Some(("start", wire::of_int(*&value.start))), Some(("end", wire::of_int(*&value.end))), Some(("direction", wire::of_string(&value.direction)))])
}

pub fn encode_input_facts(value: &InputFacts) -> Value {
    wire::of_object(vec![Some(("inputType", wire::of_string(&value.input_type))), (&value.data).as_ref().map(|x0| ("data", wire::of_string(x0)))])
}

pub fn encode_rich_event(value: &RichEvent) -> Value {
    wire::of_object(vec![Some(("name", wire::of_string(&value.name))), Some(("type", wire::of_string(&value.r#type))), (&value.key).as_ref().map(|x0| ("key", wire::of_string(x0))), (&value.value).as_ref().map(|x0| ("value", wire::of_string(x0))), (&value.modifiers).as_ref().map(|x0| ("modifiers", encode_modifiers(x0))), (&value.keyboard).as_ref().map(|x0| ("keyboard", encode_keyboard_facts(x0))), (&value.pointer).as_ref().map(|x0| ("pointer", encode_pointer_facts(x0))), (&value.drag).as_ref().map(|x0| ("drag", encode_drag_facts(x0))), (&value.composition).as_ref().map(|x0| ("composition", encode_composition_facts(x0))), (&value.selection).as_ref().map(|x0| ("selection", encode_selection_facts(x0))), (&value.input).as_ref().map(|x0| ("input", encode_input_facts(x0)))])
}

pub fn encode_listener(value: &Listener) -> Value {
    wire::of_object(vec![Some(("name", wire::of_string(&value.name))), Some(("type", wire::of_string(&value.r#type))), (&value.refused).as_ref().map(|x0| ("refused", wire::of_string(x0)))])
}

pub fn encode_events_request(value: &EventsRequest) -> Value {
    match value {
        EventsRequest::Describe => wire::of_object(vec![Some(("operation", wire::of_string("describe")))]),
    }
}

pub fn encode_events_result(value: &EventsResult) -> Value {
    match value {
        EventsResult::Listening { listeners: f_listeners } => wire::of_object(vec![Some(("kind", wire::of_string("Listening"))), Some(("listeners", wire::of_list(f_listeners, |x0| encode_listener(x0))))]),
        EventsResult::Cancelled => wire::of_object(vec![Some(("kind", wire::of_string("Cancelled")))]),
    }
}

/// Parses untrusted JSON text into a Modifiers, or says where and why it is not one.
pub fn parse_modifiers(json: &str) -> Result<Modifiers, DecodeError> {
    wire::parse(json, decode_modifiers)
}

/// Serializes a Modifiers to wire JSON text.
pub fn serialize_modifiers(value: &Modifiers) -> String {
    encode_modifiers(value).to_string()
}

/// Parses untrusted JSON text into a KeyboardFacts, or says where and why it is not one.
pub fn parse_keyboard_facts(json: &str) -> Result<KeyboardFacts, DecodeError> {
    wire::parse(json, decode_keyboard_facts)
}

/// Serializes a KeyboardFacts to wire JSON text.
pub fn serialize_keyboard_facts(value: &KeyboardFacts) -> String {
    encode_keyboard_facts(value).to_string()
}

/// Parses untrusted JSON text into a PointerFacts, or says where and why it is not one.
pub fn parse_pointer_facts(json: &str) -> Result<PointerFacts, DecodeError> {
    wire::parse(json, decode_pointer_facts)
}

/// Serializes a PointerFacts to wire JSON text.
pub fn serialize_pointer_facts(value: &PointerFacts) -> String {
    encode_pointer_facts(value).to_string()
}

/// Parses untrusted JSON text into a DragPhase, or says where and why it is not one.
pub fn parse_drag_phase(json: &str) -> Result<DragPhase, DecodeError> {
    wire::parse(json, decode_drag_phase)
}

/// Serializes a DragPhase to wire JSON text.
pub fn serialize_drag_phase(value: &DragPhase) -> String {
    encode_drag_phase(value).to_string()
}

/// Parses untrusted JSON text into a DragFacts, or says where and why it is not one.
pub fn parse_drag_facts(json: &str) -> Result<DragFacts, DecodeError> {
    wire::parse(json, decode_drag_facts)
}

/// Serializes a DragFacts to wire JSON text.
pub fn serialize_drag_facts(value: &DragFacts) -> String {
    encode_drag_facts(value).to_string()
}

/// Parses untrusted JSON text into a CompositionPhase, or says where and why it is not one.
pub fn parse_composition_phase(json: &str) -> Result<CompositionPhase, DecodeError> {
    wire::parse(json, decode_composition_phase)
}

/// Serializes a CompositionPhase to wire JSON text.
pub fn serialize_composition_phase(value: &CompositionPhase) -> String {
    encode_composition_phase(value).to_string()
}

/// Parses untrusted JSON text into a CompositionFacts, or says where and why it is not one.
pub fn parse_composition_facts(json: &str) -> Result<CompositionFacts, DecodeError> {
    wire::parse(json, decode_composition_facts)
}

/// Serializes a CompositionFacts to wire JSON text.
pub fn serialize_composition_facts(value: &CompositionFacts) -> String {
    encode_composition_facts(value).to_string()
}

/// Parses untrusted JSON text into a SelectionFacts, or says where and why it is not one.
pub fn parse_selection_facts(json: &str) -> Result<SelectionFacts, DecodeError> {
    wire::parse(json, decode_selection_facts)
}

/// Serializes a SelectionFacts to wire JSON text.
pub fn serialize_selection_facts(value: &SelectionFacts) -> String {
    encode_selection_facts(value).to_string()
}

/// Parses untrusted JSON text into a InputFacts, or says where and why it is not one.
pub fn parse_input_facts(json: &str) -> Result<InputFacts, DecodeError> {
    wire::parse(json, decode_input_facts)
}

/// Serializes a InputFacts to wire JSON text.
pub fn serialize_input_facts(value: &InputFacts) -> String {
    encode_input_facts(value).to_string()
}

/// Parses untrusted JSON text into a RichEvent, or says where and why it is not one.
pub fn parse_rich_event(json: &str) -> Result<RichEvent, DecodeError> {
    wire::parse(json, decode_rich_event)
}

/// Serializes a RichEvent to wire JSON text.
pub fn serialize_rich_event(value: &RichEvent) -> String {
    encode_rich_event(value).to_string()
}

/// Parses untrusted JSON text into a Listener, or says where and why it is not one.
pub fn parse_listener(json: &str) -> Result<Listener, DecodeError> {
    wire::parse(json, decode_listener)
}

/// Serializes a Listener to wire JSON text.
pub fn serialize_listener(value: &Listener) -> String {
    encode_listener(value).to_string()
}

/// Parses untrusted JSON text into a EventsRequest, or says where and why it is not one.
pub fn parse_events_request(json: &str) -> Result<EventsRequest, DecodeError> {
    wire::parse(json, decode_events_request)
}

/// Serializes a EventsRequest to wire JSON text.
pub fn serialize_events_request(value: &EventsRequest) -> String {
    encode_events_request(value).to_string()
}

/// Parses untrusted JSON text into a EventsResult, or says where and why it is not one.
pub fn parse_events_result(json: &str) -> Result<EventsResult, DecodeError> {
    wire::parse(json, decode_events_result)
}

/// Serializes a EventsResult to wire JSON text.
pub fn serialize_events_result(value: &EventsResult) -> String {
    encode_events_result(value).to_string()
}

/// Decode-then-encode by type name. Used only by the shared conformance runner.
pub fn conformance_round_trip(type_name: &str, value: &Value) -> Option<Result<Value, DecodeError>> {
    match type_name {
        "Modifiers" => Some(decode_modifiers(value, "$").map(|decoded| encode_modifiers(&decoded))),
        "KeyboardFacts" => Some(decode_keyboard_facts(value, "$").map(|decoded| encode_keyboard_facts(&decoded))),
        "PointerFacts" => Some(decode_pointer_facts(value, "$").map(|decoded| encode_pointer_facts(&decoded))),
        "DragPhase" => Some(decode_drag_phase(value, "$").map(|decoded| encode_drag_phase(&decoded))),
        "DragFacts" => Some(decode_drag_facts(value, "$").map(|decoded| encode_drag_facts(&decoded))),
        "CompositionPhase" => Some(decode_composition_phase(value, "$").map(|decoded| encode_composition_phase(&decoded))),
        "CompositionFacts" => Some(decode_composition_facts(value, "$").map(|decoded| encode_composition_facts(&decoded))),
        "SelectionFacts" => Some(decode_selection_facts(value, "$").map(|decoded| encode_selection_facts(&decoded))),
        "InputFacts" => Some(decode_input_facts(value, "$").map(|decoded| encode_input_facts(&decoded))),
        "RichEvent" => Some(decode_rich_event(value, "$").map(|decoded| encode_rich_event(&decoded))),
        "Listener" => Some(decode_listener(value, "$").map(|decoded| encode_listener(&decoded))),
        "EventsRequest" => Some(decode_events_request(value, "$").map(|decoded| encode_events_request(&decoded))),
        "EventsResult" => Some(decode_events_result(value, "$").map(|decoded| encode_events_result(&decoded))),
        _ => None,
    }
}
