// <auto-generated by limen-contract-gen>
// GENERATED FILE — DO NOT EDIT. Change the contract and run `npm run contract:generate`.
// source: contract/measure.contract.json
// unit: limen.measure@1
// contract-fingerprint: sha256:29614596fd5bc8d9cce90e4bcc6fe92701f7d6b724cae6c49cf3106b8877e225
// generator: limen-contract-gen/1 (rust-unit)
// content-hash: sha256:bdfc3966bd8f9dddae65f380c7ff7b3020cfa6b818a0635133e964e057a902d3
// </auto-generated>
//! Layout and visibility facts without DOM nodes (LCP-014). Targets are named in HTML with data-measure-target (and, inside a data-each row, data-measure-key projected by the engine). Subscriptions are opaque ids; their updates arrive as capability facts. What a size or a visibility means stays the engine's decision.


use serde_json::Value;

use crate::runtime::{wire, DecodeError};

/// The identity of this generated contract unit, exchanged in the handshake.
pub mod contract {
    pub const UNIT: &str = "limen.measure";
    pub const VERSION: i64 = 1;
    pub const FINGERPRINT: &str = "sha256:29614596fd5bc8d9cce90e4bcc6fe92701f7d6b724cae6c49cf3106b8877e225";
}

#[derive(Debug, Clone, PartialEq)]
pub struct MeasureTarget {
    pub name: String,
    pub key: Option<String>,
}

/// Opaque; issued by this page's pack and meaningless anywhere else.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct SubscriptionId(pub String);

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SubscriptionStaleReason {
    Unknown,
    Disposed,
    OtherSession,
}

impl SubscriptionStaleReason {
    /// The wire text of this value.
    pub fn as_wire(&self) -> &'static str {
        match self {
            SubscriptionStaleReason::Unknown => "unknown",
            SubscriptionStaleReason::Disposed => "disposed",
            SubscriptionStaleReason::OtherSession => "other-session",
        }
    }
}

/// CSS pixels, relative to the viewport.
#[derive(Debug, Clone, PartialEq)]
pub struct Rect {
    pub x: f64,
    pub y: f64,
    pub width: f64,
    pub height: f64,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Viewport {
    pub width: f64,
    pub height: f64,
    pub scroll_x: f64,
    pub scroll_y: f64,
    pub scroll_width: f64,
    pub scroll_height: f64,
    pub device_pixel_ratio: f64,
}

#[derive(Debug, Clone, PartialEq)]
pub enum MeasureRequest {
    /// The target's bounding rectangle now.
    Measure {
        target: MeasureTarget,
    },
    /// The viewport's size and the document's scroll position and extent now.
    Viewport,
    /// Resized facts whenever the target's content box changes size.
    ObserveSize {
        target: MeasureTarget,
    },
    /// Visibility facts whenever the target crosses the threshold (0 to 1) of intersection with the viewport.
    ObserveVisibility {
        target: MeasureTarget,
        threshold: f64,
    },
    Unsubscribe {
        subscription: SubscriptionId,
    },
}

#[derive(Debug, Clone, PartialEq)]
pub enum MeasureResult {
    Measured {
        rect: Rect,
    },
    ViewportMeasured {
        viewport: Viewport,
    },
    /// Facts for this subscription follow until it is unsubscribed or its target is removed.
    Subscribed {
        subscription: SubscriptionId,
    },
    Unsubscribed,
    /// No such live subscription: never issued here, already ended, or from before a reload.
    Stale {
        reason: SubscriptionStaleReason,
    },
    NotFound,
    Ambiguous {
        count: i64,
    },
    InvalidThreshold,
    /// This browser lacks the observer.
    Unsupported,
    Cancelled,
}

/// Subscription updates. The browser already coalesces observer callbacks to at most one per frame; the pack forwards the latest entry per subscription per callback.
#[derive(Debug, Clone, PartialEq)]
pub enum MeasureFact {
    Resized {
        subscription: SubscriptionId,
        width: f64,
        height: f64,
    },
    Visibility {
        subscription: SubscriptionId,
        intersecting: bool,
        ratio: f64,
    },
    /// The target left the document; the subscription has ended and nothing more will be sent for it.
    TargetRemoved {
        subscription: SubscriptionId,
    },
}

pub fn decode_measure_target(value: &Value, path: &str) -> Result<MeasureTarget, DecodeError> {
    let props = wire::closed(wire::properties(value, path)?, path, &["name", "key"])?;
    let f_name = wire::required(props, path, "name", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    let f_key = wire::optional(props, path, "key", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    Ok(MeasureTarget { name: f_name, key: f_key })
}

pub fn decode_subscription_id(value: &Value, path: &str) -> Result<SubscriptionId, DecodeError> {
    wire::string(value, path).map(SubscriptionId)
}

pub fn decode_subscription_stale_reason(value: &Value, path: &str) -> Result<SubscriptionStaleReason, DecodeError> {
    wire::enumeration(value, path, &[("unknown", SubscriptionStaleReason::Unknown), ("disposed", SubscriptionStaleReason::Disposed), ("other-session", SubscriptionStaleReason::OtherSession)])
}

pub fn decode_rect(value: &Value, path: &str) -> Result<Rect, DecodeError> {
    let props = wire::closed(wire::properties(value, path)?, path, &["x", "y", "width", "height"])?;
    let f_x = wire::required(props, path, "x", |v0: &Value, p0: &str| wire::number(v0, p0))?;
    let f_y = wire::required(props, path, "y", |v0: &Value, p0: &str| wire::number(v0, p0))?;
    let f_width = wire::required(props, path, "width", |v0: &Value, p0: &str| wire::number(v0, p0))?;
    let f_height = wire::required(props, path, "height", |v0: &Value, p0: &str| wire::number(v0, p0))?;
    Ok(Rect { x: f_x, y: f_y, width: f_width, height: f_height })
}

pub fn decode_viewport(value: &Value, path: &str) -> Result<Viewport, DecodeError> {
    let props = wire::closed(wire::properties(value, path)?, path, &["width", "height", "scrollX", "scrollY", "scrollWidth", "scrollHeight", "devicePixelRatio"])?;
    let f_width = wire::required(props, path, "width", |v0: &Value, p0: &str| wire::number(v0, p0))?;
    let f_height = wire::required(props, path, "height", |v0: &Value, p0: &str| wire::number(v0, p0))?;
    let f_scroll_x = wire::required(props, path, "scrollX", |v0: &Value, p0: &str| wire::number(v0, p0))?;
    let f_scroll_y = wire::required(props, path, "scrollY", |v0: &Value, p0: &str| wire::number(v0, p0))?;
    let f_scroll_width = wire::required(props, path, "scrollWidth", |v0: &Value, p0: &str| wire::number(v0, p0))?;
    let f_scroll_height = wire::required(props, path, "scrollHeight", |v0: &Value, p0: &str| wire::number(v0, p0))?;
    let f_device_pixel_ratio = wire::required(props, path, "devicePixelRatio", |v0: &Value, p0: &str| wire::number(v0, p0))?;
    Ok(Viewport { width: f_width, height: f_height, scroll_x: f_scroll_x, scroll_y: f_scroll_y, scroll_width: f_scroll_width, scroll_height: f_scroll_height, device_pixel_ratio: f_device_pixel_ratio })
}

pub fn decode_measure_request(value: &Value, path: &str) -> Result<MeasureRequest, DecodeError> {
    match wire::tag(value, path, "operation")?.as_str() {
        "measure" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation", "target"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "measure"))?;
            let f_target = wire::required(props, path, "target", |v0: &Value, p0: &str| decode_measure_target(v0, p0))?;
            Ok(MeasureRequest::Measure { target: f_target })
        }
        "viewport" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "viewport"))?;
            Ok(MeasureRequest::Viewport)
        }
        "observeSize" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation", "target"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "observeSize"))?;
            let f_target = wire::required(props, path, "target", |v0: &Value, p0: &str| decode_measure_target(v0, p0))?;
            Ok(MeasureRequest::ObserveSize { target: f_target })
        }
        "observeVisibility" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation", "target", "threshold"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "observeVisibility"))?;
            let f_target = wire::required(props, path, "target", |v0: &Value, p0: &str| decode_measure_target(v0, p0))?;
            let f_threshold = wire::required(props, path, "threshold", |v0: &Value, p0: &str| wire::number(v0, p0))?;
            Ok(MeasureRequest::ObserveVisibility { target: f_target, threshold: f_threshold })
        }
        "unsubscribe" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation", "subscription"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "unsubscribe"))?;
            let f_subscription = wire::required(props, path, "subscription", |v0: &Value, p0: &str| decode_subscription_id(v0, p0))?;
            Ok(MeasureRequest::Unsubscribe { subscription: f_subscription })
        }
        other => Err(wire::unknown_variant(&format!("{}.operation", path), other)),
    }
}

pub fn decode_measure_result(value: &Value, path: &str) -> Result<MeasureResult, DecodeError> {
    match wire::tag(value, path, "kind")?.as_str() {
        "Measured" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "rect"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Measured"))?;
            let f_rect = wire::required(props, path, "rect", |v0: &Value, p0: &str| decode_rect(v0, p0))?;
            Ok(MeasureResult::Measured { rect: f_rect })
        }
        "ViewportMeasured" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "viewport"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "ViewportMeasured"))?;
            let f_viewport = wire::required(props, path, "viewport", |v0: &Value, p0: &str| decode_viewport(v0, p0))?;
            Ok(MeasureResult::ViewportMeasured { viewport: f_viewport })
        }
        "Subscribed" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "subscription"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Subscribed"))?;
            let f_subscription = wire::required(props, path, "subscription", |v0: &Value, p0: &str| decode_subscription_id(v0, p0))?;
            Ok(MeasureResult::Subscribed { subscription: f_subscription })
        }
        "Unsubscribed" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Unsubscribed"))?;
            Ok(MeasureResult::Unsubscribed)
        }
        "Stale" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "reason"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Stale"))?;
            let f_reason = wire::required(props, path, "reason", |v0: &Value, p0: &str| decode_subscription_stale_reason(v0, p0))?;
            Ok(MeasureResult::Stale { reason: f_reason })
        }
        "NotFound" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "NotFound"))?;
            Ok(MeasureResult::NotFound)
        }
        "Ambiguous" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "count"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Ambiguous"))?;
            let f_count = wire::required(props, path, "count", |v0: &Value, p0: &str| wire::int(v0, p0))?;
            Ok(MeasureResult::Ambiguous { count: f_count })
        }
        "InvalidThreshold" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "InvalidThreshold"))?;
            Ok(MeasureResult::InvalidThreshold)
        }
        "Unsupported" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Unsupported"))?;
            Ok(MeasureResult::Unsupported)
        }
        "Cancelled" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Cancelled"))?;
            Ok(MeasureResult::Cancelled)
        }
        other => Err(wire::unknown_variant(&format!("{}.kind", path), other)),
    }
}

pub fn decode_measure_fact(value: &Value, path: &str) -> Result<MeasureFact, DecodeError> {
    match wire::tag(value, path, "kind")?.as_str() {
        "Resized" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "subscription", "width", "height"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Resized"))?;
            let f_subscription = wire::required(props, path, "subscription", |v0: &Value, p0: &str| decode_subscription_id(v0, p0))?;
            let f_width = wire::required(props, path, "width", |v0: &Value, p0: &str| wire::number(v0, p0))?;
            let f_height = wire::required(props, path, "height", |v0: &Value, p0: &str| wire::number(v0, p0))?;
            Ok(MeasureFact::Resized { subscription: f_subscription, width: f_width, height: f_height })
        }
        "Visibility" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "subscription", "intersecting", "ratio"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Visibility"))?;
            let f_subscription = wire::required(props, path, "subscription", |v0: &Value, p0: &str| decode_subscription_id(v0, p0))?;
            let f_intersecting = wire::required(props, path, "intersecting", |v0: &Value, p0: &str| wire::boolean(v0, p0))?;
            let f_ratio = wire::required(props, path, "ratio", |v0: &Value, p0: &str| wire::number(v0, p0))?;
            Ok(MeasureFact::Visibility { subscription: f_subscription, intersecting: f_intersecting, ratio: f_ratio })
        }
        "TargetRemoved" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "subscription"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "TargetRemoved"))?;
            let f_subscription = wire::required(props, path, "subscription", |v0: &Value, p0: &str| decode_subscription_id(v0, p0))?;
            Ok(MeasureFact::TargetRemoved { subscription: f_subscription })
        }
        other => Err(wire::unknown_variant(&format!("{}.kind", path), other)),
    }
}

pub fn encode_measure_target(value: &MeasureTarget) -> Value {
    wire::of_object(vec![Some(("name", wire::of_string(&value.name))), (&value.key).as_ref().map(|x0| ("key", wire::of_string(x0)))])
}

pub fn encode_subscription_id(value: &SubscriptionId) -> Value {
    wire::of_string(&value.0)
}

pub fn encode_subscription_stale_reason(value: &SubscriptionStaleReason) -> Value {
    match value {
        SubscriptionStaleReason::Unknown => wire::of_string("unknown"),
        SubscriptionStaleReason::Disposed => wire::of_string("disposed"),
        SubscriptionStaleReason::OtherSession => wire::of_string("other-session"),
    }
}

pub fn encode_rect(value: &Rect) -> Value {
    wire::of_object(vec![Some(("x", wire::of_number(*&value.x))), Some(("y", wire::of_number(*&value.y))), Some(("width", wire::of_number(*&value.width))), Some(("height", wire::of_number(*&value.height)))])
}

pub fn encode_viewport(value: &Viewport) -> Value {
    wire::of_object(vec![Some(("width", wire::of_number(*&value.width))), Some(("height", wire::of_number(*&value.height))), Some(("scrollX", wire::of_number(*&value.scroll_x))), Some(("scrollY", wire::of_number(*&value.scroll_y))), Some(("scrollWidth", wire::of_number(*&value.scroll_width))), Some(("scrollHeight", wire::of_number(*&value.scroll_height))), Some(("devicePixelRatio", wire::of_number(*&value.device_pixel_ratio)))])
}

pub fn encode_measure_request(value: &MeasureRequest) -> Value {
    match value {
        MeasureRequest::Measure { target: f_target } => wire::of_object(vec![Some(("operation", wire::of_string("measure"))), Some(("target", encode_measure_target(f_target)))]),
        MeasureRequest::Viewport => wire::of_object(vec![Some(("operation", wire::of_string("viewport")))]),
        MeasureRequest::ObserveSize { target: f_target } => wire::of_object(vec![Some(("operation", wire::of_string("observeSize"))), Some(("target", encode_measure_target(f_target)))]),
        MeasureRequest::ObserveVisibility { target: f_target, threshold: f_threshold } => wire::of_object(vec![Some(("operation", wire::of_string("observeVisibility"))), Some(("target", encode_measure_target(f_target))), Some(("threshold", wire::of_number(*f_threshold)))]),
        MeasureRequest::Unsubscribe { subscription: f_subscription } => wire::of_object(vec![Some(("operation", wire::of_string("unsubscribe"))), Some(("subscription", encode_subscription_id(f_subscription)))]),
    }
}

pub fn encode_measure_result(value: &MeasureResult) -> Value {
    match value {
        MeasureResult::Measured { rect: f_rect } => wire::of_object(vec![Some(("kind", wire::of_string("Measured"))), Some(("rect", encode_rect(f_rect)))]),
        MeasureResult::ViewportMeasured { viewport: f_viewport } => wire::of_object(vec![Some(("kind", wire::of_string("ViewportMeasured"))), Some(("viewport", encode_viewport(f_viewport)))]),
        MeasureResult::Subscribed { subscription: f_subscription } => wire::of_object(vec![Some(("kind", wire::of_string("Subscribed"))), Some(("subscription", encode_subscription_id(f_subscription)))]),
        MeasureResult::Unsubscribed => wire::of_object(vec![Some(("kind", wire::of_string("Unsubscribed")))]),
        MeasureResult::Stale { reason: f_reason } => wire::of_object(vec![Some(("kind", wire::of_string("Stale"))), Some(("reason", encode_subscription_stale_reason(f_reason)))]),
        MeasureResult::NotFound => wire::of_object(vec![Some(("kind", wire::of_string("NotFound")))]),
        MeasureResult::Ambiguous { count: f_count } => wire::of_object(vec![Some(("kind", wire::of_string("Ambiguous"))), Some(("count", wire::of_int(*f_count)))]),
        MeasureResult::InvalidThreshold => wire::of_object(vec![Some(("kind", wire::of_string("InvalidThreshold")))]),
        MeasureResult::Unsupported => wire::of_object(vec![Some(("kind", wire::of_string("Unsupported")))]),
        MeasureResult::Cancelled => wire::of_object(vec![Some(("kind", wire::of_string("Cancelled")))]),
    }
}

pub fn encode_measure_fact(value: &MeasureFact) -> Value {
    match value {
        MeasureFact::Resized { subscription: f_subscription, width: f_width, height: f_height } => wire::of_object(vec![Some(("kind", wire::of_string("Resized"))), Some(("subscription", encode_subscription_id(f_subscription))), Some(("width", wire::of_number(*f_width))), Some(("height", wire::of_number(*f_height)))]),
        MeasureFact::Visibility { subscription: f_subscription, intersecting: f_intersecting, ratio: f_ratio } => wire::of_object(vec![Some(("kind", wire::of_string("Visibility"))), Some(("subscription", encode_subscription_id(f_subscription))), Some(("intersecting", wire::of_bool(*f_intersecting))), Some(("ratio", wire::of_number(*f_ratio)))]),
        MeasureFact::TargetRemoved { subscription: f_subscription } => wire::of_object(vec![Some(("kind", wire::of_string("TargetRemoved"))), Some(("subscription", encode_subscription_id(f_subscription)))]),
    }
}

/// Parses untrusted JSON text into a MeasureTarget, or says where and why it is not one.
pub fn parse_measure_target(json: &str) -> Result<MeasureTarget, DecodeError> {
    wire::parse(json, decode_measure_target)
}

/// Serializes a MeasureTarget to wire JSON text.
pub fn serialize_measure_target(value: &MeasureTarget) -> String {
    encode_measure_target(value).to_string()
}

/// Parses untrusted JSON text into a SubscriptionId, or says where and why it is not one.
pub fn parse_subscription_id(json: &str) -> Result<SubscriptionId, DecodeError> {
    wire::parse(json, decode_subscription_id)
}

/// Serializes a SubscriptionId to wire JSON text.
pub fn serialize_subscription_id(value: &SubscriptionId) -> String {
    encode_subscription_id(value).to_string()
}

/// Parses untrusted JSON text into a SubscriptionStaleReason, or says where and why it is not one.
pub fn parse_subscription_stale_reason(json: &str) -> Result<SubscriptionStaleReason, DecodeError> {
    wire::parse(json, decode_subscription_stale_reason)
}

/// Serializes a SubscriptionStaleReason to wire JSON text.
pub fn serialize_subscription_stale_reason(value: &SubscriptionStaleReason) -> String {
    encode_subscription_stale_reason(value).to_string()
}

/// Parses untrusted JSON text into a Rect, or says where and why it is not one.
pub fn parse_rect(json: &str) -> Result<Rect, DecodeError> {
    wire::parse(json, decode_rect)
}

/// Serializes a Rect to wire JSON text.
pub fn serialize_rect(value: &Rect) -> String {
    encode_rect(value).to_string()
}

/// Parses untrusted JSON text into a Viewport, or says where and why it is not one.
pub fn parse_viewport(json: &str) -> Result<Viewport, DecodeError> {
    wire::parse(json, decode_viewport)
}

/// Serializes a Viewport to wire JSON text.
pub fn serialize_viewport(value: &Viewport) -> String {
    encode_viewport(value).to_string()
}

/// Parses untrusted JSON text into a MeasureRequest, or says where and why it is not one.
pub fn parse_measure_request(json: &str) -> Result<MeasureRequest, DecodeError> {
    wire::parse(json, decode_measure_request)
}

/// Serializes a MeasureRequest to wire JSON text.
pub fn serialize_measure_request(value: &MeasureRequest) -> String {
    encode_measure_request(value).to_string()
}

/// Parses untrusted JSON text into a MeasureResult, or says where and why it is not one.
pub fn parse_measure_result(json: &str) -> Result<MeasureResult, DecodeError> {
    wire::parse(json, decode_measure_result)
}

/// Serializes a MeasureResult to wire JSON text.
pub fn serialize_measure_result(value: &MeasureResult) -> String {
    encode_measure_result(value).to_string()
}

/// Parses untrusted JSON text into a MeasureFact, or says where and why it is not one.
pub fn parse_measure_fact(json: &str) -> Result<MeasureFact, DecodeError> {
    wire::parse(json, decode_measure_fact)
}

/// Serializes a MeasureFact to wire JSON text.
pub fn serialize_measure_fact(value: &MeasureFact) -> String {
    encode_measure_fact(value).to_string()
}

/// Decode-then-encode by type name. Used only by the shared conformance runner.
pub fn conformance_round_trip(type_name: &str, value: &Value) -> Option<Result<Value, DecodeError>> {
    match type_name {
        "MeasureTarget" => Some(decode_measure_target(value, "$").map(|decoded| encode_measure_target(&decoded))),
        "SubscriptionId" => Some(decode_subscription_id(value, "$").map(|decoded| encode_subscription_id(&decoded))),
        "SubscriptionStaleReason" => Some(decode_subscription_stale_reason(value, "$").map(|decoded| encode_subscription_stale_reason(&decoded))),
        "Rect" => Some(decode_rect(value, "$").map(|decoded| encode_rect(&decoded))),
        "Viewport" => Some(decode_viewport(value, "$").map(|decoded| encode_viewport(&decoded))),
        "MeasureRequest" => Some(decode_measure_request(value, "$").map(|decoded| encode_measure_request(&decoded))),
        "MeasureResult" => Some(decode_measure_result(value, "$").map(|decoded| encode_measure_result(&decoded))),
        "MeasureFact" => Some(decode_measure_fact(value, "$").map(|decoded| encode_measure_fact(&decoded))),
        _ => None,
    }
}
