// <auto-generated by limen-contract-gen>
// GENERATED FILE — DO NOT EDIT. Change the contract and run `npm run contract:generate`.
// source: test/fixtures/capabilities/echo.contract.json
// unit: limen.fixture.echo@1
// contract-fingerprint: sha256:9aa4755b6c0ba31cd6cd385f9ce4faf2820567f53907e3378445be4c2ae08b23
// generator: limen-contract-gen/1 (rust-unit)
// content-hash: sha256:aa9762fbfc0d1d6d26996f4a3e888250274bbf5246ef6e71261bf368a97efc71
// </auto-generated>
//! A test-only capability that proves a new capability family can be added without changing Core. It echoes text, optionally after waiting (so cancellation can be observed), and emits a fact on request.


use serde_json::Value;

use crate::runtime::{wire, DecodeError};

/// The identity of this generated contract unit, exchanged in the handshake.
pub mod contract {
    pub const UNIT: &str = "limen.fixture.echo";
    pub const VERSION: i64 = 1;
    pub const FINGERPRINT: &str = "sha256:9aa4755b6c0ba31cd6cd385f9ce4faf2820567f53907e3378445be4c2ae08b23";
}

#[derive(Debug, Clone, PartialEq)]
pub enum EchoRequest {
    Echo {
        text: String,
    },
    Wait {
        ms: i64,
    },
    Announce {
        text: String,
    },
}

#[derive(Debug, Clone, PartialEq)]
pub enum EchoResult {
    Echoed {
        text: String,
    },
    Waited,
    Cancelled,
    Announced,
}

#[derive(Debug, Clone, PartialEq)]
pub struct EchoFact {
    pub text: String,
}

pub fn decode_echo_request(value: &Value, path: &str) -> Result<EchoRequest, DecodeError> {
    match wire::tag(value, path, "operation")?.as_str() {
        "echo" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation", "text"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "echo"))?;
            let f_text = wire::required(props, path, "text", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            Ok(EchoRequest::Echo { text: f_text })
        }
        "wait" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation", "ms"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "wait"))?;
            let f_ms = wire::required(props, path, "ms", |v0: &Value, p0: &str| wire::int(v0, p0))?;
            Ok(EchoRequest::Wait { ms: f_ms })
        }
        "announce" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation", "text"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "announce"))?;
            let f_text = wire::required(props, path, "text", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            Ok(EchoRequest::Announce { text: f_text })
        }
        other => Err(wire::unknown_variant(&format!("{}.operation", path), other)),
    }
}

pub fn decode_echo_result(value: &Value, path: &str) -> Result<EchoResult, DecodeError> {
    match wire::tag(value, path, "kind")?.as_str() {
        "Echoed" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "text"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Echoed"))?;
            let f_text = wire::required(props, path, "text", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            Ok(EchoResult::Echoed { text: f_text })
        }
        "Waited" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Waited"))?;
            Ok(EchoResult::Waited)
        }
        "Cancelled" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Cancelled"))?;
            Ok(EchoResult::Cancelled)
        }
        "Announced" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Announced"))?;
            Ok(EchoResult::Announced)
        }
        other => Err(wire::unknown_variant(&format!("{}.kind", path), other)),
    }
}

pub fn decode_echo_fact(value: &Value, path: &str) -> Result<EchoFact, DecodeError> {
    let props = wire::closed(wire::properties(value, path)?, path, &["text"])?;
    let f_text = wire::required(props, path, "text", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    Ok(EchoFact { text: f_text })
}

pub fn encode_echo_request(value: &EchoRequest) -> Value {
    match value {
        EchoRequest::Echo { text: f_text } => wire::of_object(vec![Some(("operation", wire::of_string("echo"))), Some(("text", wire::of_string(f_text)))]),
        EchoRequest::Wait { ms: f_ms } => wire::of_object(vec![Some(("operation", wire::of_string("wait"))), Some(("ms", wire::of_int(*f_ms)))]),
        EchoRequest::Announce { text: f_text } => wire::of_object(vec![Some(("operation", wire::of_string("announce"))), Some(("text", wire::of_string(f_text)))]),
    }
}

pub fn encode_echo_result(value: &EchoResult) -> Value {
    match value {
        EchoResult::Echoed { text: f_text } => wire::of_object(vec![Some(("kind", wire::of_string("Echoed"))), Some(("text", wire::of_string(f_text)))]),
        EchoResult::Waited => wire::of_object(vec![Some(("kind", wire::of_string("Waited")))]),
        EchoResult::Cancelled => wire::of_object(vec![Some(("kind", wire::of_string("Cancelled")))]),
        EchoResult::Announced => wire::of_object(vec![Some(("kind", wire::of_string("Announced")))]),
    }
}

pub fn encode_echo_fact(value: &EchoFact) -> Value {
    wire::of_object(vec![Some(("text", wire::of_string(&value.text)))])
}

/// Decode-then-encode by type name. Used only by the shared conformance runner.
pub fn conformance_round_trip(type_name: &str, value: &Value) -> Option<Result<Value, DecodeError>> {
    match type_name {
        "EchoRequest" => Some(decode_echo_request(value, "$").map(|decoded| encode_echo_request(&decoded))),
        "EchoResult" => Some(decode_echo_result(value, "$").map(|decoded| encode_echo_result(&decoded))),
        "EchoFact" => Some(decode_echo_fact(value, "$").map(|decoded| encode_echo_fact(&decoded))),
        _ => None,
    }
}
