// <auto-generated by limen-contract-gen>
// GENERATED FILE — DO NOT EDIT. Change the contract and run `npm run contract:generate`.
// source: contract/media.contract.json
// unit: limen.media@1
// contract-fingerprint: sha256:9340f0671e5e1f4ae3fca8e893691230acd2c709297e6132ed00550ebf8b037a
// generator: limen-contract-gen/1 (rust-unit)
// content-hash: sha256:44b58cb48be751e187d229c7f7804ec049bd1e9e88607ea11d92a143da668a44
// </auto-generated>
//! Camera and microphone capture and recording (LCP-038), under the permission pattern: availability, permission state and each request's outcome are kept apart. A MediaStream, a track, a recorder or a Blob never crosses the boundary. The engine holds an opaque capture id, may show it in a <video data-media-preview> the HTML names, and reads a finished recording in bounded slices. Nothing is requested at initialization: only startCapture can make the browser prompt. Every long-lived resource ends explicitly: stop, release, a cancelled capture, and the provider's own disposal all stop every track.


use serde_json::Value;

use crate::runtime::{wire, DecodeError};

/// The identity of this generated contract unit, exchanged in the handshake.
pub mod contract {
    pub const UNIT: &str = "limen.media";
    pub const VERSION: i64 = 1;
    pub const FINGERPRINT: &str = "sha256:9340f0671e5e1f4ae3fca8e893691230acd2c709297e6132ed00550ebf8b037a";
    pub const MAX_READ_BYTES: i64 = 1048576;
}

/// Shared by every permission-sensitive pack.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum PermissionState {
    Granted,
    Denied,
    Prompt,
}

impl PermissionState {
    /// The wire text of this value.
    pub fn as_wire(&self) -> &'static str {
        match self {
            PermissionState::Granted => "granted",
            PermissionState::Denied => "denied",
            PermissionState::Prompt => "prompt",
        }
    }
}

/// Shared by every permission-sensitive pack.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum UnavailableReason {
    NotSupported,
    InsecureContext,
    BlockedByPolicy,
}

impl UnavailableReason {
    /// The wire text of this value.
    pub fn as_wire(&self) -> &'static str {
        match self {
            UnavailableReason::NotSupported => "notSupported",
            UnavailableReason::InsecureContext => "insecureContext",
            UnavailableReason::BlockedByPolicy => "blockedByPolicy",
        }
    }
}

/// What a permission is for.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MediaDevice {
    Camera,
    Microphone,
}

impl MediaDevice {
    /// The wire text of this value.
    pub fn as_wire(&self) -> &'static str {
        match self {
            MediaDevice::Camera => "camera",
            MediaDevice::Microphone => "microphone",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum DeviceKind {
    Videoinput,
    Audioinput,
    Audiooutput,
}

impl DeviceKind {
    /// The wire text of this value.
    pub fn as_wire(&self) -> &'static str {
        match self {
            DeviceKind::Videoinput => "videoinput",
            DeviceKind::Audioinput => "audioinput",
            DeviceKind::Audiooutput => "audiooutput",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TrackKind {
    Audio,
    Video,
}

impl TrackKind {
    /// The wire text of this value.
    pub fn as_wire(&self) -> &'static str {
        match self {
            TrackKind::Audio => "audio",
            TrackKind::Video => "video",
        }
    }
}

/// notFound: no such device (or none at all); inUse: the device exists but could not be started, usually because another application holds it; overconstrained: no device satisfies what was asked.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum DeviceProblem {
    NotFound,
    InUse,
    Overconstrained,
}

impl DeviceProblem {
    /// The wire text of this value.
    pub fn as_wire(&self) -> &'static str {
        match self {
            DeviceProblem::NotFound => "notFound",
            DeviceProblem::InUse => "inUse",
            DeviceProblem::Overconstrained => "overconstrained",
        }
    }
}

/// Opaque; issued by this page's pack and meaningless anywhere else.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct CaptureId(pub String);

/// Opaque; issued by this page's pack and meaningless anywhere else.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct RecordingId(pub String);

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MediaStaleReason {
    Unknown,
    Disposed,
    OtherSession,
}

impl MediaStaleReason {
    /// The wire text of this value.
    pub fn as_wire(&self) -> &'static str {
        match self {
            MediaStaleReason::Unknown => "unknown",
            MediaStaleReason::Disposed => "disposed",
            MediaStaleReason::OtherSession => "other-session",
        }
    }
}

/// deviceId is the browser's per-origin identifier. label is empty until the user has granted access, as the browser decides.
#[derive(Debug, Clone, PartialEq)]
pub struct DeviceInfo {
    pub device_id: String,
    pub kind: DeviceKind,
    pub label: String,
}

#[derive(Debug, Clone, PartialEq)]
pub struct TrackInfo {
    pub kind: TrackKind,
    pub label: String,
    pub width: Option<i64>,
    pub height: Option<i64>,
}

/// A <video> named in HTML by data-media-preview; key selects a row by the nearest data-media-key ancestor.
#[derive(Debug, Clone, PartialEq)]
pub struct PreviewTarget {
    pub name: String,
    pub key: Option<String>,
}

#[derive(Debug, Clone, PartialEq)]
pub enum MediaRequest {
    /// The current permission state, without asking.
    Permission {
        device: MediaDevice,
    },
    /// PermissionChanged facts follow until unwatchPermission.
    WatchPermission {
        device: MediaDevice,
    },
    UnwatchPermission {
        device: MediaDevice,
    },
    /// The devices the browser lists. DevicesChanged facts follow any change.
    Devices,
    /// Start the camera, the microphone or both. May show the browser's permission prompt. audioDevice and videoDevice ask for exactly that device.
    StartCapture {
        audio: bool,
        video: bool,
        audio_device: Option<String>,
        video_device: Option<String>,
    },
    /// Show a capture in the named <video>, muted. One capture per element; a new preview replaces the old.
    Preview {
        capture: CaptureId,
        target: PreviewTarget,
    },
    Unpreview {
        target: PreviewTarget,
    },
    /// Stop every track of a capture, end any recording of it, clear its previews and release the id.
    Stop {
        capture: CaptureId,
    },
    /// Start recording a live capture. mimeType, if given, must be one this browser can record.
    Record {
        capture: CaptureId,
        mime_type: Option<String>,
    },
    /// Stop a recording; answers with its size once the browser has delivered every byte.
    Finish {
        recording: RecordingId,
    },
    /// Read length bytes (1 to MAX_READ_BYTES) of a finished recording from offset, as base64.
    Read {
        recording: RecordingId,
        offset: i64,
        length: i64,
    },
    /// Discard a recording, stopping it first if it is still running.
    Release {
        recording: RecordingId,
    },
}

#[derive(Debug, Clone, PartialEq)]
pub enum MediaResult {
    /// state is absent when this browser cannot report it.
    Permission {
        state: Option<PermissionState>,
    },
    Watching {
        state: PermissionState,
    },
    Unwatched,
    /// This browser cannot report permission changes.
    CannotWatch,
    Devices {
        devices: Vec<DeviceInfo>,
    },
    Capturing {
        capture: CaptureId,
        tracks: Vec<TrackInfo>,
    },
    /// startCapture with neither audio nor video.
    NothingRequested,
    Previewing,
    Unpreviewed,
    /// No element carries that preview name (and key).
    NotFound,
    Ambiguous {
        count: i64,
    },
    /// The named element is not a <video>.
    WrongElement,
    Stopped,
    RecordingStarted {
        recording: RecordingId,
        mime_type: String,
    },
    Recorded {
        recording: RecordingId,
        bytes: i64,
        mime_type: String,
        duration_ms: f64,
    },
    Read {
        data: String,
        bytes_read: i64,
        eof: bool,
    },
    Released,
    /// The user or the browser refused this origin the device.
    Denied,
    DeviceUnavailable {
        problem: DeviceProblem,
    },
    /// The capture's tracks have all ended, so it cannot be recorded or previewed.
    CaptureEnded,
    /// This browser cannot record that type (or cannot record at all).
    NotRecordable {
        mime_type: String,
    },
    /// A read of a recording that has not been finished. (release always succeeds: it stops the recording first.)
    StillRecording,
    InvalidRange,
    TooLarge {
        limit: i64,
    },
    Stale {
        reason: MediaStaleReason,
    },
    Unavailable {
        reason: UnavailableReason,
    },
    /// The engine cancelled the request. A capture that arrives afterwards is stopped at once and never reported.
    Cancelled,
    /// The browser failed in a way none of the above names. reason is its error name.
    Failed {
        reason: String,
    },
}

#[derive(Debug, Clone, PartialEq)]
pub enum MediaFact {
    /// A revocation is previous granted, state prompt or denied.
    PermissionChanged {
        device: MediaDevice,
        state: PermissionState,
        previous: PermissionState,
    },
    /// A device was added or removed; ask devices again.
    DevicesChanged,
    /// The browser ended one track of a capture (a device unplugged, access revoked).
    TrackEnded {
        capture: CaptureId,
        track: TrackKind,
    },
    /// Every track of the capture has ended. The id stays valid until stop.
    CaptureEnded {
        capture: CaptureId,
    },
    /// The browser stopped a recording the engine had not finished (its capture ended, or recording failed). finish still answers with what was recorded.
    RecordingInterrupted {
        recording: RecordingId,
        reason: String,
    },
}

pub fn decode_permission_state(value: &Value, path: &str) -> Result<PermissionState, DecodeError> {
    wire::enumeration(value, path, &[("granted", PermissionState::Granted), ("denied", PermissionState::Denied), ("prompt", PermissionState::Prompt)])
}

pub fn decode_unavailable_reason(value: &Value, path: &str) -> Result<UnavailableReason, DecodeError> {
    wire::enumeration(value, path, &[("notSupported", UnavailableReason::NotSupported), ("insecureContext", UnavailableReason::InsecureContext), ("blockedByPolicy", UnavailableReason::BlockedByPolicy)])
}

pub fn decode_media_device(value: &Value, path: &str) -> Result<MediaDevice, DecodeError> {
    wire::enumeration(value, path, &[("camera", MediaDevice::Camera), ("microphone", MediaDevice::Microphone)])
}

pub fn decode_device_kind(value: &Value, path: &str) -> Result<DeviceKind, DecodeError> {
    wire::enumeration(value, path, &[("videoinput", DeviceKind::Videoinput), ("audioinput", DeviceKind::Audioinput), ("audiooutput", DeviceKind::Audiooutput)])
}

pub fn decode_track_kind(value: &Value, path: &str) -> Result<TrackKind, DecodeError> {
    wire::enumeration(value, path, &[("audio", TrackKind::Audio), ("video", TrackKind::Video)])
}

pub fn decode_device_problem(value: &Value, path: &str) -> Result<DeviceProblem, DecodeError> {
    wire::enumeration(value, path, &[("notFound", DeviceProblem::NotFound), ("inUse", DeviceProblem::InUse), ("overconstrained", DeviceProblem::Overconstrained)])
}

pub fn decode_capture_id(value: &Value, path: &str) -> Result<CaptureId, DecodeError> {
    wire::string(value, path).map(CaptureId)
}

pub fn decode_recording_id(value: &Value, path: &str) -> Result<RecordingId, DecodeError> {
    wire::string(value, path).map(RecordingId)
}

pub fn decode_media_stale_reason(value: &Value, path: &str) -> Result<MediaStaleReason, DecodeError> {
    wire::enumeration(value, path, &[("unknown", MediaStaleReason::Unknown), ("disposed", MediaStaleReason::Disposed), ("other-session", MediaStaleReason::OtherSession)])
}

pub fn decode_device_info(value: &Value, path: &str) -> Result<DeviceInfo, DecodeError> {
    let props = wire::closed(wire::properties(value, path)?, path, &["deviceId", "kind", "label"])?;
    let f_device_id = wire::required(props, path, "deviceId", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    let f_kind = wire::required(props, path, "kind", |v0: &Value, p0: &str| decode_device_kind(v0, p0))?;
    let f_label = wire::required(props, path, "label", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    Ok(DeviceInfo { device_id: f_device_id, kind: f_kind, label: f_label })
}

pub fn decode_track_info(value: &Value, path: &str) -> Result<TrackInfo, DecodeError> {
    let props = wire::closed(wire::properties(value, path)?, path, &["kind", "label", "width", "height"])?;
    let f_kind = wire::required(props, path, "kind", |v0: &Value, p0: &str| decode_track_kind(v0, p0))?;
    let f_label = wire::required(props, path, "label", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    let f_width = wire::optional(props, path, "width", |v0: &Value, p0: &str| wire::int(v0, p0))?;
    let f_height = wire::optional(props, path, "height", |v0: &Value, p0: &str| wire::int(v0, p0))?;
    Ok(TrackInfo { kind: f_kind, label: f_label, width: f_width, height: f_height })
}

pub fn decode_preview_target(value: &Value, path: &str) -> Result<PreviewTarget, DecodeError> {
    let props = wire::closed(wire::properties(value, path)?, path, &["name", "key"])?;
    let f_name = wire::required(props, path, "name", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    let f_key = wire::optional(props, path, "key", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    Ok(PreviewTarget { name: f_name, key: f_key })
}

pub fn decode_media_request(value: &Value, path: &str) -> Result<MediaRequest, DecodeError> {
    match wire::tag(value, path, "operation")?.as_str() {
        "permission" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation", "device"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "permission"))?;
            let f_device = wire::required(props, path, "device", |v0: &Value, p0: &str| decode_media_device(v0, p0))?;
            Ok(MediaRequest::Permission { device: f_device })
        }
        "watchPermission" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation", "device"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "watchPermission"))?;
            let f_device = wire::required(props, path, "device", |v0: &Value, p0: &str| decode_media_device(v0, p0))?;
            Ok(MediaRequest::WatchPermission { device: f_device })
        }
        "unwatchPermission" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation", "device"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "unwatchPermission"))?;
            let f_device = wire::required(props, path, "device", |v0: &Value, p0: &str| decode_media_device(v0, p0))?;
            Ok(MediaRequest::UnwatchPermission { device: f_device })
        }
        "devices" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "devices"))?;
            Ok(MediaRequest::Devices)
        }
        "startCapture" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation", "audio", "video", "audioDevice", "videoDevice"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "startCapture"))?;
            let f_audio = wire::required(props, path, "audio", |v0: &Value, p0: &str| wire::boolean(v0, p0))?;
            let f_video = wire::required(props, path, "video", |v0: &Value, p0: &str| wire::boolean(v0, p0))?;
            let f_audio_device = wire::optional(props, path, "audioDevice", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            let f_video_device = wire::optional(props, path, "videoDevice", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            Ok(MediaRequest::StartCapture { audio: f_audio, video: f_video, audio_device: f_audio_device, video_device: f_video_device })
        }
        "preview" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation", "capture", "target"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "preview"))?;
            let f_capture = wire::required(props, path, "capture", |v0: &Value, p0: &str| decode_capture_id(v0, p0))?;
            let f_target = wire::required(props, path, "target", |v0: &Value, p0: &str| decode_preview_target(v0, p0))?;
            Ok(MediaRequest::Preview { capture: f_capture, target: f_target })
        }
        "unpreview" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation", "target"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "unpreview"))?;
            let f_target = wire::required(props, path, "target", |v0: &Value, p0: &str| decode_preview_target(v0, p0))?;
            Ok(MediaRequest::Unpreview { target: f_target })
        }
        "stop" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation", "capture"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "stop"))?;
            let f_capture = wire::required(props, path, "capture", |v0: &Value, p0: &str| decode_capture_id(v0, p0))?;
            Ok(MediaRequest::Stop { capture: f_capture })
        }
        "record" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation", "capture", "mimeType"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "record"))?;
            let f_capture = wire::required(props, path, "capture", |v0: &Value, p0: &str| decode_capture_id(v0, p0))?;
            let f_mime_type = wire::optional(props, path, "mimeType", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            Ok(MediaRequest::Record { capture: f_capture, mime_type: f_mime_type })
        }
        "finish" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation", "recording"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "finish"))?;
            let f_recording = wire::required(props, path, "recording", |v0: &Value, p0: &str| decode_recording_id(v0, p0))?;
            Ok(MediaRequest::Finish { recording: f_recording })
        }
        "read" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation", "recording", "offset", "length"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "read"))?;
            let f_recording = wire::required(props, path, "recording", |v0: &Value, p0: &str| decode_recording_id(v0, p0))?;
            let f_offset = wire::required(props, path, "offset", |v0: &Value, p0: &str| wire::int(v0, p0))?;
            let f_length = wire::required(props, path, "length", |v0: &Value, p0: &str| wire::int(v0, p0))?;
            Ok(MediaRequest::Read { recording: f_recording, offset: f_offset, length: f_length })
        }
        "release" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation", "recording"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "release"))?;
            let f_recording = wire::required(props, path, "recording", |v0: &Value, p0: &str| decode_recording_id(v0, p0))?;
            Ok(MediaRequest::Release { recording: f_recording })
        }
        other => Err(wire::unknown_variant(&format!("{}.operation", path), other)),
    }
}

pub fn decode_media_result(value: &Value, path: &str) -> Result<MediaResult, DecodeError> {
    match wire::tag(value, path, "kind")?.as_str() {
        "Permission" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "state"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Permission"))?;
            let f_state = wire::optional(props, path, "state", |v0: &Value, p0: &str| decode_permission_state(v0, p0))?;
            Ok(MediaResult::Permission { state: f_state })
        }
        "Watching" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "state"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Watching"))?;
            let f_state = wire::required(props, path, "state", |v0: &Value, p0: &str| decode_permission_state(v0, p0))?;
            Ok(MediaResult::Watching { state: f_state })
        }
        "Unwatched" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Unwatched"))?;
            Ok(MediaResult::Unwatched)
        }
        "CannotWatch" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "CannotWatch"))?;
            Ok(MediaResult::CannotWatch)
        }
        "Devices" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "devices"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Devices"))?;
            let f_devices = wire::required(props, path, "devices", |v0: &Value, p0: &str| wire::list(v0, p0, |v1: &Value, p1: &str| decode_device_info(v1, p1)))?;
            Ok(MediaResult::Devices { devices: f_devices })
        }
        "Capturing" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "capture", "tracks"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Capturing"))?;
            let f_capture = wire::required(props, path, "capture", |v0: &Value, p0: &str| decode_capture_id(v0, p0))?;
            let f_tracks = wire::required(props, path, "tracks", |v0: &Value, p0: &str| wire::list(v0, p0, |v1: &Value, p1: &str| decode_track_info(v1, p1)))?;
            Ok(MediaResult::Capturing { capture: f_capture, tracks: f_tracks })
        }
        "NothingRequested" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "NothingRequested"))?;
            Ok(MediaResult::NothingRequested)
        }
        "Previewing" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Previewing"))?;
            Ok(MediaResult::Previewing)
        }
        "Unpreviewed" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Unpreviewed"))?;
            Ok(MediaResult::Unpreviewed)
        }
        "NotFound" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "NotFound"))?;
            Ok(MediaResult::NotFound)
        }
        "Ambiguous" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "count"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Ambiguous"))?;
            let f_count = wire::required(props, path, "count", |v0: &Value, p0: &str| wire::int(v0, p0))?;
            Ok(MediaResult::Ambiguous { count: f_count })
        }
        "WrongElement" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "WrongElement"))?;
            Ok(MediaResult::WrongElement)
        }
        "Stopped" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Stopped"))?;
            Ok(MediaResult::Stopped)
        }
        "RecordingStarted" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "recording", "mimeType"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "RecordingStarted"))?;
            let f_recording = wire::required(props, path, "recording", |v0: &Value, p0: &str| decode_recording_id(v0, p0))?;
            let f_mime_type = wire::required(props, path, "mimeType", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            Ok(MediaResult::RecordingStarted { recording: f_recording, mime_type: f_mime_type })
        }
        "Recorded" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "recording", "bytes", "mimeType", "durationMs"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Recorded"))?;
            let f_recording = wire::required(props, path, "recording", |v0: &Value, p0: &str| decode_recording_id(v0, p0))?;
            let f_bytes = wire::required(props, path, "bytes", |v0: &Value, p0: &str| wire::int(v0, p0))?;
            let f_mime_type = wire::required(props, path, "mimeType", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            let f_duration_ms = wire::required(props, path, "durationMs", |v0: &Value, p0: &str| wire::number(v0, p0))?;
            Ok(MediaResult::Recorded { recording: f_recording, bytes: f_bytes, mime_type: f_mime_type, duration_ms: f_duration_ms })
        }
        "Read" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "data", "bytesRead", "eof"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Read"))?;
            let f_data = wire::required(props, path, "data", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            let f_bytes_read = wire::required(props, path, "bytesRead", |v0: &Value, p0: &str| wire::int(v0, p0))?;
            let f_eof = wire::required(props, path, "eof", |v0: &Value, p0: &str| wire::boolean(v0, p0))?;
            Ok(MediaResult::Read { data: f_data, bytes_read: f_bytes_read, eof: f_eof })
        }
        "Released" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Released"))?;
            Ok(MediaResult::Released)
        }
        "Denied" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Denied"))?;
            Ok(MediaResult::Denied)
        }
        "DeviceUnavailable" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "problem"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "DeviceUnavailable"))?;
            let f_problem = wire::required(props, path, "problem", |v0: &Value, p0: &str| decode_device_problem(v0, p0))?;
            Ok(MediaResult::DeviceUnavailable { problem: f_problem })
        }
        "CaptureEnded" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "CaptureEnded"))?;
            Ok(MediaResult::CaptureEnded)
        }
        "NotRecordable" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "mimeType"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "NotRecordable"))?;
            let f_mime_type = wire::required(props, path, "mimeType", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            Ok(MediaResult::NotRecordable { mime_type: f_mime_type })
        }
        "StillRecording" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "StillRecording"))?;
            Ok(MediaResult::StillRecording)
        }
        "InvalidRange" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "InvalidRange"))?;
            Ok(MediaResult::InvalidRange)
        }
        "TooLarge" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "limit"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "TooLarge"))?;
            let f_limit = wire::required(props, path, "limit", |v0: &Value, p0: &str| wire::int(v0, p0))?;
            Ok(MediaResult::TooLarge { limit: f_limit })
        }
        "Stale" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "reason"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Stale"))?;
            let f_reason = wire::required(props, path, "reason", |v0: &Value, p0: &str| decode_media_stale_reason(v0, p0))?;
            Ok(MediaResult::Stale { reason: f_reason })
        }
        "Unavailable" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "reason"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Unavailable"))?;
            let f_reason = wire::required(props, path, "reason", |v0: &Value, p0: &str| decode_unavailable_reason(v0, p0))?;
            Ok(MediaResult::Unavailable { reason: f_reason })
        }
        "Cancelled" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Cancelled"))?;
            Ok(MediaResult::Cancelled)
        }
        "Failed" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "reason"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Failed"))?;
            let f_reason = wire::required(props, path, "reason", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            Ok(MediaResult::Failed { reason: f_reason })
        }
        other => Err(wire::unknown_variant(&format!("{}.kind", path), other)),
    }
}

pub fn decode_media_fact(value: &Value, path: &str) -> Result<MediaFact, DecodeError> {
    match wire::tag(value, path, "kind")?.as_str() {
        "PermissionChanged" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "device", "state", "previous"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "PermissionChanged"))?;
            let f_device = wire::required(props, path, "device", |v0: &Value, p0: &str| decode_media_device(v0, p0))?;
            let f_state = wire::required(props, path, "state", |v0: &Value, p0: &str| decode_permission_state(v0, p0))?;
            let f_previous = wire::required(props, path, "previous", |v0: &Value, p0: &str| decode_permission_state(v0, p0))?;
            Ok(MediaFact::PermissionChanged { device: f_device, state: f_state, previous: f_previous })
        }
        "DevicesChanged" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "DevicesChanged"))?;
            Ok(MediaFact::DevicesChanged)
        }
        "TrackEnded" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "capture", "track"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "TrackEnded"))?;
            let f_capture = wire::required(props, path, "capture", |v0: &Value, p0: &str| decode_capture_id(v0, p0))?;
            let f_track = wire::required(props, path, "track", |v0: &Value, p0: &str| decode_track_kind(v0, p0))?;
            Ok(MediaFact::TrackEnded { capture: f_capture, track: f_track })
        }
        "CaptureEnded" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "capture"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "CaptureEnded"))?;
            let f_capture = wire::required(props, path, "capture", |v0: &Value, p0: &str| decode_capture_id(v0, p0))?;
            Ok(MediaFact::CaptureEnded { capture: f_capture })
        }
        "RecordingInterrupted" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "recording", "reason"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "RecordingInterrupted"))?;
            let f_recording = wire::required(props, path, "recording", |v0: &Value, p0: &str| decode_recording_id(v0, p0))?;
            let f_reason = wire::required(props, path, "reason", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            Ok(MediaFact::RecordingInterrupted { recording: f_recording, reason: f_reason })
        }
        other => Err(wire::unknown_variant(&format!("{}.kind", path), other)),
    }
}

pub fn encode_permission_state(value: &PermissionState) -> Value {
    match value {
        PermissionState::Granted => wire::of_string("granted"),
        PermissionState::Denied => wire::of_string("denied"),
        PermissionState::Prompt => wire::of_string("prompt"),
    }
}

pub fn encode_unavailable_reason(value: &UnavailableReason) -> Value {
    match value {
        UnavailableReason::NotSupported => wire::of_string("notSupported"),
        UnavailableReason::InsecureContext => wire::of_string("insecureContext"),
        UnavailableReason::BlockedByPolicy => wire::of_string("blockedByPolicy"),
    }
}

pub fn encode_media_device(value: &MediaDevice) -> Value {
    match value {
        MediaDevice::Camera => wire::of_string("camera"),
        MediaDevice::Microphone => wire::of_string("microphone"),
    }
}

pub fn encode_device_kind(value: &DeviceKind) -> Value {
    match value {
        DeviceKind::Videoinput => wire::of_string("videoinput"),
        DeviceKind::Audioinput => wire::of_string("audioinput"),
        DeviceKind::Audiooutput => wire::of_string("audiooutput"),
    }
}

pub fn encode_track_kind(value: &TrackKind) -> Value {
    match value {
        TrackKind::Audio => wire::of_string("audio"),
        TrackKind::Video => wire::of_string("video"),
    }
}

pub fn encode_device_problem(value: &DeviceProblem) -> Value {
    match value {
        DeviceProblem::NotFound => wire::of_string("notFound"),
        DeviceProblem::InUse => wire::of_string("inUse"),
        DeviceProblem::Overconstrained => wire::of_string("overconstrained"),
    }
}

pub fn encode_capture_id(value: &CaptureId) -> Value {
    wire::of_string(&value.0)
}

pub fn encode_recording_id(value: &RecordingId) -> Value {
    wire::of_string(&value.0)
}

pub fn encode_media_stale_reason(value: &MediaStaleReason) -> Value {
    match value {
        MediaStaleReason::Unknown => wire::of_string("unknown"),
        MediaStaleReason::Disposed => wire::of_string("disposed"),
        MediaStaleReason::OtherSession => wire::of_string("other-session"),
    }
}

pub fn encode_device_info(value: &DeviceInfo) -> Value {
    wire::of_object(vec![Some(("deviceId", wire::of_string(&value.device_id))), Some(("kind", encode_device_kind(&value.kind))), Some(("label", wire::of_string(&value.label)))])
}

pub fn encode_track_info(value: &TrackInfo) -> Value {
    wire::of_object(vec![Some(("kind", encode_track_kind(&value.kind))), Some(("label", wire::of_string(&value.label))), (&value.width).as_ref().map(|x0| ("width", wire::of_int(*x0))), (&value.height).as_ref().map(|x0| ("height", wire::of_int(*x0)))])
}

pub fn encode_preview_target(value: &PreviewTarget) -> Value {
    wire::of_object(vec![Some(("name", wire::of_string(&value.name))), (&value.key).as_ref().map(|x0| ("key", wire::of_string(x0)))])
}

pub fn encode_media_request(value: &MediaRequest) -> Value {
    match value {
        MediaRequest::Permission { device: f_device } => wire::of_object(vec![Some(("operation", wire::of_string("permission"))), Some(("device", encode_media_device(f_device)))]),
        MediaRequest::WatchPermission { device: f_device } => wire::of_object(vec![Some(("operation", wire::of_string("watchPermission"))), Some(("device", encode_media_device(f_device)))]),
        MediaRequest::UnwatchPermission { device: f_device } => wire::of_object(vec![Some(("operation", wire::of_string("unwatchPermission"))), Some(("device", encode_media_device(f_device)))]),
        MediaRequest::Devices => wire::of_object(vec![Some(("operation", wire::of_string("devices")))]),
        MediaRequest::StartCapture { audio: f_audio, video: f_video, audio_device: f_audio_device, video_device: f_video_device } => wire::of_object(vec![Some(("operation", wire::of_string("startCapture"))), Some(("audio", wire::of_bool(*f_audio))), Some(("video", wire::of_bool(*f_video))), (f_audio_device).as_ref().map(|x0| ("audioDevice", wire::of_string(x0))), (f_video_device).as_ref().map(|x0| ("videoDevice", wire::of_string(x0)))]),
        MediaRequest::Preview { capture: f_capture, target: f_target } => wire::of_object(vec![Some(("operation", wire::of_string("preview"))), Some(("capture", encode_capture_id(f_capture))), Some(("target", encode_preview_target(f_target)))]),
        MediaRequest::Unpreview { target: f_target } => wire::of_object(vec![Some(("operation", wire::of_string("unpreview"))), Some(("target", encode_preview_target(f_target)))]),
        MediaRequest::Stop { capture: f_capture } => wire::of_object(vec![Some(("operation", wire::of_string("stop"))), Some(("capture", encode_capture_id(f_capture)))]),
        MediaRequest::Record { capture: f_capture, mime_type: f_mime_type } => wire::of_object(vec![Some(("operation", wire::of_string("record"))), Some(("capture", encode_capture_id(f_capture))), (f_mime_type).as_ref().map(|x0| ("mimeType", wire::of_string(x0)))]),
        MediaRequest::Finish { recording: f_recording } => wire::of_object(vec![Some(("operation", wire::of_string("finish"))), Some(("recording", encode_recording_id(f_recording)))]),
        MediaRequest::Read { recording: f_recording, offset: f_offset, length: f_length } => wire::of_object(vec![Some(("operation", wire::of_string("read"))), Some(("recording", encode_recording_id(f_recording))), Some(("offset", wire::of_int(*f_offset))), Some(("length", wire::of_int(*f_length)))]),
        MediaRequest::Release { recording: f_recording } => wire::of_object(vec![Some(("operation", wire::of_string("release"))), Some(("recording", encode_recording_id(f_recording)))]),
    }
}

pub fn encode_media_result(value: &MediaResult) -> Value {
    match value {
        MediaResult::Permission { state: f_state } => wire::of_object(vec![Some(("kind", wire::of_string("Permission"))), (f_state).as_ref().map(|x0| ("state", encode_permission_state(x0)))]),
        MediaResult::Watching { state: f_state } => wire::of_object(vec![Some(("kind", wire::of_string("Watching"))), Some(("state", encode_permission_state(f_state)))]),
        MediaResult::Unwatched => wire::of_object(vec![Some(("kind", wire::of_string("Unwatched")))]),
        MediaResult::CannotWatch => wire::of_object(vec![Some(("kind", wire::of_string("CannotWatch")))]),
        MediaResult::Devices { devices: f_devices } => wire::of_object(vec![Some(("kind", wire::of_string("Devices"))), Some(("devices", wire::of_list(f_devices, |x0| encode_device_info(x0))))]),
        MediaResult::Capturing { capture: f_capture, tracks: f_tracks } => wire::of_object(vec![Some(("kind", wire::of_string("Capturing"))), Some(("capture", encode_capture_id(f_capture))), Some(("tracks", wire::of_list(f_tracks, |x0| encode_track_info(x0))))]),
        MediaResult::NothingRequested => wire::of_object(vec![Some(("kind", wire::of_string("NothingRequested")))]),
        MediaResult::Previewing => wire::of_object(vec![Some(("kind", wire::of_string("Previewing")))]),
        MediaResult::Unpreviewed => wire::of_object(vec![Some(("kind", wire::of_string("Unpreviewed")))]),
        MediaResult::NotFound => wire::of_object(vec![Some(("kind", wire::of_string("NotFound")))]),
        MediaResult::Ambiguous { count: f_count } => wire::of_object(vec![Some(("kind", wire::of_string("Ambiguous"))), Some(("count", wire::of_int(*f_count)))]),
        MediaResult::WrongElement => wire::of_object(vec![Some(("kind", wire::of_string("WrongElement")))]),
        MediaResult::Stopped => wire::of_object(vec![Some(("kind", wire::of_string("Stopped")))]),
        MediaResult::RecordingStarted { recording: f_recording, mime_type: f_mime_type } => wire::of_object(vec![Some(("kind", wire::of_string("RecordingStarted"))), Some(("recording", encode_recording_id(f_recording))), Some(("mimeType", wire::of_string(f_mime_type)))]),
        MediaResult::Recorded { recording: f_recording, bytes: f_bytes, mime_type: f_mime_type, duration_ms: f_duration_ms } => wire::of_object(vec![Some(("kind", wire::of_string("Recorded"))), Some(("recording", encode_recording_id(f_recording))), Some(("bytes", wire::of_int(*f_bytes))), Some(("mimeType", wire::of_string(f_mime_type))), Some(("durationMs", wire::of_number(*f_duration_ms)))]),
        MediaResult::Read { data: f_data, bytes_read: f_bytes_read, eof: f_eof } => wire::of_object(vec![Some(("kind", wire::of_string("Read"))), Some(("data", wire::of_string(f_data))), Some(("bytesRead", wire::of_int(*f_bytes_read))), Some(("eof", wire::of_bool(*f_eof)))]),
        MediaResult::Released => wire::of_object(vec![Some(("kind", wire::of_string("Released")))]),
        MediaResult::Denied => wire::of_object(vec![Some(("kind", wire::of_string("Denied")))]),
        MediaResult::DeviceUnavailable { problem: f_problem } => wire::of_object(vec![Some(("kind", wire::of_string("DeviceUnavailable"))), Some(("problem", encode_device_problem(f_problem)))]),
        MediaResult::CaptureEnded => wire::of_object(vec![Some(("kind", wire::of_string("CaptureEnded")))]),
        MediaResult::NotRecordable { mime_type: f_mime_type } => wire::of_object(vec![Some(("kind", wire::of_string("NotRecordable"))), Some(("mimeType", wire::of_string(f_mime_type)))]),
        MediaResult::StillRecording => wire::of_object(vec![Some(("kind", wire::of_string("StillRecording")))]),
        MediaResult::InvalidRange => wire::of_object(vec![Some(("kind", wire::of_string("InvalidRange")))]),
        MediaResult::TooLarge { limit: f_limit } => wire::of_object(vec![Some(("kind", wire::of_string("TooLarge"))), Some(("limit", wire::of_int(*f_limit)))]),
        MediaResult::Stale { reason: f_reason } => wire::of_object(vec![Some(("kind", wire::of_string("Stale"))), Some(("reason", encode_media_stale_reason(f_reason)))]),
        MediaResult::Unavailable { reason: f_reason } => wire::of_object(vec![Some(("kind", wire::of_string("Unavailable"))), Some(("reason", encode_unavailable_reason(f_reason)))]),
        MediaResult::Cancelled => wire::of_object(vec![Some(("kind", wire::of_string("Cancelled")))]),
        MediaResult::Failed { reason: f_reason } => wire::of_object(vec![Some(("kind", wire::of_string("Failed"))), Some(("reason", wire::of_string(f_reason)))]),
    }
}

pub fn encode_media_fact(value: &MediaFact) -> Value {
    match value {
        MediaFact::PermissionChanged { device: f_device, state: f_state, previous: f_previous } => wire::of_object(vec![Some(("kind", wire::of_string("PermissionChanged"))), Some(("device", encode_media_device(f_device))), Some(("state", encode_permission_state(f_state))), Some(("previous", encode_permission_state(f_previous)))]),
        MediaFact::DevicesChanged => wire::of_object(vec![Some(("kind", wire::of_string("DevicesChanged")))]),
        MediaFact::TrackEnded { capture: f_capture, track: f_track } => wire::of_object(vec![Some(("kind", wire::of_string("TrackEnded"))), Some(("capture", encode_capture_id(f_capture))), Some(("track", encode_track_kind(f_track)))]),
        MediaFact::CaptureEnded { capture: f_capture } => wire::of_object(vec![Some(("kind", wire::of_string("CaptureEnded"))), Some(("capture", encode_capture_id(f_capture)))]),
        MediaFact::RecordingInterrupted { recording: f_recording, reason: f_reason } => wire::of_object(vec![Some(("kind", wire::of_string("RecordingInterrupted"))), Some(("recording", encode_recording_id(f_recording))), Some(("reason", wire::of_string(f_reason)))]),
    }
}

/// Parses untrusted JSON text into a PermissionState, or says where and why it is not one.
pub fn parse_permission_state(json: &str) -> Result<PermissionState, DecodeError> {
    wire::parse(json, decode_permission_state)
}

/// Serializes a PermissionState to wire JSON text.
pub fn serialize_permission_state(value: &PermissionState) -> String {
    encode_permission_state(value).to_string()
}

/// Parses untrusted JSON text into a UnavailableReason, or says where and why it is not one.
pub fn parse_unavailable_reason(json: &str) -> Result<UnavailableReason, DecodeError> {
    wire::parse(json, decode_unavailable_reason)
}

/// Serializes a UnavailableReason to wire JSON text.
pub fn serialize_unavailable_reason(value: &UnavailableReason) -> String {
    encode_unavailable_reason(value).to_string()
}

/// Parses untrusted JSON text into a MediaDevice, or says where and why it is not one.
pub fn parse_media_device(json: &str) -> Result<MediaDevice, DecodeError> {
    wire::parse(json, decode_media_device)
}

/// Serializes a MediaDevice to wire JSON text.
pub fn serialize_media_device(value: &MediaDevice) -> String {
    encode_media_device(value).to_string()
}

/// Parses untrusted JSON text into a DeviceKind, or says where and why it is not one.
pub fn parse_device_kind(json: &str) -> Result<DeviceKind, DecodeError> {
    wire::parse(json, decode_device_kind)
}

/// Serializes a DeviceKind to wire JSON text.
pub fn serialize_device_kind(value: &DeviceKind) -> String {
    encode_device_kind(value).to_string()
}

/// Parses untrusted JSON text into a TrackKind, or says where and why it is not one.
pub fn parse_track_kind(json: &str) -> Result<TrackKind, DecodeError> {
    wire::parse(json, decode_track_kind)
}

/// Serializes a TrackKind to wire JSON text.
pub fn serialize_track_kind(value: &TrackKind) -> String {
    encode_track_kind(value).to_string()
}

/// Parses untrusted JSON text into a DeviceProblem, or says where and why it is not one.
pub fn parse_device_problem(json: &str) -> Result<DeviceProblem, DecodeError> {
    wire::parse(json, decode_device_problem)
}

/// Serializes a DeviceProblem to wire JSON text.
pub fn serialize_device_problem(value: &DeviceProblem) -> String {
    encode_device_problem(value).to_string()
}

/// Parses untrusted JSON text into a CaptureId, or says where and why it is not one.
pub fn parse_capture_id(json: &str) -> Result<CaptureId, DecodeError> {
    wire::parse(json, decode_capture_id)
}

/// Serializes a CaptureId to wire JSON text.
pub fn serialize_capture_id(value: &CaptureId) -> String {
    encode_capture_id(value).to_string()
}

/// Parses untrusted JSON text into a RecordingId, or says where and why it is not one.
pub fn parse_recording_id(json: &str) -> Result<RecordingId, DecodeError> {
    wire::parse(json, decode_recording_id)
}

/// Serializes a RecordingId to wire JSON text.
pub fn serialize_recording_id(value: &RecordingId) -> String {
    encode_recording_id(value).to_string()
}

/// Parses untrusted JSON text into a MediaStaleReason, or says where and why it is not one.
pub fn parse_media_stale_reason(json: &str) -> Result<MediaStaleReason, DecodeError> {
    wire::parse(json, decode_media_stale_reason)
}

/// Serializes a MediaStaleReason to wire JSON text.
pub fn serialize_media_stale_reason(value: &MediaStaleReason) -> String {
    encode_media_stale_reason(value).to_string()
}

/// Parses untrusted JSON text into a DeviceInfo, or says where and why it is not one.
pub fn parse_device_info(json: &str) -> Result<DeviceInfo, DecodeError> {
    wire::parse(json, decode_device_info)
}

/// Serializes a DeviceInfo to wire JSON text.
pub fn serialize_device_info(value: &DeviceInfo) -> String {
    encode_device_info(value).to_string()
}

/// Parses untrusted JSON text into a TrackInfo, or says where and why it is not one.
pub fn parse_track_info(json: &str) -> Result<TrackInfo, DecodeError> {
    wire::parse(json, decode_track_info)
}

/// Serializes a TrackInfo to wire JSON text.
pub fn serialize_track_info(value: &TrackInfo) -> String {
    encode_track_info(value).to_string()
}

/// Parses untrusted JSON text into a PreviewTarget, or says where and why it is not one.
pub fn parse_preview_target(json: &str) -> Result<PreviewTarget, DecodeError> {
    wire::parse(json, decode_preview_target)
}

/// Serializes a PreviewTarget to wire JSON text.
pub fn serialize_preview_target(value: &PreviewTarget) -> String {
    encode_preview_target(value).to_string()
}

/// Parses untrusted JSON text into a MediaRequest, or says where and why it is not one.
pub fn parse_media_request(json: &str) -> Result<MediaRequest, DecodeError> {
    wire::parse(json, decode_media_request)
}

/// Serializes a MediaRequest to wire JSON text.
pub fn serialize_media_request(value: &MediaRequest) -> String {
    encode_media_request(value).to_string()
}

/// Parses untrusted JSON text into a MediaResult, or says where and why it is not one.
pub fn parse_media_result(json: &str) -> Result<MediaResult, DecodeError> {
    wire::parse(json, decode_media_result)
}

/// Serializes a MediaResult to wire JSON text.
pub fn serialize_media_result(value: &MediaResult) -> String {
    encode_media_result(value).to_string()
}

/// Parses untrusted JSON text into a MediaFact, or says where and why it is not one.
pub fn parse_media_fact(json: &str) -> Result<MediaFact, DecodeError> {
    wire::parse(json, decode_media_fact)
}

/// Serializes a MediaFact to wire JSON text.
pub fn serialize_media_fact(value: &MediaFact) -> String {
    encode_media_fact(value).to_string()
}

/// Decode-then-encode by type name. Used only by the shared conformance runner.
pub fn conformance_round_trip(type_name: &str, value: &Value) -> Option<Result<Value, DecodeError>> {
    match type_name {
        "PermissionState" => Some(decode_permission_state(value, "$").map(|decoded| encode_permission_state(&decoded))),
        "UnavailableReason" => Some(decode_unavailable_reason(value, "$").map(|decoded| encode_unavailable_reason(&decoded))),
        "MediaDevice" => Some(decode_media_device(value, "$").map(|decoded| encode_media_device(&decoded))),
        "DeviceKind" => Some(decode_device_kind(value, "$").map(|decoded| encode_device_kind(&decoded))),
        "TrackKind" => Some(decode_track_kind(value, "$").map(|decoded| encode_track_kind(&decoded))),
        "DeviceProblem" => Some(decode_device_problem(value, "$").map(|decoded| encode_device_problem(&decoded))),
        "CaptureId" => Some(decode_capture_id(value, "$").map(|decoded| encode_capture_id(&decoded))),
        "RecordingId" => Some(decode_recording_id(value, "$").map(|decoded| encode_recording_id(&decoded))),
        "MediaStaleReason" => Some(decode_media_stale_reason(value, "$").map(|decoded| encode_media_stale_reason(&decoded))),
        "DeviceInfo" => Some(decode_device_info(value, "$").map(|decoded| encode_device_info(&decoded))),
        "TrackInfo" => Some(decode_track_info(value, "$").map(|decoded| encode_track_info(&decoded))),
        "PreviewTarget" => Some(decode_preview_target(value, "$").map(|decoded| encode_preview_target(&decoded))),
        "MediaRequest" => Some(decode_media_request(value, "$").map(|decoded| encode_media_request(&decoded))),
        "MediaResult" => Some(decode_media_result(value, "$").map(|decoded| encode_media_result(&decoded))),
        "MediaFact" => Some(decode_media_fact(value, "$").map(|decoded| encode_media_fact(&decoded))),
        _ => None,
    }
}
