// <auto-generated by limen-contract-gen>
// GENERATED FILE — DO NOT EDIT. Change the contract and run `npm run contract:generate`.
// source: contract/realtime.contract.json
// unit: limen.realtime@1
// contract-fingerprint: sha256:00561fb3820d20931bc667dc4f12c3acbc84963a096a5b9db31495681981454e
// generator: limen-contract-gen/1 (rust-unit)
// content-hash: sha256:331ec885a307b591d80e50f2d3a78671f763a8d9d34350d8bdb504926d853b23
// </auto-generated>
//! Long-lived browser I/O: WebSocket and Server-Sent Events (LCP-016). The engine opens a connection and gets an opaque id; everything that happens to it arrives as facts under that id, ending with exactly one Closed. The pack never reconnects — EventSource's native retry is stopped and reported as Closed — so reconnection, backoff and replacement are the engine's decisions. Payloads are uninterpreted text.


use serde_json::Value;

use crate::runtime::{wire, DecodeError};

/// The identity of this generated contract unit, exchanged in the handshake.
pub mod contract {
    pub const UNIT: &str = "limen.realtime";
    pub const VERSION: i64 = 1;
    pub const FINGERPRINT: &str = "sha256:00561fb3820d20931bc667dc4f12c3acbc84963a096a5b9db31495681981454e";
}

/// Opaque; issued by this page's pack and meaningless anywhere else.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ConnectionId(pub String);

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ConnectionStaleReason {
    Unknown,
    Disposed,
    OtherSession,
}

impl ConnectionStaleReason {
    /// The wire text of this value.
    pub fn as_wire(&self) -> &'static str {
        match self {
            ConnectionStaleReason::Unknown => "unknown",
            ConnectionStaleReason::Disposed => "disposed",
            ConnectionStaleReason::OtherSession => "other-session",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ReadyState {
    Connecting,
    Open,
    Closing,
    Closed,
}

impl ReadyState {
    /// The wire text of this value.
    pub fn as_wire(&self) -> &'static str {
        match self {
            ReadyState::Connecting => "connecting",
            ReadyState::Open => "open",
            ReadyState::Closing => "closing",
            ReadyState::Closed => "closed",
        }
    }
}

/// Who ended a connection the engine did not close (an engine's own close is answered Closed and nothing follows). remote: the server closed it. error: the connection failed, or an event stream dropped and would have retried on its own.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum CloseInitiator {
    Remote,
    Error,
}

impl CloseInitiator {
    /// The wire text of this value.
    pub fn as_wire(&self) -> &'static str {
        match self {
            CloseInitiator::Remote => "remote",
            CloseInitiator::Error => "error",
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub enum RealtimeRequest {
    /// url is ws:, wss:, or http(s): (mapped to ws(s):), absolute or relative to the page.
    OpenWebSocket {
        url: String,
        protocols: Vec<String>,
    },
    /// url is http(s):, absolute or relative to the page. Unnamed events arrive as Message; a named event type arrives only if it is listed in events (the browser offers no way to hear every type).
    OpenEventSource {
        url: String,
        with_credentials: bool,
        events: Vec<String>,
    },
    /// Send one text message on an open WebSocket.
    Send {
        connection: ConnectionId,
        text: String,
    },
    /// Close a connection. It is answered Closed and nothing more is heard for it — not even a message the browser had already queued.
    Close {
        connection: ConnectionId,
        code: Option<i64>,
        reason: Option<String>,
    },
}

#[derive(Debug, Clone, PartialEq)]
pub enum RealtimeResult {
    /// Facts for this connection follow: Opened, Message…, then exactly one Closed — unless the engine closes it first.
    Connecting {
        connection: ConnectionId,
    },
    Sent {
        buffered_amount: i64,
    },
    Closed,
    /// send before Opened, or while closing.
    NotOpen {
        state: ReadyState,
    },
    /// An event stream is receive-only.
    NotSendable,
    /// No such live connection: never issued here, already closed, or from before a reload.
    Stale {
        reason: ConnectionStaleReason,
    },
    /// The URL does not parse, or its scheme is not one this transport takes. Named by scheme only, never by value.
    InvalidUrl {
        scheme: String,
    },
    /// A WebSocket close code must be 1000 or 3000–4999.
    InvalidCloseCode,
    /// The browser threw (for example a content security policy). The exception's name only.
    Refused {
        reason: String,
    },
    Unsupported,
    Cancelled,
}

#[derive(Debug, Clone, PartialEq)]
pub enum RealtimeFact {
    Opened {
        connection: ConnectionId,
        /// The subprotocol the server chose; empty for none and for event streams.
        protocol: String,
    },
    Message {
        connection: ConnectionId,
        data: String,
        /// An event stream's event type, when not the default message.
        event: Option<String>,
        last_event_id: Option<String>,
    },
    /// A binary WebSocket frame: its size only. Bytes do not cross.
    BinaryMessage {
        connection: ConnectionId,
        bytes: i64,
    },
    /// The last fact for this connection; its id is Stale from now on.
    Closed {
        connection: ConnectionId,
        initiator: CloseInitiator,
        code: i64,
        reason: String,
        clean: bool,
    },
}

pub fn decode_connection_id(value: &Value, path: &str) -> Result<ConnectionId, DecodeError> {
    wire::string(value, path).map(ConnectionId)
}

pub fn decode_connection_stale_reason(value: &Value, path: &str) -> Result<ConnectionStaleReason, DecodeError> {
    wire::enumeration(value, path, &[("unknown", ConnectionStaleReason::Unknown), ("disposed", ConnectionStaleReason::Disposed), ("other-session", ConnectionStaleReason::OtherSession)])
}

pub fn decode_ready_state(value: &Value, path: &str) -> Result<ReadyState, DecodeError> {
    wire::enumeration(value, path, &[("connecting", ReadyState::Connecting), ("open", ReadyState::Open), ("closing", ReadyState::Closing), ("closed", ReadyState::Closed)])
}

pub fn decode_close_initiator(value: &Value, path: &str) -> Result<CloseInitiator, DecodeError> {
    wire::enumeration(value, path, &[("remote", CloseInitiator::Remote), ("error", CloseInitiator::Error)])
}

pub fn decode_realtime_request(value: &Value, path: &str) -> Result<RealtimeRequest, DecodeError> {
    match wire::tag(value, path, "operation")?.as_str() {
        "openWebSocket" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation", "url", "protocols"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "openWebSocket"))?;
            let f_url = wire::required(props, path, "url", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            let f_protocols = wire::required(props, path, "protocols", |v0: &Value, p0: &str| wire::list(v0, p0, |v1: &Value, p1: &str| wire::string(v1, p1)))?;
            Ok(RealtimeRequest::OpenWebSocket { url: f_url, protocols: f_protocols })
        }
        "openEventSource" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation", "url", "withCredentials", "events"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "openEventSource"))?;
            let f_url = wire::required(props, path, "url", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            let f_with_credentials = wire::required(props, path, "withCredentials", |v0: &Value, p0: &str| wire::boolean(v0, p0))?;
            let f_events = wire::required(props, path, "events", |v0: &Value, p0: &str| wire::list(v0, p0, |v1: &Value, p1: &str| wire::string(v1, p1)))?;
            Ok(RealtimeRequest::OpenEventSource { url: f_url, with_credentials: f_with_credentials, events: f_events })
        }
        "send" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation", "connection", "text"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "send"))?;
            let f_connection = wire::required(props, path, "connection", |v0: &Value, p0: &str| decode_connection_id(v0, p0))?;
            let f_text = wire::required(props, path, "text", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            Ok(RealtimeRequest::Send { connection: f_connection, text: f_text })
        }
        "close" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation", "connection", "code", "reason"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "close"))?;
            let f_connection = wire::required(props, path, "connection", |v0: &Value, p0: &str| decode_connection_id(v0, p0))?;
            let f_code = wire::optional(props, path, "code", |v0: &Value, p0: &str| wire::int(v0, p0))?;
            let f_reason = wire::optional(props, path, "reason", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            Ok(RealtimeRequest::Close { connection: f_connection, code: f_code, reason: f_reason })
        }
        other => Err(wire::unknown_variant(&format!("{}.operation", path), other)),
    }
}

pub fn decode_realtime_result(value: &Value, path: &str) -> Result<RealtimeResult, DecodeError> {
    match wire::tag(value, path, "kind")?.as_str() {
        "Connecting" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "connection"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Connecting"))?;
            let f_connection = wire::required(props, path, "connection", |v0: &Value, p0: &str| decode_connection_id(v0, p0))?;
            Ok(RealtimeResult::Connecting { connection: f_connection })
        }
        "Sent" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "bufferedAmount"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Sent"))?;
            let f_buffered_amount = wire::required(props, path, "bufferedAmount", |v0: &Value, p0: &str| wire::int(v0, p0))?;
            Ok(RealtimeResult::Sent { buffered_amount: f_buffered_amount })
        }
        "Closed" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Closed"))?;
            Ok(RealtimeResult::Closed)
        }
        "NotOpen" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "state"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "NotOpen"))?;
            let f_state = wire::required(props, path, "state", |v0: &Value, p0: &str| decode_ready_state(v0, p0))?;
            Ok(RealtimeResult::NotOpen { state: f_state })
        }
        "NotSendable" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "NotSendable"))?;
            Ok(RealtimeResult::NotSendable)
        }
        "Stale" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "reason"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Stale"))?;
            let f_reason = wire::required(props, path, "reason", |v0: &Value, p0: &str| decode_connection_stale_reason(v0, p0))?;
            Ok(RealtimeResult::Stale { reason: f_reason })
        }
        "InvalidUrl" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "scheme"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "InvalidUrl"))?;
            let f_scheme = wire::required(props, path, "scheme", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            Ok(RealtimeResult::InvalidUrl { scheme: f_scheme })
        }
        "InvalidCloseCode" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "InvalidCloseCode"))?;
            Ok(RealtimeResult::InvalidCloseCode)
        }
        "Refused" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "reason"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Refused"))?;
            let f_reason = wire::required(props, path, "reason", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            Ok(RealtimeResult::Refused { reason: f_reason })
        }
        "Unsupported" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Unsupported"))?;
            Ok(RealtimeResult::Unsupported)
        }
        "Cancelled" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Cancelled"))?;
            Ok(RealtimeResult::Cancelled)
        }
        other => Err(wire::unknown_variant(&format!("{}.kind", path), other)),
    }
}

pub fn decode_realtime_fact(value: &Value, path: &str) -> Result<RealtimeFact, DecodeError> {
    match wire::tag(value, path, "kind")?.as_str() {
        "Opened" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "connection", "protocol"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Opened"))?;
            let f_connection = wire::required(props, path, "connection", |v0: &Value, p0: &str| decode_connection_id(v0, p0))?;
            let f_protocol = wire::required(props, path, "protocol", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            Ok(RealtimeFact::Opened { connection: f_connection, protocol: f_protocol })
        }
        "Message" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "connection", "data", "event", "lastEventId"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Message"))?;
            let f_connection = wire::required(props, path, "connection", |v0: &Value, p0: &str| decode_connection_id(v0, p0))?;
            let f_data = wire::required(props, path, "data", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            let f_event = wire::optional(props, path, "event", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            let f_last_event_id = wire::optional(props, path, "lastEventId", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            Ok(RealtimeFact::Message { connection: f_connection, data: f_data, event: f_event, last_event_id: f_last_event_id })
        }
        "BinaryMessage" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "connection", "bytes"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "BinaryMessage"))?;
            let f_connection = wire::required(props, path, "connection", |v0: &Value, p0: &str| decode_connection_id(v0, p0))?;
            let f_bytes = wire::required(props, path, "bytes", |v0: &Value, p0: &str| wire::int(v0, p0))?;
            Ok(RealtimeFact::BinaryMessage { connection: f_connection, bytes: f_bytes })
        }
        "Closed" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "connection", "initiator", "code", "reason", "clean"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Closed"))?;
            let f_connection = wire::required(props, path, "connection", |v0: &Value, p0: &str| decode_connection_id(v0, p0))?;
            let f_initiator = wire::required(props, path, "initiator", |v0: &Value, p0: &str| decode_close_initiator(v0, p0))?;
            let f_code = wire::required(props, path, "code", |v0: &Value, p0: &str| wire::int(v0, p0))?;
            let f_reason = wire::required(props, path, "reason", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            let f_clean = wire::required(props, path, "clean", |v0: &Value, p0: &str| wire::boolean(v0, p0))?;
            Ok(RealtimeFact::Closed { connection: f_connection, initiator: f_initiator, code: f_code, reason: f_reason, clean: f_clean })
        }
        other => Err(wire::unknown_variant(&format!("{}.kind", path), other)),
    }
}

pub fn encode_connection_id(value: &ConnectionId) -> Value {
    wire::of_string(&value.0)
}

pub fn encode_connection_stale_reason(value: &ConnectionStaleReason) -> Value {
    match value {
        ConnectionStaleReason::Unknown => wire::of_string("unknown"),
        ConnectionStaleReason::Disposed => wire::of_string("disposed"),
        ConnectionStaleReason::OtherSession => wire::of_string("other-session"),
    }
}

pub fn encode_ready_state(value: &ReadyState) -> Value {
    match value {
        ReadyState::Connecting => wire::of_string("connecting"),
        ReadyState::Open => wire::of_string("open"),
        ReadyState::Closing => wire::of_string("closing"),
        ReadyState::Closed => wire::of_string("closed"),
    }
}

pub fn encode_close_initiator(value: &CloseInitiator) -> Value {
    match value {
        CloseInitiator::Remote => wire::of_string("remote"),
        CloseInitiator::Error => wire::of_string("error"),
    }
}

pub fn encode_realtime_request(value: &RealtimeRequest) -> Value {
    match value {
        RealtimeRequest::OpenWebSocket { url: f_url, protocols: f_protocols } => wire::of_object(vec![Some(("operation", wire::of_string("openWebSocket"))), Some(("url", wire::of_string(f_url))), Some(("protocols", wire::of_list(f_protocols, |x0| wire::of_string(x0))))]),
        RealtimeRequest::OpenEventSource { url: f_url, with_credentials: f_with_credentials, events: f_events } => wire::of_object(vec![Some(("operation", wire::of_string("openEventSource"))), Some(("url", wire::of_string(f_url))), Some(("withCredentials", wire::of_bool(*f_with_credentials))), Some(("events", wire::of_list(f_events, |x0| wire::of_string(x0))))]),
        RealtimeRequest::Send { connection: f_connection, text: f_text } => wire::of_object(vec![Some(("operation", wire::of_string("send"))), Some(("connection", encode_connection_id(f_connection))), Some(("text", wire::of_string(f_text)))]),
        RealtimeRequest::Close { connection: f_connection, code: f_code, reason: f_reason } => wire::of_object(vec![Some(("operation", wire::of_string("close"))), Some(("connection", encode_connection_id(f_connection))), (f_code).as_ref().map(|x0| ("code", wire::of_int(*x0))), (f_reason).as_ref().map(|x0| ("reason", wire::of_string(x0)))]),
    }
}

pub fn encode_realtime_result(value: &RealtimeResult) -> Value {
    match value {
        RealtimeResult::Connecting { connection: f_connection } => wire::of_object(vec![Some(("kind", wire::of_string("Connecting"))), Some(("connection", encode_connection_id(f_connection)))]),
        RealtimeResult::Sent { buffered_amount: f_buffered_amount } => wire::of_object(vec![Some(("kind", wire::of_string("Sent"))), Some(("bufferedAmount", wire::of_int(*f_buffered_amount)))]),
        RealtimeResult::Closed => wire::of_object(vec![Some(("kind", wire::of_string("Closed")))]),
        RealtimeResult::NotOpen { state: f_state } => wire::of_object(vec![Some(("kind", wire::of_string("NotOpen"))), Some(("state", encode_ready_state(f_state)))]),
        RealtimeResult::NotSendable => wire::of_object(vec![Some(("kind", wire::of_string("NotSendable")))]),
        RealtimeResult::Stale { reason: f_reason } => wire::of_object(vec![Some(("kind", wire::of_string("Stale"))), Some(("reason", encode_connection_stale_reason(f_reason)))]),
        RealtimeResult::InvalidUrl { scheme: f_scheme } => wire::of_object(vec![Some(("kind", wire::of_string("InvalidUrl"))), Some(("scheme", wire::of_string(f_scheme)))]),
        RealtimeResult::InvalidCloseCode => wire::of_object(vec![Some(("kind", wire::of_string("InvalidCloseCode")))]),
        RealtimeResult::Refused { reason: f_reason } => wire::of_object(vec![Some(("kind", wire::of_string("Refused"))), Some(("reason", wire::of_string(f_reason)))]),
        RealtimeResult::Unsupported => wire::of_object(vec![Some(("kind", wire::of_string("Unsupported")))]),
        RealtimeResult::Cancelled => wire::of_object(vec![Some(("kind", wire::of_string("Cancelled")))]),
    }
}

pub fn encode_realtime_fact(value: &RealtimeFact) -> Value {
    match value {
        RealtimeFact::Opened { connection: f_connection, protocol: f_protocol } => wire::of_object(vec![Some(("kind", wire::of_string("Opened"))), Some(("connection", encode_connection_id(f_connection))), Some(("protocol", wire::of_string(f_protocol)))]),
        RealtimeFact::Message { connection: f_connection, data: f_data, event: f_event, last_event_id: f_last_event_id } => wire::of_object(vec![Some(("kind", wire::of_string("Message"))), Some(("connection", encode_connection_id(f_connection))), Some(("data", wire::of_string(f_data))), (f_event).as_ref().map(|x0| ("event", wire::of_string(x0))), (f_last_event_id).as_ref().map(|x0| ("lastEventId", wire::of_string(x0)))]),
        RealtimeFact::BinaryMessage { connection: f_connection, bytes: f_bytes } => wire::of_object(vec![Some(("kind", wire::of_string("BinaryMessage"))), Some(("connection", encode_connection_id(f_connection))), Some(("bytes", wire::of_int(*f_bytes)))]),
        RealtimeFact::Closed { connection: f_connection, initiator: f_initiator, code: f_code, reason: f_reason, clean: f_clean } => wire::of_object(vec![Some(("kind", wire::of_string("Closed"))), Some(("connection", encode_connection_id(f_connection))), Some(("initiator", encode_close_initiator(f_initiator))), Some(("code", wire::of_int(*f_code))), Some(("reason", wire::of_string(f_reason))), Some(("clean", wire::of_bool(*f_clean)))]),
    }
}

/// Parses untrusted JSON text into a ConnectionId, or says where and why it is not one.
pub fn parse_connection_id(json: &str) -> Result<ConnectionId, DecodeError> {
    wire::parse(json, decode_connection_id)
}

/// Serializes a ConnectionId to wire JSON text.
pub fn serialize_connection_id(value: &ConnectionId) -> String {
    encode_connection_id(value).to_string()
}

/// Parses untrusted JSON text into a ConnectionStaleReason, or says where and why it is not one.
pub fn parse_connection_stale_reason(json: &str) -> Result<ConnectionStaleReason, DecodeError> {
    wire::parse(json, decode_connection_stale_reason)
}

/// Serializes a ConnectionStaleReason to wire JSON text.
pub fn serialize_connection_stale_reason(value: &ConnectionStaleReason) -> String {
    encode_connection_stale_reason(value).to_string()
}

/// Parses untrusted JSON text into a ReadyState, or says where and why it is not one.
pub fn parse_ready_state(json: &str) -> Result<ReadyState, DecodeError> {
    wire::parse(json, decode_ready_state)
}

/// Serializes a ReadyState to wire JSON text.
pub fn serialize_ready_state(value: &ReadyState) -> String {
    encode_ready_state(value).to_string()
}

/// Parses untrusted JSON text into a CloseInitiator, or says where and why it is not one.
pub fn parse_close_initiator(json: &str) -> Result<CloseInitiator, DecodeError> {
    wire::parse(json, decode_close_initiator)
}

/// Serializes a CloseInitiator to wire JSON text.
pub fn serialize_close_initiator(value: &CloseInitiator) -> String {
    encode_close_initiator(value).to_string()
}

/// Parses untrusted JSON text into a RealtimeRequest, or says where and why it is not one.
pub fn parse_realtime_request(json: &str) -> Result<RealtimeRequest, DecodeError> {
    wire::parse(json, decode_realtime_request)
}

/// Serializes a RealtimeRequest to wire JSON text.
pub fn serialize_realtime_request(value: &RealtimeRequest) -> String {
    encode_realtime_request(value).to_string()
}

/// Parses untrusted JSON text into a RealtimeResult, or says where and why it is not one.
pub fn parse_realtime_result(json: &str) -> Result<RealtimeResult, DecodeError> {
    wire::parse(json, decode_realtime_result)
}

/// Serializes a RealtimeResult to wire JSON text.
pub fn serialize_realtime_result(value: &RealtimeResult) -> String {
    encode_realtime_result(value).to_string()
}

/// Parses untrusted JSON text into a RealtimeFact, or says where and why it is not one.
pub fn parse_realtime_fact(json: &str) -> Result<RealtimeFact, DecodeError> {
    wire::parse(json, decode_realtime_fact)
}

/// Serializes a RealtimeFact to wire JSON text.
pub fn serialize_realtime_fact(value: &RealtimeFact) -> String {
    encode_realtime_fact(value).to_string()
}

/// Decode-then-encode by type name. Used only by the shared conformance runner.
pub fn conformance_round_trip(type_name: &str, value: &Value) -> Option<Result<Value, DecodeError>> {
    match type_name {
        "ConnectionId" => Some(decode_connection_id(value, "$").map(|decoded| encode_connection_id(&decoded))),
        "ConnectionStaleReason" => Some(decode_connection_stale_reason(value, "$").map(|decoded| encode_connection_stale_reason(&decoded))),
        "ReadyState" => Some(decode_ready_state(value, "$").map(|decoded| encode_ready_state(&decoded))),
        "CloseInitiator" => Some(decode_close_initiator(value, "$").map(|decoded| encode_close_initiator(&decoded))),
        "RealtimeRequest" => Some(decode_realtime_request(value, "$").map(|decoded| encode_realtime_request(&decoded))),
        "RealtimeResult" => Some(decode_realtime_result(value, "$").map(|decoded| encode_realtime_result(&decoded))),
        "RealtimeFact" => Some(decode_realtime_fact(value, "$").map(|decoded| encode_realtime_fact(&decoded))),
        _ => None,
    }
}
