// <auto-generated by limen-contract-gen>
// GENERATED FILE — DO NOT EDIT. Change the contract and run `npm run contract:generate`.
// source: contract/core.contract.json
// unit: limen.core@1
// contract-fingerprint: sha256:4b1dc4e720c9a7a24e45e916ed29dcfff6bf329e5eb0e0415dd45897de2019dd
// generator: limen-contract-gen/1 (rust-unit)
// content-hash: sha256:48c9ac02d34729da3803b205235d7bba62042cb6b05c795a06b113fa1b426264
// </auto-generated>
//! The Limen browser/engine wire contract. Plain JSON-serializable data only. This file is the single source of truth: every language binding is generated from it by tools/contract-gen and must never be edited by hand.

use std::collections::BTreeMap;

use serde_json::Value;

use crate::runtime::{wire, DecodeError, RawJson};

/// The identity of this generated contract unit, exchanged in the handshake.
pub mod contract {
    pub const UNIT: &str = "limen.core";
    pub const VERSION: i64 = 1;
    pub const FINGERPRINT: &str = "sha256:4b1dc4e720c9a7a24e45e916ed29dcfff6bf329e5eb0e0415dd45897de2019dd";
    pub const PROTOCOL_VERSION: i64 = 1;
    pub const PROTOCOL_MINOR: i64 = 1;
}

/// Identifies one requested effect so its result can be matched to the question it answers, and a stale answer rejected.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct CorrelationId(pub String);

/// What the kernel implements, announced once in Initialize. Not a statement about what this browser will permit at the moment an effect runs: permission and availability are reported per effect, in that effect's own outcome.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Capability {
    Http,
    Storage,
    Clipboard,
    Navigation,
}

impl Capability {
    /// The wire text of this value.
    pub fn as_wire(&self) -> &'static str {
        match self {
            Capability::Http => "Http",
            Capability::Storage => "Storage",
            Capability::Clipboard => "Clipboard",
            Capability::Navigation => "Navigation",
        }
    }
}

/// `name` is a domain-chosen identifier (the value of a data-event attribute). The bridge does not know its meaning; only the engine interprets it.
#[derive(Debug, Clone, PartialEq)]
pub struct SemanticEvent {
    pub name: String,
    pub key: Option<String>,
    pub value: Option<String>,
}

/// The browser's current URL, split mechanically by the kernel. Deciding what a path means is application meaning, so the kernel never parses further than this.
#[derive(Debug, Clone, PartialEq)]
pub struct BrowserLocation {
    /// Scheme, host and port, no trailing slash.
    pub origin: String,
    /// Always begins with /.
    pub path: String,
    /// Leading ? included, or empty.
    pub query: String,
    /// Leading # included, or empty.
    pub hash: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum HttpFailureReason {
    Network,
    Aborted,
    InvalidResponse,
}

impl HttpFailureReason {
    /// The wire text of this value.
    pub fn as_wire(&self) -> &'static str {
        match self {
            HttpFailureReason::Network => "network",
            HttpFailureReason::Aborted => "aborted",
            HttpFailureReason::InvalidResponse => "invalid-response",
        }
    }
}

/// The outcome of an Http effect. OutcomeUnknown exists because a timed-out request may already have reached the server; it must never be collapsed into Failure.
#[derive(Debug, Clone, PartialEq)]
pub enum EffectOutcome {
    Success {
        status: i64,
        /// The decoded response body. The engine narrows it with its own typed decoder.
        body: RawJson,
    },
    Failure {
        reason: HttpFailureReason,
        /// Present exactly when a response was received (invalid-response).
        status: Option<i64>,
    },
    Cancelled,
    OutcomeUnknown,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum StorageFailureReason {
    Unavailable,
    QuotaExceeded,
}

impl StorageFailureReason {
    /// The wire text of this value.
    pub fn as_wire(&self) -> &'static str {
        match self {
            StorageFailureReason::Unavailable => "unavailable",
            StorageFailureReason::QuotaExceeded => "quota-exceeded",
        }
    }
}

/// A single localStorage call is atomic, so there is no dispatched-but-uncertain case. Success.value is null when a key was absent or the operation was set/remove.
#[derive(Debug, Clone, PartialEq)]
pub enum StorageOutcome {
    Success {
        value: Option<String>,
    },
    Failure {
        reason: StorageFailureReason,
    },
}

/// denied is usually recoverable by another user gesture; unavailable never is in this browser.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ClipboardFailureReason {
    Denied,
    Unavailable,
    Unknown,
}

impl ClipboardFailureReason {
    /// The wire text of this value.
    pub fn as_wire(&self) -> &'static str {
        match self {
            ClipboardFailureReason::Denied => "denied",
            ClipboardFailureReason::Unavailable => "unavailable",
            ClipboardFailureReason::Unknown => "unknown",
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub enum ClipboardOutcome {
    Success,
    Failure {
        reason: ClipboardFailureReason,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum NavigationFailureReason {
    Unavailable,
    NotSameOrigin,
}

impl NavigationFailureReason {
    /// The wire text of this value.
    pub fn as_wire(&self) -> &'static str {
        match self {
            NavigationFailureReason::Unavailable => "unavailable",
            NavigationFailureReason::NotSameOrigin => "not-same-origin",
        }
    }
}

/// Dispatched is not a weaker Success: back/forward only ask the browser to move, and the move arrives later as LocationChanged, or never.
#[derive(Debug, Clone, PartialEq)]
pub enum NavigationOutcome {
    Success {
        location: BrowserLocation,
    },
    Dispatched,
    Failure {
        reason: NavigationFailureReason,
    },
}

/// The identity of an optional capability pack, e.g. limen.focus. Chosen by the pack's own contract unit; Core never interprets it beyond equality.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct CapabilityId(pub String);

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum CapabilityUnsupportedReason {
    NotNegotiated,
    VersionUnsupported,
}

impl CapabilityUnsupportedReason {
    /// The wire text of this value.
    pub fn as_wire(&self) -> &'static str {
        match self {
            CapabilityUnsupportedReason::NotNegotiated => "not-negotiated",
            CapabilityUnsupportedReason::VersionUnsupported => "version-unsupported",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum CapabilityRejectedReason {
    MalformedRequest,
}

impl CapabilityRejectedReason {
    /// The wire text of this value.
    pub fn as_wire(&self) -> &'static str {
        match self {
            CapabilityRejectedReason::MalformedRequest => "malformed-request",
        }
    }
}

/// How Core answers a capability effect. Completed carries the capability's own closed outcome, which is where its success, failure, cancellation and unknown variants live. Unsupported and Rejected are compatibility facts, never effect outcomes: they mean the request was not executed.
#[derive(Debug, Clone, PartialEq)]
pub enum CapabilityOutcome {
    Completed {
        /// Encoded by the capability's generated binding; decoded by the engine with the same.
        result: RawJson,
    },
    Unsupported {
        reason: CapabilityUnsupportedReason,
    },
    Rejected {
        reason: CapabilityRejectedReason,
    },
}

#[derive(Debug, Clone, PartialEq)]
pub enum EffectResult {
    HttpResult {
        correlation_id: CorrelationId,
        outcome: EffectOutcome,
    },
    StorageResult {
        correlation_id: CorrelationId,
        outcome: StorageOutcome,
    },
    ClipboardResult {
        correlation_id: CorrelationId,
        outcome: ClipboardOutcome,
    },
    NavigationResult {
        correlation_id: CorrelationId,
        outcome: NavigationOutcome,
    },
    CapabilityResult {
        correlation_id: CorrelationId,
        capability: CapabilityId,
        version: i64,
        outcome: CapabilityOutcome,
    },
}

#[derive(Debug, Clone, PartialEq)]
pub struct ProtocolRevision {
    pub major: i64,
    pub minor: i64,
}

/// Identifies one generated contract unit. The fingerprint is SHA-256 over the unit's canonical JSON with documentation removed.
#[derive(Debug, Clone, PartialEq)]
pub struct ContractIdentity {
    pub unit: String,
    pub version: i64,
    pub fingerprint: String,
}

/// An optional capability the host implements. An offer is not permission.
#[derive(Debug, Clone, PartialEq)]
pub struct CapabilityOffer {
    pub id: CapabilityId,
    pub version: i64,
    pub fingerprint: String,
}

#[derive(Debug, Clone, PartialEq)]
pub struct HostHandshake {
    pub protocol: ProtocolRevision,
    pub contract: ContractIdentity,
    pub capabilities: Vec<CapabilityOffer>,
}

/// Why an engine refused the host. Protocol incompatibility is a compatibility state, never an effect OutcomeUnknown.
#[derive(Debug, Clone, PartialEq)]
pub enum HandshakeRejection {
    ProtocolUnsupported {
        offered: ProtocolRevision,
    },
    ContractMismatch {
        expected: ContractIdentity,
        offered: ContractIdentity,
    },
    CapabilityUnavailable {
        id: CapabilityId,
        version: i64,
    },
    HandshakeMissing,
}

#[derive(Debug, Clone, PartialEq)]
pub enum EngineHandshake {
    Accepted {
        protocol: ProtocolRevision,
        contract: ContractIdentity,
        /// The capabilities this engine will use. Every one must have been offered with the same version and fingerprint.
        capabilities: Vec<CapabilityOffer>,
    },
    Rejected {
        reason: HandshakeRejection,
    },
}

#[derive(Debug, Clone, PartialEq)]
pub enum BrowserToEngineMessage {
    /// Delivered once at startup. handshake is absent only from kernels older than protocol 1.1.
    Initialize {
        capabilities: Vec<Capability>,
        location: BrowserLocation,
        handshake: Option<HostHandshake>,
    },
    Event {
        event: SemanticEvent,
    },
    EffectResult {
        result: EffectResult,
    },
    /// The browser moved through history on its own. Adopt it; never answer it with another navigation.
    LocationChanged {
        location: BrowserLocation,
    },
    /// A browser-originated fact from a negotiated capability (a subscription update, a lifecycle change). Not correlated with a result.
    CapabilityFact {
        capability: CapabilityId,
        version: i64,
        /// Encoded by the capability's generated binding.
        fact: RawJson,
    },
}

#[derive(Debug, Clone, PartialEq)]
pub enum ViewPrimitive {
    Text(String),
    Number(f64),
    Flag(bool),
}

pub type ViewItem = BTreeMap<String, ViewPrimitive>;

#[derive(Debug, Clone, PartialEq)]
pub enum ViewValue {
    Text(String),
    Number(f64),
    Flag(bool),
    Items(Vec<ViewItem>),
}

/// A projection, not the engine's internal state: named values a view binds to and named lists it repeats.
pub type ViewState = BTreeMap<String, ViewValue>;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum HttpMethod {
    Get,
    Put,
    Post,
    Patch,
    Delete,
}

impl HttpMethod {
    /// The wire text of this value.
    pub fn as_wire(&self) -> &'static str {
        match self {
            HttpMethod::Get => "GET",
            HttpMethod::Put => "PUT",
            HttpMethod::Post => "POST",
            HttpMethod::Patch => "PATCH",
            HttpMethod::Delete => "DELETE",
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct HttpEffectRequest {
    pub correlation_id: CorrelationId,
    pub method: HttpMethod,
    pub url: String,
    /// Never surfaced in diagnostics: headers commonly carry credentials.
    pub headers: Option<BTreeMap<String, String>>,
    /// Pre-serialized by the engine; the kernel never interprets it.
    pub body: Option<String>,
    pub timeout_ms: i64,
}

#[derive(Debug, Clone, PartialEq)]
pub enum StorageEffectRequest {
    Get {
        correlation_id: CorrelationId,
        key: String,
    },
    Set {
        correlation_id: CorrelationId,
        key: String,
        value: String,
    },
    Remove {
        correlation_id: CorrelationId,
        key: String,
    },
}

/// Write-only by design (LCP-019 intentional non-parity). text is never surfaced in diagnostics.
#[derive(Debug, Clone, PartialEq)]
pub struct ClipboardEffectRequest {
    pub correlation_id: CorrelationId,
    pub text: String,
}

/// url is same-origin and root-relative; the kernel refuses anything else.
#[derive(Debug, Clone, PartialEq)]
pub enum NavigationEffectRequest {
    Push {
        correlation_id: CorrelationId,
        url: String,
    },
    Replace {
        correlation_id: CorrelationId,
        url: String,
    },
    Back {
        correlation_id: CorrelationId,
    },
    Forward {
        correlation_id: CorrelationId,
    },
}

/// A request to a negotiated optional capability. request is encoded by that capability's generated binding; Core routes it by capability and never interprets it.
#[derive(Debug, Clone, PartialEq)]
pub struct CapabilityEffectRequest {
    pub correlation_id: CorrelationId,
    pub capability: CapabilityId,
    pub version: i64,
    pub request: RawJson,
}

#[derive(Debug, Clone, PartialEq)]
pub enum EffectRequest {
    Http(HttpEffectRequest),
    Storage(StorageEffectRequest),
    Clipboard(ClipboardEffectRequest),
    Navigation(NavigationEffectRequest),
    Capability(CapabilityEffectRequest),
}

#[derive(Debug, Clone, PartialEq)]
pub struct EngineToBrowserMessage {
    pub view: ViewState,
    pub effects: Vec<EffectRequest>,
    /// Previously requested effects whose result is no longer wanted. Only the engine decides this.
    pub cancellations: Vec<CorrelationId>,
    /// Only meaningful on the response to Initialize.
    pub handshake: Option<EngineHandshake>,
}

pub fn decode_correlation_id(value: &Value, path: &str) -> Result<CorrelationId, DecodeError> {
    wire::string(value, path).map(CorrelationId)
}

pub fn decode_capability(value: &Value, path: &str) -> Result<Capability, DecodeError> {
    wire::enumeration(value, path, &[("Http", Capability::Http), ("Storage", Capability::Storage), ("Clipboard", Capability::Clipboard), ("Navigation", Capability::Navigation)])
}

pub fn decode_semantic_event(value: &Value, path: &str) -> Result<SemanticEvent, DecodeError> {
    let props = wire::closed(wire::properties(value, path)?, path, &["kind", "name", "key", "value"])?;
    wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Event"))?;
    let f_name = wire::required(props, path, "name", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    let f_key = wire::optional(props, path, "key", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    let f_value = wire::optional(props, path, "value", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    Ok(SemanticEvent { name: f_name, key: f_key, value: f_value })
}

pub fn decode_browser_location(value: &Value, path: &str) -> Result<BrowserLocation, DecodeError> {
    let props = wire::closed(wire::properties(value, path)?, path, &["origin", "path", "query", "hash"])?;
    let f_origin = wire::required(props, path, "origin", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    let f_path = wire::required(props, path, "path", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    let f_query = wire::required(props, path, "query", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    let f_hash = wire::required(props, path, "hash", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    Ok(BrowserLocation { origin: f_origin, path: f_path, query: f_query, hash: f_hash })
}

pub fn decode_http_failure_reason(value: &Value, path: &str) -> Result<HttpFailureReason, DecodeError> {
    wire::enumeration(value, path, &[("network", HttpFailureReason::Network), ("aborted", HttpFailureReason::Aborted), ("invalid-response", HttpFailureReason::InvalidResponse)])
}

pub fn decode_effect_outcome(value: &Value, path: &str) -> Result<EffectOutcome, DecodeError> {
    match wire::tag(value, path, "kind")?.as_str() {
        "Success" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "status", "body"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Success"))?;
            let f_status = wire::required(props, path, "status", |v0: &Value, p0: &str| wire::int(v0, p0))?;
            let f_body = wire::required(props, path, "body", |v0: &Value, p0: &str| wire::json(v0, p0))?;
            Ok(EffectOutcome::Success { status: f_status, body: f_body })
        }
        "Failure" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "reason", "status"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Failure"))?;
            let f_reason = wire::required(props, path, "reason", |v0: &Value, p0: &str| decode_http_failure_reason(v0, p0))?;
            let f_status = wire::optional(props, path, "status", |v0: &Value, p0: &str| wire::int(v0, p0))?;
            Ok(EffectOutcome::Failure { reason: f_reason, status: f_status })
        }
        "Cancelled" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Cancelled"))?;
            Ok(EffectOutcome::Cancelled)
        }
        "OutcomeUnknown" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "reason"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "OutcomeUnknown"))?;
            wire::required(props, path, "reason", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "timeout-after-dispatch"))?;
            Ok(EffectOutcome::OutcomeUnknown)
        }
        other => Err(wire::unknown_variant(&format!("{}.kind", path), other)),
    }
}

pub fn decode_storage_failure_reason(value: &Value, path: &str) -> Result<StorageFailureReason, DecodeError> {
    wire::enumeration(value, path, &[("unavailable", StorageFailureReason::Unavailable), ("quota-exceeded", StorageFailureReason::QuotaExceeded)])
}

pub fn decode_storage_outcome(value: &Value, path: &str) -> Result<StorageOutcome, DecodeError> {
    match wire::tag(value, path, "kind")?.as_str() {
        "Success" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "value"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Success"))?;
            let f_value = wire::required(props, path, "value", |v0: &Value, p0: &str| wire::nullable(v0, p0, |v1: &Value, p1: &str| wire::string(v1, p1)))?;
            Ok(StorageOutcome::Success { value: f_value })
        }
        "Failure" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "reason"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Failure"))?;
            let f_reason = wire::required(props, path, "reason", |v0: &Value, p0: &str| decode_storage_failure_reason(v0, p0))?;
            Ok(StorageOutcome::Failure { reason: f_reason })
        }
        other => Err(wire::unknown_variant(&format!("{}.kind", path), other)),
    }
}

pub fn decode_clipboard_failure_reason(value: &Value, path: &str) -> Result<ClipboardFailureReason, DecodeError> {
    wire::enumeration(value, path, &[("denied", ClipboardFailureReason::Denied), ("unavailable", ClipboardFailureReason::Unavailable), ("unknown", ClipboardFailureReason::Unknown)])
}

pub fn decode_clipboard_outcome(value: &Value, path: &str) -> Result<ClipboardOutcome, DecodeError> {
    match wire::tag(value, path, "kind")?.as_str() {
        "Success" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Success"))?;
            Ok(ClipboardOutcome::Success)
        }
        "Failure" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "reason"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Failure"))?;
            let f_reason = wire::required(props, path, "reason", |v0: &Value, p0: &str| decode_clipboard_failure_reason(v0, p0))?;
            Ok(ClipboardOutcome::Failure { reason: f_reason })
        }
        other => Err(wire::unknown_variant(&format!("{}.kind", path), other)),
    }
}

pub fn decode_navigation_failure_reason(value: &Value, path: &str) -> Result<NavigationFailureReason, DecodeError> {
    wire::enumeration(value, path, &[("unavailable", NavigationFailureReason::Unavailable), ("not-same-origin", NavigationFailureReason::NotSameOrigin)])
}

pub fn decode_navigation_outcome(value: &Value, path: &str) -> Result<NavigationOutcome, DecodeError> {
    match wire::tag(value, path, "kind")?.as_str() {
        "Success" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "location"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Success"))?;
            let f_location = wire::required(props, path, "location", |v0: &Value, p0: &str| decode_browser_location(v0, p0))?;
            Ok(NavigationOutcome::Success { location: f_location })
        }
        "Dispatched" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Dispatched"))?;
            Ok(NavigationOutcome::Dispatched)
        }
        "Failure" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "reason"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Failure"))?;
            let f_reason = wire::required(props, path, "reason", |v0: &Value, p0: &str| decode_navigation_failure_reason(v0, p0))?;
            Ok(NavigationOutcome::Failure { reason: f_reason })
        }
        other => Err(wire::unknown_variant(&format!("{}.kind", path), other)),
    }
}

pub fn decode_capability_id(value: &Value, path: &str) -> Result<CapabilityId, DecodeError> {
    wire::string(value, path).map(CapabilityId)
}

pub fn decode_capability_unsupported_reason(value: &Value, path: &str) -> Result<CapabilityUnsupportedReason, DecodeError> {
    wire::enumeration(value, path, &[("not-negotiated", CapabilityUnsupportedReason::NotNegotiated), ("version-unsupported", CapabilityUnsupportedReason::VersionUnsupported)])
}

pub fn decode_capability_rejected_reason(value: &Value, path: &str) -> Result<CapabilityRejectedReason, DecodeError> {
    wire::enumeration(value, path, &[("malformed-request", CapabilityRejectedReason::MalformedRequest)])
}

pub fn decode_capability_outcome(value: &Value, path: &str) -> Result<CapabilityOutcome, DecodeError> {
    match wire::tag(value, path, "kind")?.as_str() {
        "Completed" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "result"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Completed"))?;
            let f_result = wire::required(props, path, "result", |v0: &Value, p0: &str| wire::json(v0, p0))?;
            Ok(CapabilityOutcome::Completed { result: f_result })
        }
        "Unsupported" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "reason"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Unsupported"))?;
            let f_reason = wire::required(props, path, "reason", |v0: &Value, p0: &str| decode_capability_unsupported_reason(v0, p0))?;
            Ok(CapabilityOutcome::Unsupported { reason: f_reason })
        }
        "Rejected" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "reason"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Rejected"))?;
            let f_reason = wire::required(props, path, "reason", |v0: &Value, p0: &str| decode_capability_rejected_reason(v0, p0))?;
            Ok(CapabilityOutcome::Rejected { reason: f_reason })
        }
        other => Err(wire::unknown_variant(&format!("{}.kind", path), other)),
    }
}

pub fn decode_effect_result(value: &Value, path: &str) -> Result<EffectResult, DecodeError> {
    match wire::tag(value, path, "kind")?.as_str() {
        "HttpResult" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "correlationId", "outcome"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "HttpResult"))?;
            let f_correlation_id = wire::required(props, path, "correlationId", |v0: &Value, p0: &str| decode_correlation_id(v0, p0))?;
            let f_outcome = wire::required(props, path, "outcome", |v0: &Value, p0: &str| decode_effect_outcome(v0, p0))?;
            Ok(EffectResult::HttpResult { correlation_id: f_correlation_id, outcome: f_outcome })
        }
        "StorageResult" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "correlationId", "outcome"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "StorageResult"))?;
            let f_correlation_id = wire::required(props, path, "correlationId", |v0: &Value, p0: &str| decode_correlation_id(v0, p0))?;
            let f_outcome = wire::required(props, path, "outcome", |v0: &Value, p0: &str| decode_storage_outcome(v0, p0))?;
            Ok(EffectResult::StorageResult { correlation_id: f_correlation_id, outcome: f_outcome })
        }
        "ClipboardResult" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "correlationId", "outcome"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "ClipboardResult"))?;
            let f_correlation_id = wire::required(props, path, "correlationId", |v0: &Value, p0: &str| decode_correlation_id(v0, p0))?;
            let f_outcome = wire::required(props, path, "outcome", |v0: &Value, p0: &str| decode_clipboard_outcome(v0, p0))?;
            Ok(EffectResult::ClipboardResult { correlation_id: f_correlation_id, outcome: f_outcome })
        }
        "NavigationResult" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "correlationId", "outcome"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "NavigationResult"))?;
            let f_correlation_id = wire::required(props, path, "correlationId", |v0: &Value, p0: &str| decode_correlation_id(v0, p0))?;
            let f_outcome = wire::required(props, path, "outcome", |v0: &Value, p0: &str| decode_navigation_outcome(v0, p0))?;
            Ok(EffectResult::NavigationResult { correlation_id: f_correlation_id, outcome: f_outcome })
        }
        "CapabilityResult" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "correlationId", "capability", "version", "outcome"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "CapabilityResult"))?;
            let f_correlation_id = wire::required(props, path, "correlationId", |v0: &Value, p0: &str| decode_correlation_id(v0, p0))?;
            let f_capability = wire::required(props, path, "capability", |v0: &Value, p0: &str| decode_capability_id(v0, p0))?;
            let f_version = wire::required(props, path, "version", |v0: &Value, p0: &str| wire::int(v0, p0))?;
            let f_outcome = wire::required(props, path, "outcome", |v0: &Value, p0: &str| decode_capability_outcome(v0, p0))?;
            Ok(EffectResult::CapabilityResult { correlation_id: f_correlation_id, capability: f_capability, version: f_version, outcome: f_outcome })
        }
        other => Err(wire::unknown_variant(&format!("{}.kind", path), other)),
    }
}

pub fn decode_protocol_revision(value: &Value, path: &str) -> Result<ProtocolRevision, DecodeError> {
    let props = wire::closed(wire::properties(value, path)?, path, &["major", "minor"])?;
    let f_major = wire::required(props, path, "major", |v0: &Value, p0: &str| wire::int(v0, p0))?;
    let f_minor = wire::required(props, path, "minor", |v0: &Value, p0: &str| wire::int(v0, p0))?;
    Ok(ProtocolRevision { major: f_major, minor: f_minor })
}

pub fn decode_contract_identity(value: &Value, path: &str) -> Result<ContractIdentity, DecodeError> {
    let props = wire::closed(wire::properties(value, path)?, path, &["unit", "version", "fingerprint"])?;
    let f_unit = wire::required(props, path, "unit", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    let f_version = wire::required(props, path, "version", |v0: &Value, p0: &str| wire::int(v0, p0))?;
    let f_fingerprint = wire::required(props, path, "fingerprint", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    Ok(ContractIdentity { unit: f_unit, version: f_version, fingerprint: f_fingerprint })
}

pub fn decode_capability_offer(value: &Value, path: &str) -> Result<CapabilityOffer, DecodeError> {
    let props = wire::closed(wire::properties(value, path)?, path, &["id", "version", "fingerprint"])?;
    let f_id = wire::required(props, path, "id", |v0: &Value, p0: &str| decode_capability_id(v0, p0))?;
    let f_version = wire::required(props, path, "version", |v0: &Value, p0: &str| wire::int(v0, p0))?;
    let f_fingerprint = wire::required(props, path, "fingerprint", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    Ok(CapabilityOffer { id: f_id, version: f_version, fingerprint: f_fingerprint })
}

pub fn decode_host_handshake(value: &Value, path: &str) -> Result<HostHandshake, DecodeError> {
    let props = wire::closed(wire::properties(value, path)?, path, &["protocol", "contract", "capabilities"])?;
    let f_protocol = wire::required(props, path, "protocol", |v0: &Value, p0: &str| decode_protocol_revision(v0, p0))?;
    let f_contract = wire::required(props, path, "contract", |v0: &Value, p0: &str| decode_contract_identity(v0, p0))?;
    let f_capabilities = wire::required(props, path, "capabilities", |v0: &Value, p0: &str| wire::list(v0, p0, |v1: &Value, p1: &str| decode_capability_offer(v1, p1)))?;
    Ok(HostHandshake { protocol: f_protocol, contract: f_contract, capabilities: f_capabilities })
}

pub fn decode_handshake_rejection(value: &Value, path: &str) -> Result<HandshakeRejection, DecodeError> {
    match wire::tag(value, path, "kind")?.as_str() {
        "ProtocolUnsupported" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "offered"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "ProtocolUnsupported"))?;
            let f_offered = wire::required(props, path, "offered", |v0: &Value, p0: &str| decode_protocol_revision(v0, p0))?;
            Ok(HandshakeRejection::ProtocolUnsupported { offered: f_offered })
        }
        "ContractMismatch" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "expected", "offered"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "ContractMismatch"))?;
            let f_expected = wire::required(props, path, "expected", |v0: &Value, p0: &str| decode_contract_identity(v0, p0))?;
            let f_offered = wire::required(props, path, "offered", |v0: &Value, p0: &str| decode_contract_identity(v0, p0))?;
            Ok(HandshakeRejection::ContractMismatch { expected: f_expected, offered: f_offered })
        }
        "CapabilityUnavailable" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "id", "version"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "CapabilityUnavailable"))?;
            let f_id = wire::required(props, path, "id", |v0: &Value, p0: &str| decode_capability_id(v0, p0))?;
            let f_version = wire::required(props, path, "version", |v0: &Value, p0: &str| wire::int(v0, p0))?;
            Ok(HandshakeRejection::CapabilityUnavailable { id: f_id, version: f_version })
        }
        "HandshakeMissing" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "HandshakeMissing"))?;
            Ok(HandshakeRejection::HandshakeMissing)
        }
        other => Err(wire::unknown_variant(&format!("{}.kind", path), other)),
    }
}

pub fn decode_engine_handshake(value: &Value, path: &str) -> Result<EngineHandshake, DecodeError> {
    match wire::tag(value, path, "kind")?.as_str() {
        "Accepted" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "protocol", "contract", "capabilities"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Accepted"))?;
            let f_protocol = wire::required(props, path, "protocol", |v0: &Value, p0: &str| decode_protocol_revision(v0, p0))?;
            let f_contract = wire::required(props, path, "contract", |v0: &Value, p0: &str| decode_contract_identity(v0, p0))?;
            let f_capabilities = wire::required(props, path, "capabilities", |v0: &Value, p0: &str| wire::list(v0, p0, |v1: &Value, p1: &str| decode_capability_offer(v1, p1)))?;
            Ok(EngineHandshake::Accepted { protocol: f_protocol, contract: f_contract, capabilities: f_capabilities })
        }
        "Rejected" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "reason"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Rejected"))?;
            let f_reason = wire::required(props, path, "reason", |v0: &Value, p0: &str| decode_handshake_rejection(v0, p0))?;
            Ok(EngineHandshake::Rejected { reason: f_reason })
        }
        other => Err(wire::unknown_variant(&format!("{}.kind", path), other)),
    }
}

pub fn decode_browser_to_engine_message(value: &Value, path: &str) -> Result<BrowserToEngineMessage, DecodeError> {
    match wire::tag(value, path, "kind")?.as_str() {
        "Initialize" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "protocolVersion", "capabilities", "location", "handshake"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Initialize"))?;
            wire::required(props, path, "protocolVersion", |v0: &Value, p0: &str| wire::literal_int(v0, p0, 1))?;
            let f_capabilities = wire::required(props, path, "capabilities", |v0: &Value, p0: &str| wire::list(v0, p0, |v1: &Value, p1: &str| decode_capability(v1, p1)))?;
            let f_location = wire::required(props, path, "location", |v0: &Value, p0: &str| decode_browser_location(v0, p0))?;
            let f_handshake = wire::optional(props, path, "handshake", |v0: &Value, p0: &str| decode_host_handshake(v0, p0))?;
            Ok(BrowserToEngineMessage::Initialize { capabilities: f_capabilities, location: f_location, handshake: f_handshake })
        }
        "Event" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "event"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Event"))?;
            let f_event = wire::required(props, path, "event", |v0: &Value, p0: &str| decode_semantic_event(v0, p0))?;
            Ok(BrowserToEngineMessage::Event { event: f_event })
        }
        "EffectResult" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "result"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "EffectResult"))?;
            let f_result = wire::required(props, path, "result", |v0: &Value, p0: &str| decode_effect_result(v0, p0))?;
            Ok(BrowserToEngineMessage::EffectResult { result: f_result })
        }
        "LocationChanged" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "location"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "LocationChanged"))?;
            let f_location = wire::required(props, path, "location", |v0: &Value, p0: &str| decode_browser_location(v0, p0))?;
            Ok(BrowserToEngineMessage::LocationChanged { location: f_location })
        }
        "CapabilityFact" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "capability", "version", "fact"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "CapabilityFact"))?;
            let f_capability = wire::required(props, path, "capability", |v0: &Value, p0: &str| decode_capability_id(v0, p0))?;
            let f_version = wire::required(props, path, "version", |v0: &Value, p0: &str| wire::int(v0, p0))?;
            let f_fact = wire::required(props, path, "fact", |v0: &Value, p0: &str| wire::json(v0, p0))?;
            Ok(BrowserToEngineMessage::CapabilityFact { capability: f_capability, version: f_version, fact: f_fact })
        }
        other => Err(wire::unknown_variant(&format!("{}.kind", path), other)),
    }
}

pub fn decode_view_primitive(value: &Value, path: &str) -> Result<ViewPrimitive, DecodeError> {
    match wire::kind_of(value) {
        "string" => wire::string(value, path).map(ViewPrimitive::Text),
        "number" => wire::number(value, path).map(ViewPrimitive::Number),
        "boolean" => wire::boolean(value, path).map(ViewPrimitive::Flag),
        _ => Err(wire::mismatch("string | number | boolean", path, value)),
    }
}

pub fn decode_view_item(value: &Value, path: &str) -> Result<ViewItem, DecodeError> {
    wire::map(value, path, |v0: &Value, p0: &str| decode_view_primitive(v0, p0))
}

pub fn decode_view_value(value: &Value, path: &str) -> Result<ViewValue, DecodeError> {
    match wire::kind_of(value) {
        "string" => wire::string(value, path).map(ViewValue::Text),
        "number" => wire::number(value, path).map(ViewValue::Number),
        "boolean" => wire::boolean(value, path).map(ViewValue::Flag),
        "array" => wire::list(value, path, |v1: &Value, p1: &str| decode_view_item(v1, p1)).map(ViewValue::Items),
        _ => Err(wire::mismatch("string | number | boolean | array", path, value)),
    }
}

pub fn decode_view_state(value: &Value, path: &str) -> Result<ViewState, DecodeError> {
    wire::map(value, path, |v0: &Value, p0: &str| decode_view_value(v0, p0))
}

pub fn decode_http_method(value: &Value, path: &str) -> Result<HttpMethod, DecodeError> {
    wire::enumeration(value, path, &[("GET", HttpMethod::Get), ("PUT", HttpMethod::Put), ("POST", HttpMethod::Post), ("PATCH", HttpMethod::Patch), ("DELETE", HttpMethod::Delete)])
}

pub fn decode_http_effect_request(value: &Value, path: &str) -> Result<HttpEffectRequest, DecodeError> {
    let props = wire::closed(wire::properties(value, path)?, path, &["kind", "correlationId", "method", "url", "headers", "body", "timeoutMs"])?;
    wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Http"))?;
    let f_correlation_id = wire::required(props, path, "correlationId", |v0: &Value, p0: &str| decode_correlation_id(v0, p0))?;
    let f_method = wire::required(props, path, "method", |v0: &Value, p0: &str| decode_http_method(v0, p0))?;
    let f_url = wire::required(props, path, "url", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    let f_headers = wire::optional(props, path, "headers", |v0: &Value, p0: &str| wire::map(v0, p0, |v1: &Value, p1: &str| wire::string(v1, p1)))?;
    let f_body = wire::optional(props, path, "body", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    let f_timeout_ms = wire::required(props, path, "timeoutMs", |v0: &Value, p0: &str| wire::int(v0, p0))?;
    Ok(HttpEffectRequest { correlation_id: f_correlation_id, method: f_method, url: f_url, headers: f_headers, body: f_body, timeout_ms: f_timeout_ms })
}

pub fn decode_storage_effect_request(value: &Value, path: &str) -> Result<StorageEffectRequest, DecodeError> {
    match wire::tag(value, path, "operation")?.as_str() {
        "get" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "operation", "correlationId", "key"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Storage"))?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "get"))?;
            let f_correlation_id = wire::required(props, path, "correlationId", |v0: &Value, p0: &str| decode_correlation_id(v0, p0))?;
            let f_key = wire::required(props, path, "key", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            Ok(StorageEffectRequest::Get { correlation_id: f_correlation_id, key: f_key })
        }
        "set" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "operation", "correlationId", "key", "value"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Storage"))?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "set"))?;
            let f_correlation_id = wire::required(props, path, "correlationId", |v0: &Value, p0: &str| decode_correlation_id(v0, p0))?;
            let f_key = wire::required(props, path, "key", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            let f_value = wire::required(props, path, "value", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            Ok(StorageEffectRequest::Set { correlation_id: f_correlation_id, key: f_key, value: f_value })
        }
        "remove" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "operation", "correlationId", "key"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Storage"))?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "remove"))?;
            let f_correlation_id = wire::required(props, path, "correlationId", |v0: &Value, p0: &str| decode_correlation_id(v0, p0))?;
            let f_key = wire::required(props, path, "key", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            Ok(StorageEffectRequest::Remove { correlation_id: f_correlation_id, key: f_key })
        }
        other => Err(wire::unknown_variant(&format!("{}.operation", path), other)),
    }
}

pub fn decode_clipboard_effect_request(value: &Value, path: &str) -> Result<ClipboardEffectRequest, DecodeError> {
    let props = wire::closed(wire::properties(value, path)?, path, &["kind", "correlationId", "operation", "text"])?;
    wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Clipboard"))?;
    let f_correlation_id = wire::required(props, path, "correlationId", |v0: &Value, p0: &str| decode_correlation_id(v0, p0))?;
    wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "writeText"))?;
    let f_text = wire::required(props, path, "text", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    Ok(ClipboardEffectRequest { correlation_id: f_correlation_id, text: f_text })
}

pub fn decode_navigation_effect_request(value: &Value, path: &str) -> Result<NavigationEffectRequest, DecodeError> {
    match wire::tag(value, path, "operation")?.as_str() {
        "push" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "operation", "correlationId", "url"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Navigation"))?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "push"))?;
            let f_correlation_id = wire::required(props, path, "correlationId", |v0: &Value, p0: &str| decode_correlation_id(v0, p0))?;
            let f_url = wire::required(props, path, "url", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            Ok(NavigationEffectRequest::Push { correlation_id: f_correlation_id, url: f_url })
        }
        "replace" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "operation", "correlationId", "url"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Navigation"))?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "replace"))?;
            let f_correlation_id = wire::required(props, path, "correlationId", |v0: &Value, p0: &str| decode_correlation_id(v0, p0))?;
            let f_url = wire::required(props, path, "url", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            Ok(NavigationEffectRequest::Replace { correlation_id: f_correlation_id, url: f_url })
        }
        "back" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "operation", "correlationId"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Navigation"))?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "back"))?;
            let f_correlation_id = wire::required(props, path, "correlationId", |v0: &Value, p0: &str| decode_correlation_id(v0, p0))?;
            Ok(NavigationEffectRequest::Back { correlation_id: f_correlation_id })
        }
        "forward" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "operation", "correlationId"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Navigation"))?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "forward"))?;
            let f_correlation_id = wire::required(props, path, "correlationId", |v0: &Value, p0: &str| decode_correlation_id(v0, p0))?;
            Ok(NavigationEffectRequest::Forward { correlation_id: f_correlation_id })
        }
        other => Err(wire::unknown_variant(&format!("{}.operation", path), other)),
    }
}

pub fn decode_capability_effect_request(value: &Value, path: &str) -> Result<CapabilityEffectRequest, DecodeError> {
    let props = wire::closed(wire::properties(value, path)?, path, &["kind", "correlationId", "capability", "version", "request"])?;
    wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Capability"))?;
    let f_correlation_id = wire::required(props, path, "correlationId", |v0: &Value, p0: &str| decode_correlation_id(v0, p0))?;
    let f_capability = wire::required(props, path, "capability", |v0: &Value, p0: &str| decode_capability_id(v0, p0))?;
    let f_version = wire::required(props, path, "version", |v0: &Value, p0: &str| wire::int(v0, p0))?;
    let f_request = wire::required(props, path, "request", |v0: &Value, p0: &str| wire::json(v0, p0))?;
    Ok(CapabilityEffectRequest { correlation_id: f_correlation_id, capability: f_capability, version: f_version, request: f_request })
}

pub fn decode_effect_request(value: &Value, path: &str) -> Result<EffectRequest, DecodeError> {
    match wire::tag(value, path, "kind")?.as_str() {
        "Http" => decode_http_effect_request(value, path).map(EffectRequest::Http),
        "Storage" => decode_storage_effect_request(value, path).map(EffectRequest::Storage),
        "Clipboard" => decode_clipboard_effect_request(value, path).map(EffectRequest::Clipboard),
        "Navigation" => decode_navigation_effect_request(value, path).map(EffectRequest::Navigation),
        "Capability" => decode_capability_effect_request(value, path).map(EffectRequest::Capability),
        other => Err(wire::unknown_variant(&format!("{}.kind", path), other)),
    }
}

pub fn decode_engine_to_browser_message(value: &Value, path: &str) -> Result<EngineToBrowserMessage, DecodeError> {
    let props = wire::closed(wire::properties(value, path)?, path, &["view", "effects", "cancellations", "handshake"])?;
    let f_view = wire::required(props, path, "view", |v0: &Value, p0: &str| decode_view_state(v0, p0))?;
    let f_effects = wire::required(props, path, "effects", |v0: &Value, p0: &str| wire::list(v0, p0, |v1: &Value, p1: &str| decode_effect_request(v1, p1)))?;
    let f_cancellations = wire::required(props, path, "cancellations", |v0: &Value, p0: &str| wire::list(v0, p0, |v1: &Value, p1: &str| decode_correlation_id(v1, p1)))?;
    let f_handshake = wire::optional(props, path, "handshake", |v0: &Value, p0: &str| decode_engine_handshake(v0, p0))?;
    Ok(EngineToBrowserMessage { view: f_view, effects: f_effects, cancellations: f_cancellations, handshake: f_handshake })
}

pub fn encode_correlation_id(value: &CorrelationId) -> Value {
    wire::of_string(&value.0)
}

pub fn encode_capability(value: &Capability) -> Value {
    match value {
        Capability::Http => wire::of_string("Http"),
        Capability::Storage => wire::of_string("Storage"),
        Capability::Clipboard => wire::of_string("Clipboard"),
        Capability::Navigation => wire::of_string("Navigation"),
    }
}

pub fn encode_semantic_event(value: &SemanticEvent) -> Value {
    wire::of_object(vec![Some(("kind", wire::of_string("Event"))), Some(("name", wire::of_string(&value.name))), (&value.key).as_ref().map(|x0| ("key", wire::of_string(x0))), (&value.value).as_ref().map(|x0| ("value", wire::of_string(x0)))])
}

pub fn encode_browser_location(value: &BrowserLocation) -> Value {
    wire::of_object(vec![Some(("origin", wire::of_string(&value.origin))), Some(("path", wire::of_string(&value.path))), Some(("query", wire::of_string(&value.query))), Some(("hash", wire::of_string(&value.hash)))])
}

pub fn encode_http_failure_reason(value: &HttpFailureReason) -> Value {
    match value {
        HttpFailureReason::Network => wire::of_string("network"),
        HttpFailureReason::Aborted => wire::of_string("aborted"),
        HttpFailureReason::InvalidResponse => wire::of_string("invalid-response"),
    }
}

pub fn encode_effect_outcome(value: &EffectOutcome) -> Value {
    match value {
        EffectOutcome::Success { status: f_status, body: f_body } => wire::of_object(vec![Some(("kind", wire::of_string("Success"))), Some(("status", wire::of_int(*f_status))), Some(("body", wire::of_json(f_body)))]),
        EffectOutcome::Failure { reason: f_reason, status: f_status } => wire::of_object(vec![Some(("kind", wire::of_string("Failure"))), Some(("reason", encode_http_failure_reason(f_reason))), (f_status).as_ref().map(|x0| ("status", wire::of_int(*x0)))]),
        EffectOutcome::Cancelled => wire::of_object(vec![Some(("kind", wire::of_string("Cancelled")))]),
        EffectOutcome::OutcomeUnknown => wire::of_object(vec![Some(("kind", wire::of_string("OutcomeUnknown"))), Some(("reason", wire::of_string("timeout-after-dispatch")))]),
    }
}

pub fn encode_storage_failure_reason(value: &StorageFailureReason) -> Value {
    match value {
        StorageFailureReason::Unavailable => wire::of_string("unavailable"),
        StorageFailureReason::QuotaExceeded => wire::of_string("quota-exceeded"),
    }
}

pub fn encode_storage_outcome(value: &StorageOutcome) -> Value {
    match value {
        StorageOutcome::Success { value: f_value } => wire::of_object(vec![Some(("kind", wire::of_string("Success"))), Some(("value", wire::of_nullable(f_value, |x0| wire::of_string(x0))))]),
        StorageOutcome::Failure { reason: f_reason } => wire::of_object(vec![Some(("kind", wire::of_string("Failure"))), Some(("reason", encode_storage_failure_reason(f_reason)))]),
    }
}

pub fn encode_clipboard_failure_reason(value: &ClipboardFailureReason) -> Value {
    match value {
        ClipboardFailureReason::Denied => wire::of_string("denied"),
        ClipboardFailureReason::Unavailable => wire::of_string("unavailable"),
        ClipboardFailureReason::Unknown => wire::of_string("unknown"),
    }
}

pub fn encode_clipboard_outcome(value: &ClipboardOutcome) -> Value {
    match value {
        ClipboardOutcome::Success => wire::of_object(vec![Some(("kind", wire::of_string("Success")))]),
        ClipboardOutcome::Failure { reason: f_reason } => wire::of_object(vec![Some(("kind", wire::of_string("Failure"))), Some(("reason", encode_clipboard_failure_reason(f_reason)))]),
    }
}

pub fn encode_navigation_failure_reason(value: &NavigationFailureReason) -> Value {
    match value {
        NavigationFailureReason::Unavailable => wire::of_string("unavailable"),
        NavigationFailureReason::NotSameOrigin => wire::of_string("not-same-origin"),
    }
}

pub fn encode_navigation_outcome(value: &NavigationOutcome) -> Value {
    match value {
        NavigationOutcome::Success { location: f_location } => wire::of_object(vec![Some(("kind", wire::of_string("Success"))), Some(("location", encode_browser_location(f_location)))]),
        NavigationOutcome::Dispatched => wire::of_object(vec![Some(("kind", wire::of_string("Dispatched")))]),
        NavigationOutcome::Failure { reason: f_reason } => wire::of_object(vec![Some(("kind", wire::of_string("Failure"))), Some(("reason", encode_navigation_failure_reason(f_reason)))]),
    }
}

pub fn encode_capability_id(value: &CapabilityId) -> Value {
    wire::of_string(&value.0)
}

pub fn encode_capability_unsupported_reason(value: &CapabilityUnsupportedReason) -> Value {
    match value {
        CapabilityUnsupportedReason::NotNegotiated => wire::of_string("not-negotiated"),
        CapabilityUnsupportedReason::VersionUnsupported => wire::of_string("version-unsupported"),
    }
}

pub fn encode_capability_rejected_reason(value: &CapabilityRejectedReason) -> Value {
    match value {
        CapabilityRejectedReason::MalformedRequest => wire::of_string("malformed-request"),
    }
}

pub fn encode_capability_outcome(value: &CapabilityOutcome) -> Value {
    match value {
        CapabilityOutcome::Completed { result: f_result } => wire::of_object(vec![Some(("kind", wire::of_string("Completed"))), Some(("result", wire::of_json(f_result)))]),
        CapabilityOutcome::Unsupported { reason: f_reason } => wire::of_object(vec![Some(("kind", wire::of_string("Unsupported"))), Some(("reason", encode_capability_unsupported_reason(f_reason)))]),
        CapabilityOutcome::Rejected { reason: f_reason } => wire::of_object(vec![Some(("kind", wire::of_string("Rejected"))), Some(("reason", encode_capability_rejected_reason(f_reason)))]),
    }
}

pub fn encode_effect_result(value: &EffectResult) -> Value {
    match value {
        EffectResult::HttpResult { correlation_id: f_correlation_id, outcome: f_outcome } => wire::of_object(vec![Some(("kind", wire::of_string("HttpResult"))), Some(("correlationId", encode_correlation_id(f_correlation_id))), Some(("outcome", encode_effect_outcome(f_outcome)))]),
        EffectResult::StorageResult { correlation_id: f_correlation_id, outcome: f_outcome } => wire::of_object(vec![Some(("kind", wire::of_string("StorageResult"))), Some(("correlationId", encode_correlation_id(f_correlation_id))), Some(("outcome", encode_storage_outcome(f_outcome)))]),
        EffectResult::ClipboardResult { correlation_id: f_correlation_id, outcome: f_outcome } => wire::of_object(vec![Some(("kind", wire::of_string("ClipboardResult"))), Some(("correlationId", encode_correlation_id(f_correlation_id))), Some(("outcome", encode_clipboard_outcome(f_outcome)))]),
        EffectResult::NavigationResult { correlation_id: f_correlation_id, outcome: f_outcome } => wire::of_object(vec![Some(("kind", wire::of_string("NavigationResult"))), Some(("correlationId", encode_correlation_id(f_correlation_id))), Some(("outcome", encode_navigation_outcome(f_outcome)))]),
        EffectResult::CapabilityResult { correlation_id: f_correlation_id, capability: f_capability, version: f_version, outcome: f_outcome } => wire::of_object(vec![Some(("kind", wire::of_string("CapabilityResult"))), Some(("correlationId", encode_correlation_id(f_correlation_id))), Some(("capability", encode_capability_id(f_capability))), Some(("version", wire::of_int(*f_version))), Some(("outcome", encode_capability_outcome(f_outcome)))]),
    }
}

pub fn encode_protocol_revision(value: &ProtocolRevision) -> Value {
    wire::of_object(vec![Some(("major", wire::of_int(*&value.major))), Some(("minor", wire::of_int(*&value.minor)))])
}

pub fn encode_contract_identity(value: &ContractIdentity) -> Value {
    wire::of_object(vec![Some(("unit", wire::of_string(&value.unit))), Some(("version", wire::of_int(*&value.version))), Some(("fingerprint", wire::of_string(&value.fingerprint)))])
}

pub fn encode_capability_offer(value: &CapabilityOffer) -> Value {
    wire::of_object(vec![Some(("id", encode_capability_id(&value.id))), Some(("version", wire::of_int(*&value.version))), Some(("fingerprint", wire::of_string(&value.fingerprint)))])
}

pub fn encode_host_handshake(value: &HostHandshake) -> Value {
    wire::of_object(vec![Some(("protocol", encode_protocol_revision(&value.protocol))), Some(("contract", encode_contract_identity(&value.contract))), Some(("capabilities", wire::of_list(&value.capabilities, |x0| encode_capability_offer(x0))))])
}

pub fn encode_handshake_rejection(value: &HandshakeRejection) -> Value {
    match value {
        HandshakeRejection::ProtocolUnsupported { offered: f_offered } => wire::of_object(vec![Some(("kind", wire::of_string("ProtocolUnsupported"))), Some(("offered", encode_protocol_revision(f_offered)))]),
        HandshakeRejection::ContractMismatch { expected: f_expected, offered: f_offered } => wire::of_object(vec![Some(("kind", wire::of_string("ContractMismatch"))), Some(("expected", encode_contract_identity(f_expected))), Some(("offered", encode_contract_identity(f_offered)))]),
        HandshakeRejection::CapabilityUnavailable { id: f_id, version: f_version } => wire::of_object(vec![Some(("kind", wire::of_string("CapabilityUnavailable"))), Some(("id", encode_capability_id(f_id))), Some(("version", wire::of_int(*f_version)))]),
        HandshakeRejection::HandshakeMissing => wire::of_object(vec![Some(("kind", wire::of_string("HandshakeMissing")))]),
    }
}

pub fn encode_engine_handshake(value: &EngineHandshake) -> Value {
    match value {
        EngineHandshake::Accepted { protocol: f_protocol, contract: f_contract, capabilities: f_capabilities } => wire::of_object(vec![Some(("kind", wire::of_string("Accepted"))), Some(("protocol", encode_protocol_revision(f_protocol))), Some(("contract", encode_contract_identity(f_contract))), Some(("capabilities", wire::of_list(f_capabilities, |x0| encode_capability_offer(x0))))]),
        EngineHandshake::Rejected { reason: f_reason } => wire::of_object(vec![Some(("kind", wire::of_string("Rejected"))), Some(("reason", encode_handshake_rejection(f_reason)))]),
    }
}

pub fn encode_browser_to_engine_message(value: &BrowserToEngineMessage) -> Value {
    match value {
        BrowserToEngineMessage::Initialize { capabilities: f_capabilities, location: f_location, handshake: f_handshake } => wire::of_object(vec![Some(("kind", wire::of_string("Initialize"))), Some(("protocolVersion", wire::of_int(1))), Some(("capabilities", wire::of_list(f_capabilities, |x0| encode_capability(x0)))), Some(("location", encode_browser_location(f_location))), (f_handshake).as_ref().map(|x0| ("handshake", encode_host_handshake(x0)))]),
        BrowserToEngineMessage::Event { event: f_event } => wire::of_object(vec![Some(("kind", wire::of_string("Event"))), Some(("event", encode_semantic_event(f_event)))]),
        BrowserToEngineMessage::EffectResult { result: f_result } => wire::of_object(vec![Some(("kind", wire::of_string("EffectResult"))), Some(("result", encode_effect_result(f_result)))]),
        BrowserToEngineMessage::LocationChanged { location: f_location } => wire::of_object(vec![Some(("kind", wire::of_string("LocationChanged"))), Some(("location", encode_browser_location(f_location)))]),
        BrowserToEngineMessage::CapabilityFact { capability: f_capability, version: f_version, fact: f_fact } => wire::of_object(vec![Some(("kind", wire::of_string("CapabilityFact"))), Some(("capability", encode_capability_id(f_capability))), Some(("version", wire::of_int(*f_version))), Some(("fact", wire::of_json(f_fact)))]),
    }
}

pub fn encode_view_primitive(value: &ViewPrimitive) -> Value {
    match value {
        ViewPrimitive::Text(inner) => wire::of_string(inner),
        ViewPrimitive::Number(inner) => wire::of_number(*inner),
        ViewPrimitive::Flag(inner) => wire::of_bool(*inner),
    }
}

pub fn encode_view_item(value: &ViewItem) -> Value {
    wire::of_map(value, |x0| encode_view_primitive(x0))
}

pub fn encode_view_value(value: &ViewValue) -> Value {
    match value {
        ViewValue::Text(inner) => wire::of_string(inner),
        ViewValue::Number(inner) => wire::of_number(*inner),
        ViewValue::Flag(inner) => wire::of_bool(*inner),
        ViewValue::Items(inner) => wire::of_list(inner, |x0| encode_view_item(x0)),
    }
}

pub fn encode_view_state(value: &ViewState) -> Value {
    wire::of_map(value, |x0| encode_view_value(x0))
}

pub fn encode_http_method(value: &HttpMethod) -> Value {
    match value {
        HttpMethod::Get => wire::of_string("GET"),
        HttpMethod::Put => wire::of_string("PUT"),
        HttpMethod::Post => wire::of_string("POST"),
        HttpMethod::Patch => wire::of_string("PATCH"),
        HttpMethod::Delete => wire::of_string("DELETE"),
    }
}

pub fn encode_http_effect_request(value: &HttpEffectRequest) -> Value {
    wire::of_object(vec![Some(("kind", wire::of_string("Http"))), Some(("correlationId", encode_correlation_id(&value.correlation_id))), Some(("method", encode_http_method(&value.method))), Some(("url", wire::of_string(&value.url))), (&value.headers).as_ref().map(|x0| ("headers", wire::of_map(x0, |x1| wire::of_string(x1)))), (&value.body).as_ref().map(|x0| ("body", wire::of_string(x0))), Some(("timeoutMs", wire::of_int(*&value.timeout_ms)))])
}

pub fn encode_storage_effect_request(value: &StorageEffectRequest) -> Value {
    match value {
        StorageEffectRequest::Get { correlation_id: f_correlation_id, key: f_key } => wire::of_object(vec![Some(("kind", wire::of_string("Storage"))), Some(("operation", wire::of_string("get"))), Some(("correlationId", encode_correlation_id(f_correlation_id))), Some(("key", wire::of_string(f_key)))]),
        StorageEffectRequest::Set { correlation_id: f_correlation_id, key: f_key, value: f_value } => wire::of_object(vec![Some(("kind", wire::of_string("Storage"))), Some(("operation", wire::of_string("set"))), Some(("correlationId", encode_correlation_id(f_correlation_id))), Some(("key", wire::of_string(f_key))), Some(("value", wire::of_string(f_value)))]),
        StorageEffectRequest::Remove { correlation_id: f_correlation_id, key: f_key } => wire::of_object(vec![Some(("kind", wire::of_string("Storage"))), Some(("operation", wire::of_string("remove"))), Some(("correlationId", encode_correlation_id(f_correlation_id))), Some(("key", wire::of_string(f_key)))]),
    }
}

pub fn encode_clipboard_effect_request(value: &ClipboardEffectRequest) -> Value {
    wire::of_object(vec![Some(("kind", wire::of_string("Clipboard"))), Some(("correlationId", encode_correlation_id(&value.correlation_id))), Some(("operation", wire::of_string("writeText"))), Some(("text", wire::of_string(&value.text)))])
}

pub fn encode_navigation_effect_request(value: &NavigationEffectRequest) -> Value {
    match value {
        NavigationEffectRequest::Push { correlation_id: f_correlation_id, url: f_url } => wire::of_object(vec![Some(("kind", wire::of_string("Navigation"))), Some(("operation", wire::of_string("push"))), Some(("correlationId", encode_correlation_id(f_correlation_id))), Some(("url", wire::of_string(f_url)))]),
        NavigationEffectRequest::Replace { correlation_id: f_correlation_id, url: f_url } => wire::of_object(vec![Some(("kind", wire::of_string("Navigation"))), Some(("operation", wire::of_string("replace"))), Some(("correlationId", encode_correlation_id(f_correlation_id))), Some(("url", wire::of_string(f_url)))]),
        NavigationEffectRequest::Back { correlation_id: f_correlation_id } => wire::of_object(vec![Some(("kind", wire::of_string("Navigation"))), Some(("operation", wire::of_string("back"))), Some(("correlationId", encode_correlation_id(f_correlation_id)))]),
        NavigationEffectRequest::Forward { correlation_id: f_correlation_id } => wire::of_object(vec![Some(("kind", wire::of_string("Navigation"))), Some(("operation", wire::of_string("forward"))), Some(("correlationId", encode_correlation_id(f_correlation_id)))]),
    }
}

pub fn encode_capability_effect_request(value: &CapabilityEffectRequest) -> Value {
    wire::of_object(vec![Some(("kind", wire::of_string("Capability"))), Some(("correlationId", encode_correlation_id(&value.correlation_id))), Some(("capability", encode_capability_id(&value.capability))), Some(("version", wire::of_int(*&value.version))), Some(("request", wire::of_json(&value.request)))])
}

pub fn encode_effect_request(value: &EffectRequest) -> Value {
    match value {
        EffectRequest::Http(inner) => encode_http_effect_request(inner),
        EffectRequest::Storage(inner) => encode_storage_effect_request(inner),
        EffectRequest::Clipboard(inner) => encode_clipboard_effect_request(inner),
        EffectRequest::Navigation(inner) => encode_navigation_effect_request(inner),
        EffectRequest::Capability(inner) => encode_capability_effect_request(inner),
    }
}

pub fn encode_engine_to_browser_message(value: &EngineToBrowserMessage) -> Value {
    wire::of_object(vec![Some(("view", encode_view_state(&value.view))), Some(("effects", wire::of_list(&value.effects, |x0| encode_effect_request(x0)))), Some(("cancellations", wire::of_list(&value.cancellations, |x0| encode_correlation_id(x0)))), (&value.handshake).as_ref().map(|x0| ("handshake", encode_engine_handshake(x0)))])
}

/// Parses untrusted JSON text into a CorrelationId, or says where and why it is not one.
pub fn parse_correlation_id(json: &str) -> Result<CorrelationId, DecodeError> {
    wire::parse(json, decode_correlation_id)
}

/// Serializes a CorrelationId to wire JSON text.
pub fn serialize_correlation_id(value: &CorrelationId) -> String {
    encode_correlation_id(value).to_string()
}

/// Parses untrusted JSON text into a Capability, or says where and why it is not one.
pub fn parse_capability(json: &str) -> Result<Capability, DecodeError> {
    wire::parse(json, decode_capability)
}

/// Serializes a Capability to wire JSON text.
pub fn serialize_capability(value: &Capability) -> String {
    encode_capability(value).to_string()
}

/// Parses untrusted JSON text into a SemanticEvent, or says where and why it is not one.
pub fn parse_semantic_event(json: &str) -> Result<SemanticEvent, DecodeError> {
    wire::parse(json, decode_semantic_event)
}

/// Serializes a SemanticEvent to wire JSON text.
pub fn serialize_semantic_event(value: &SemanticEvent) -> String {
    encode_semantic_event(value).to_string()
}

/// Parses untrusted JSON text into a BrowserLocation, or says where and why it is not one.
pub fn parse_browser_location(json: &str) -> Result<BrowserLocation, DecodeError> {
    wire::parse(json, decode_browser_location)
}

/// Serializes a BrowserLocation to wire JSON text.
pub fn serialize_browser_location(value: &BrowserLocation) -> String {
    encode_browser_location(value).to_string()
}

/// Parses untrusted JSON text into a HttpFailureReason, or says where and why it is not one.
pub fn parse_http_failure_reason(json: &str) -> Result<HttpFailureReason, DecodeError> {
    wire::parse(json, decode_http_failure_reason)
}

/// Serializes a HttpFailureReason to wire JSON text.
pub fn serialize_http_failure_reason(value: &HttpFailureReason) -> String {
    encode_http_failure_reason(value).to_string()
}

/// Parses untrusted JSON text into a EffectOutcome, or says where and why it is not one.
pub fn parse_effect_outcome(json: &str) -> Result<EffectOutcome, DecodeError> {
    wire::parse(json, decode_effect_outcome)
}

/// Serializes a EffectOutcome to wire JSON text.
pub fn serialize_effect_outcome(value: &EffectOutcome) -> String {
    encode_effect_outcome(value).to_string()
}

/// Parses untrusted JSON text into a StorageFailureReason, or says where and why it is not one.
pub fn parse_storage_failure_reason(json: &str) -> Result<StorageFailureReason, DecodeError> {
    wire::parse(json, decode_storage_failure_reason)
}

/// Serializes a StorageFailureReason to wire JSON text.
pub fn serialize_storage_failure_reason(value: &StorageFailureReason) -> String {
    encode_storage_failure_reason(value).to_string()
}

/// Parses untrusted JSON text into a StorageOutcome, or says where and why it is not one.
pub fn parse_storage_outcome(json: &str) -> Result<StorageOutcome, DecodeError> {
    wire::parse(json, decode_storage_outcome)
}

/// Serializes a StorageOutcome to wire JSON text.
pub fn serialize_storage_outcome(value: &StorageOutcome) -> String {
    encode_storage_outcome(value).to_string()
}

/// Parses untrusted JSON text into a ClipboardFailureReason, or says where and why it is not one.
pub fn parse_clipboard_failure_reason(json: &str) -> Result<ClipboardFailureReason, DecodeError> {
    wire::parse(json, decode_clipboard_failure_reason)
}

/// Serializes a ClipboardFailureReason to wire JSON text.
pub fn serialize_clipboard_failure_reason(value: &ClipboardFailureReason) -> String {
    encode_clipboard_failure_reason(value).to_string()
}

/// Parses untrusted JSON text into a ClipboardOutcome, or says where and why it is not one.
pub fn parse_clipboard_outcome(json: &str) -> Result<ClipboardOutcome, DecodeError> {
    wire::parse(json, decode_clipboard_outcome)
}

/// Serializes a ClipboardOutcome to wire JSON text.
pub fn serialize_clipboard_outcome(value: &ClipboardOutcome) -> String {
    encode_clipboard_outcome(value).to_string()
}

/// Parses untrusted JSON text into a NavigationFailureReason, or says where and why it is not one.
pub fn parse_navigation_failure_reason(json: &str) -> Result<NavigationFailureReason, DecodeError> {
    wire::parse(json, decode_navigation_failure_reason)
}

/// Serializes a NavigationFailureReason to wire JSON text.
pub fn serialize_navigation_failure_reason(value: &NavigationFailureReason) -> String {
    encode_navigation_failure_reason(value).to_string()
}

/// Parses untrusted JSON text into a NavigationOutcome, or says where and why it is not one.
pub fn parse_navigation_outcome(json: &str) -> Result<NavigationOutcome, DecodeError> {
    wire::parse(json, decode_navigation_outcome)
}

/// Serializes a NavigationOutcome to wire JSON text.
pub fn serialize_navigation_outcome(value: &NavigationOutcome) -> String {
    encode_navigation_outcome(value).to_string()
}

/// Parses untrusted JSON text into a CapabilityId, or says where and why it is not one.
pub fn parse_capability_id(json: &str) -> Result<CapabilityId, DecodeError> {
    wire::parse(json, decode_capability_id)
}

/// Serializes a CapabilityId to wire JSON text.
pub fn serialize_capability_id(value: &CapabilityId) -> String {
    encode_capability_id(value).to_string()
}

/// Parses untrusted JSON text into a CapabilityUnsupportedReason, or says where and why it is not one.
pub fn parse_capability_unsupported_reason(json: &str) -> Result<CapabilityUnsupportedReason, DecodeError> {
    wire::parse(json, decode_capability_unsupported_reason)
}

/// Serializes a CapabilityUnsupportedReason to wire JSON text.
pub fn serialize_capability_unsupported_reason(value: &CapabilityUnsupportedReason) -> String {
    encode_capability_unsupported_reason(value).to_string()
}

/// Parses untrusted JSON text into a CapabilityRejectedReason, or says where and why it is not one.
pub fn parse_capability_rejected_reason(json: &str) -> Result<CapabilityRejectedReason, DecodeError> {
    wire::parse(json, decode_capability_rejected_reason)
}

/// Serializes a CapabilityRejectedReason to wire JSON text.
pub fn serialize_capability_rejected_reason(value: &CapabilityRejectedReason) -> String {
    encode_capability_rejected_reason(value).to_string()
}

/// Parses untrusted JSON text into a CapabilityOutcome, or says where and why it is not one.
pub fn parse_capability_outcome(json: &str) -> Result<CapabilityOutcome, DecodeError> {
    wire::parse(json, decode_capability_outcome)
}

/// Serializes a CapabilityOutcome to wire JSON text.
pub fn serialize_capability_outcome(value: &CapabilityOutcome) -> String {
    encode_capability_outcome(value).to_string()
}

/// Parses untrusted JSON text into a EffectResult, or says where and why it is not one.
pub fn parse_effect_result(json: &str) -> Result<EffectResult, DecodeError> {
    wire::parse(json, decode_effect_result)
}

/// Serializes a EffectResult to wire JSON text.
pub fn serialize_effect_result(value: &EffectResult) -> String {
    encode_effect_result(value).to_string()
}

/// Parses untrusted JSON text into a ProtocolRevision, or says where and why it is not one.
pub fn parse_protocol_revision(json: &str) -> Result<ProtocolRevision, DecodeError> {
    wire::parse(json, decode_protocol_revision)
}

/// Serializes a ProtocolRevision to wire JSON text.
pub fn serialize_protocol_revision(value: &ProtocolRevision) -> String {
    encode_protocol_revision(value).to_string()
}

/// Parses untrusted JSON text into a ContractIdentity, or says where and why it is not one.
pub fn parse_contract_identity(json: &str) -> Result<ContractIdentity, DecodeError> {
    wire::parse(json, decode_contract_identity)
}

/// Serializes a ContractIdentity to wire JSON text.
pub fn serialize_contract_identity(value: &ContractIdentity) -> String {
    encode_contract_identity(value).to_string()
}

/// Parses untrusted JSON text into a CapabilityOffer, or says where and why it is not one.
pub fn parse_capability_offer(json: &str) -> Result<CapabilityOffer, DecodeError> {
    wire::parse(json, decode_capability_offer)
}

/// Serializes a CapabilityOffer to wire JSON text.
pub fn serialize_capability_offer(value: &CapabilityOffer) -> String {
    encode_capability_offer(value).to_string()
}

/// Parses untrusted JSON text into a HostHandshake, or says where and why it is not one.
pub fn parse_host_handshake(json: &str) -> Result<HostHandshake, DecodeError> {
    wire::parse(json, decode_host_handshake)
}

/// Serializes a HostHandshake to wire JSON text.
pub fn serialize_host_handshake(value: &HostHandshake) -> String {
    encode_host_handshake(value).to_string()
}

/// Parses untrusted JSON text into a HandshakeRejection, or says where and why it is not one.
pub fn parse_handshake_rejection(json: &str) -> Result<HandshakeRejection, DecodeError> {
    wire::parse(json, decode_handshake_rejection)
}

/// Serializes a HandshakeRejection to wire JSON text.
pub fn serialize_handshake_rejection(value: &HandshakeRejection) -> String {
    encode_handshake_rejection(value).to_string()
}

/// Parses untrusted JSON text into a EngineHandshake, or says where and why it is not one.
pub fn parse_engine_handshake(json: &str) -> Result<EngineHandshake, DecodeError> {
    wire::parse(json, decode_engine_handshake)
}

/// Serializes a EngineHandshake to wire JSON text.
pub fn serialize_engine_handshake(value: &EngineHandshake) -> String {
    encode_engine_handshake(value).to_string()
}

/// Parses untrusted JSON text into a BrowserToEngineMessage, or says where and why it is not one.
pub fn parse_browser_to_engine_message(json: &str) -> Result<BrowserToEngineMessage, DecodeError> {
    wire::parse(json, decode_browser_to_engine_message)
}

/// Serializes a BrowserToEngineMessage to wire JSON text.
pub fn serialize_browser_to_engine_message(value: &BrowserToEngineMessage) -> String {
    encode_browser_to_engine_message(value).to_string()
}

/// Parses untrusted JSON text into a ViewPrimitive, or says where and why it is not one.
pub fn parse_view_primitive(json: &str) -> Result<ViewPrimitive, DecodeError> {
    wire::parse(json, decode_view_primitive)
}

/// Serializes a ViewPrimitive to wire JSON text.
pub fn serialize_view_primitive(value: &ViewPrimitive) -> String {
    encode_view_primitive(value).to_string()
}

/// Parses untrusted JSON text into a ViewItem, or says where and why it is not one.
pub fn parse_view_item(json: &str) -> Result<ViewItem, DecodeError> {
    wire::parse(json, decode_view_item)
}

/// Serializes a ViewItem to wire JSON text.
pub fn serialize_view_item(value: &ViewItem) -> String {
    encode_view_item(value).to_string()
}

/// Parses untrusted JSON text into a ViewValue, or says where and why it is not one.
pub fn parse_view_value(json: &str) -> Result<ViewValue, DecodeError> {
    wire::parse(json, decode_view_value)
}

/// Serializes a ViewValue to wire JSON text.
pub fn serialize_view_value(value: &ViewValue) -> String {
    encode_view_value(value).to_string()
}

/// Parses untrusted JSON text into a ViewState, or says where and why it is not one.
pub fn parse_view_state(json: &str) -> Result<ViewState, DecodeError> {
    wire::parse(json, decode_view_state)
}

/// Serializes a ViewState to wire JSON text.
pub fn serialize_view_state(value: &ViewState) -> String {
    encode_view_state(value).to_string()
}

/// Parses untrusted JSON text into a HttpMethod, or says where and why it is not one.
pub fn parse_http_method(json: &str) -> Result<HttpMethod, DecodeError> {
    wire::parse(json, decode_http_method)
}

/// Serializes a HttpMethod to wire JSON text.
pub fn serialize_http_method(value: &HttpMethod) -> String {
    encode_http_method(value).to_string()
}

/// Parses untrusted JSON text into a HttpEffectRequest, or says where and why it is not one.
pub fn parse_http_effect_request(json: &str) -> Result<HttpEffectRequest, DecodeError> {
    wire::parse(json, decode_http_effect_request)
}

/// Serializes a HttpEffectRequest to wire JSON text.
pub fn serialize_http_effect_request(value: &HttpEffectRequest) -> String {
    encode_http_effect_request(value).to_string()
}

/// Parses untrusted JSON text into a StorageEffectRequest, or says where and why it is not one.
pub fn parse_storage_effect_request(json: &str) -> Result<StorageEffectRequest, DecodeError> {
    wire::parse(json, decode_storage_effect_request)
}

/// Serializes a StorageEffectRequest to wire JSON text.
pub fn serialize_storage_effect_request(value: &StorageEffectRequest) -> String {
    encode_storage_effect_request(value).to_string()
}

/// Parses untrusted JSON text into a ClipboardEffectRequest, or says where and why it is not one.
pub fn parse_clipboard_effect_request(json: &str) -> Result<ClipboardEffectRequest, DecodeError> {
    wire::parse(json, decode_clipboard_effect_request)
}

/// Serializes a ClipboardEffectRequest to wire JSON text.
pub fn serialize_clipboard_effect_request(value: &ClipboardEffectRequest) -> String {
    encode_clipboard_effect_request(value).to_string()
}

/// Parses untrusted JSON text into a NavigationEffectRequest, or says where and why it is not one.
pub fn parse_navigation_effect_request(json: &str) -> Result<NavigationEffectRequest, DecodeError> {
    wire::parse(json, decode_navigation_effect_request)
}

/// Serializes a NavigationEffectRequest to wire JSON text.
pub fn serialize_navigation_effect_request(value: &NavigationEffectRequest) -> String {
    encode_navigation_effect_request(value).to_string()
}

/// Parses untrusted JSON text into a CapabilityEffectRequest, or says where and why it is not one.
pub fn parse_capability_effect_request(json: &str) -> Result<CapabilityEffectRequest, DecodeError> {
    wire::parse(json, decode_capability_effect_request)
}

/// Serializes a CapabilityEffectRequest to wire JSON text.
pub fn serialize_capability_effect_request(value: &CapabilityEffectRequest) -> String {
    encode_capability_effect_request(value).to_string()
}

/// Parses untrusted JSON text into a EffectRequest, or says where and why it is not one.
pub fn parse_effect_request(json: &str) -> Result<EffectRequest, DecodeError> {
    wire::parse(json, decode_effect_request)
}

/// Serializes a EffectRequest to wire JSON text.
pub fn serialize_effect_request(value: &EffectRequest) -> String {
    encode_effect_request(value).to_string()
}

/// Parses untrusted JSON text into a EngineToBrowserMessage, or says where and why it is not one.
pub fn parse_engine_to_browser_message(json: &str) -> Result<EngineToBrowserMessage, DecodeError> {
    wire::parse(json, decode_engine_to_browser_message)
}

/// Serializes a EngineToBrowserMessage to wire JSON text.
pub fn serialize_engine_to_browser_message(value: &EngineToBrowserMessage) -> String {
    encode_engine_to_browser_message(value).to_string()
}

/// Decode-then-encode by type name. Used only by the shared conformance runner.
pub fn conformance_round_trip(type_name: &str, value: &Value) -> Option<Result<Value, DecodeError>> {
    match type_name {
        "CorrelationId" => Some(decode_correlation_id(value, "$").map(|decoded| encode_correlation_id(&decoded))),
        "Capability" => Some(decode_capability(value, "$").map(|decoded| encode_capability(&decoded))),
        "SemanticEvent" => Some(decode_semantic_event(value, "$").map(|decoded| encode_semantic_event(&decoded))),
        "BrowserLocation" => Some(decode_browser_location(value, "$").map(|decoded| encode_browser_location(&decoded))),
        "HttpFailureReason" => Some(decode_http_failure_reason(value, "$").map(|decoded| encode_http_failure_reason(&decoded))),
        "EffectOutcome" => Some(decode_effect_outcome(value, "$").map(|decoded| encode_effect_outcome(&decoded))),
        "StorageFailureReason" => Some(decode_storage_failure_reason(value, "$").map(|decoded| encode_storage_failure_reason(&decoded))),
        "StorageOutcome" => Some(decode_storage_outcome(value, "$").map(|decoded| encode_storage_outcome(&decoded))),
        "ClipboardFailureReason" => Some(decode_clipboard_failure_reason(value, "$").map(|decoded| encode_clipboard_failure_reason(&decoded))),
        "ClipboardOutcome" => Some(decode_clipboard_outcome(value, "$").map(|decoded| encode_clipboard_outcome(&decoded))),
        "NavigationFailureReason" => Some(decode_navigation_failure_reason(value, "$").map(|decoded| encode_navigation_failure_reason(&decoded))),
        "NavigationOutcome" => Some(decode_navigation_outcome(value, "$").map(|decoded| encode_navigation_outcome(&decoded))),
        "CapabilityId" => Some(decode_capability_id(value, "$").map(|decoded| encode_capability_id(&decoded))),
        "CapabilityUnsupportedReason" => Some(decode_capability_unsupported_reason(value, "$").map(|decoded| encode_capability_unsupported_reason(&decoded))),
        "CapabilityRejectedReason" => Some(decode_capability_rejected_reason(value, "$").map(|decoded| encode_capability_rejected_reason(&decoded))),
        "CapabilityOutcome" => Some(decode_capability_outcome(value, "$").map(|decoded| encode_capability_outcome(&decoded))),
        "EffectResult" => Some(decode_effect_result(value, "$").map(|decoded| encode_effect_result(&decoded))),
        "ProtocolRevision" => Some(decode_protocol_revision(value, "$").map(|decoded| encode_protocol_revision(&decoded))),
        "ContractIdentity" => Some(decode_contract_identity(value, "$").map(|decoded| encode_contract_identity(&decoded))),
        "CapabilityOffer" => Some(decode_capability_offer(value, "$").map(|decoded| encode_capability_offer(&decoded))),
        "HostHandshake" => Some(decode_host_handshake(value, "$").map(|decoded| encode_host_handshake(&decoded))),
        "HandshakeRejection" => Some(decode_handshake_rejection(value, "$").map(|decoded| encode_handshake_rejection(&decoded))),
        "EngineHandshake" => Some(decode_engine_handshake(value, "$").map(|decoded| encode_engine_handshake(&decoded))),
        "BrowserToEngineMessage" => Some(decode_browser_to_engine_message(value, "$").map(|decoded| encode_browser_to_engine_message(&decoded))),
        "ViewPrimitive" => Some(decode_view_primitive(value, "$").map(|decoded| encode_view_primitive(&decoded))),
        "ViewItem" => Some(decode_view_item(value, "$").map(|decoded| encode_view_item(&decoded))),
        "ViewValue" => Some(decode_view_value(value, "$").map(|decoded| encode_view_value(&decoded))),
        "ViewState" => Some(decode_view_state(value, "$").map(|decoded| encode_view_state(&decoded))),
        "HttpMethod" => Some(decode_http_method(value, "$").map(|decoded| encode_http_method(&decoded))),
        "HttpEffectRequest" => Some(decode_http_effect_request(value, "$").map(|decoded| encode_http_effect_request(&decoded))),
        "StorageEffectRequest" => Some(decode_storage_effect_request(value, "$").map(|decoded| encode_storage_effect_request(&decoded))),
        "ClipboardEffectRequest" => Some(decode_clipboard_effect_request(value, "$").map(|decoded| encode_clipboard_effect_request(&decoded))),
        "NavigationEffectRequest" => Some(decode_navigation_effect_request(value, "$").map(|decoded| encode_navigation_effect_request(&decoded))),
        "CapabilityEffectRequest" => Some(decode_capability_effect_request(value, "$").map(|decoded| encode_capability_effect_request(&decoded))),
        "EffectRequest" => Some(decode_effect_request(value, "$").map(|decoded| encode_effect_request(&decoded))),
        "EngineToBrowserMessage" => Some(decode_engine_to_browser_message(value, "$").map(|decoded| encode_engine_to_browser_message(&decoded))),
        _ => None,
    }
}
