// <auto-generated by limen-contract-gen>
// GENERATED FILE — DO NOT EDIT. Change the contract and run `npm run contract:generate`.
// source: contract/store.contract.json
// unit: limen.store@2
// contract-fingerprint: sha256:c964a8c86b6f372fecacf50617c4f88595403c2521addbc412d528b0947c903a
// generator: limen-contract-gen/1 (rust-unit)
// content-hash: sha256:4e9c77488258be15f7cebecef2c7ebeda65cc2235df3db4d09a0de61dc2077ea
// </auto-generated>
//! Durable structured browser storage over IndexedDB (LCP-018; version 2 adds LCP-043..064). The engine declares each database's version, stores and indexes; the pack creates what is declared, drops only what the engine names, and reports anything else as a typed outcome. A transaction is one atomic batch of operations, answered Committed with every result or Aborted with the operation that failed — never partly applied. What the data means, and how it migrates between versions, stays in the engine. localStorage (Core Storage effects) is unchanged. Version 2 is offered by a pack registered with an application namespace (every database name resolves inside it) and serialized-size limits; a pack registered without options still offers version 1, unchanged.


use serde_json::Value;

use crate::runtime::{wire, DecodeError, RawJson};

/// The identity of this generated contract unit, exchanged in the handshake.
pub mod contract {
    pub const UNIT: &str = "limen.store";
    pub const VERSION: i64 = 2;
    pub const FINGERPRINT: &str = "sha256:c964a8c86b6f372fecacf50617c4f88595403c2521addbc412d528b0947c903a";
}

/// keyPath is one dotted path. A compound index (version 2) gives keyPaths, two or more dotted paths, with keyPath empty; its key is the list of their values, compared element by element. A compound index cannot be multiEntry.
#[derive(Debug, Clone, PartialEq)]
pub struct IndexSchema {
    pub name: String,
    pub key_path: String,
    pub unique: bool,
    pub multi_entry: bool,
    pub key_paths: Option<Vec<String>>,
}

/// keyPath names the field that holds each record's key (a dotted path for a nested field). A compound key (version 2) gives keyPaths, two or more dotted paths, with keyPath empty: the record's key is the list of their values, so records sort by the first, then the second, and so on.
#[derive(Debug, Clone, PartialEq)]
pub struct StoreSchema {
    pub name: String,
    pub key_path: String,
    pub indexes: Vec<IndexSchema>,
    pub key_paths: Option<Vec<String>>,
}

/// The serialized-size limits this pack enforces, in bytes of UTF-8 JSON: one stored value, and all of one transaction's operations together. A request over either is InvalidRequest before the database is touched.
#[derive(Debug, Clone, PartialEq)]
pub struct StoreLimits {
    pub max_value_bytes: i64,
    pub max_transaction_bytes: i64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TransactionMode {
    Readonly,
    Readwrite,
}

impl TransactionMode {
    /// The wire text of this value.
    pub fn as_wire(&self) -> &'static str {
        match self {
            TransactionMode::Readonly => "readonly",
            TransactionMode::Readwrite => "readwrite",
        }
    }
}

/// A key is a string, a finite number, or a list of keys. Omitted bounds are open-ended.
#[derive(Debug, Clone, PartialEq)]
pub struct KeyRange {
    pub lower: Option<RawJson>,
    pub upper: Option<RawJson>,
    pub lower_open: bool,
    pub upper_open: bool,
}

#[derive(Debug, Clone, PartialEq)]
pub enum Operation {
    Get {
        store: String,
        key: RawJson,
    },
    /// Insert or replace the record whose key is at the store's keyPath in value.
    Put {
        store: String,
        value: RawJson,
    },
    /// Compare-and-put: write value only if the record stored under its key is exactly expected (JSON-equal), or absent when expected is null. Otherwise the whole transaction aborts as a conflict, reporting what is stored — the stale-write guard.
    PutIf {
        store: String,
        value: RawJson,
        expected: RawJson,
    },
    Delete {
        store: String,
        key: RawJson,
    },
    /// Records in key order (of the index, when given), at most limit (1 to 1000).
    Query {
        store: String,
        index: Option<String>,
        range: Option<KeyRange>,
        limit: i64,
        reverse: bool,
    },
    /// Version 2. How many records are in the range (of the index, when given); all of them when range is absent. Agrees with a query of the same range.
    Count {
        store: String,
        index: Option<String>,
        range: Option<KeyRange>,
    },
    /// Version 2. Delete every record whose key is in the range; an absent range clears the store. A write: refused in a readonly transaction, and undone with the rest of an aborted one.
    DeleteRange {
        store: String,
        range: Option<KeyRange>,
    },
}

#[derive(Debug, Clone, PartialEq)]
pub enum OperationResult {
    Found {
        value: RawJson,
    },
    Missing,
    Put {
        key: RawJson,
    },
    Deleted,
    Queried {
        values: Vec<RawJson>,
    },
    Counted {
        count: i64,
    },
    RangeDeleted,
}

/// Available: a probe database opened and closed inside the namespace. Missing: no indexedDB. Refused: a SecurityError, or an open refused in a private mode or with storage blocked. Broken: an open that failed for any other reason. Ephemeral, memory-backed private storage is deliberately hidden by browsers and is not detected.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum AvailabilityClass {
    Available,
    Missing,
    Refused,
    Broken,
}

impl AvailabilityClass {
    /// The wire text of this value.
    pub fn as_wire(&self) -> &'static str {
        match self {
            AvailabilityClass::Available => "Available",
            AvailabilityClass::Missing => "Missing",
            AvailabilityClass::Refused => "Refused",
            AvailabilityClass::Broken => "Broken",
        }
    }
}

/// conflict: a putIf found something else. constraint: a unique index was violated. invalidKey: a value has no valid key at the keyPath, or a key is not a valid key. quota: the browser's storage quota was exceeded. unknownStore: the store is not in the open database. other: the browser aborted for another reason.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum AbortReason {
    Conflict,
    Constraint,
    InvalidKey,
    Quota,
    UnknownStore,
    Other,
}

impl AbortReason {
    /// The wire text of this value.
    pub fn as_wire(&self) -> &'static str {
        match self {
            AbortReason::Conflict => "conflict",
            AbortReason::Constraint => "constraint",
            AbortReason::InvalidKey => "invalidKey",
            AbortReason::Quota => "quota",
            AbortReason::UnknownStore => "unknownStore",
            AbortReason::Other => "other",
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub enum StoreRequest {
    /// Open database at version. Opening at a higher version than the stored one upgrades it: every declared store and index that does not exist is created, and every store in dropStores is deleted — nothing else changes. Opening at the stored version checks the declared schema against the stored one.
    Open {
        database: String,
        version: i64,
        stores: Vec<StoreSchema>,
        drop_stores: Vec<String>,
    },
    /// Run the operations, in order, in one transaction over the stores they name.
    Transact {
        database: String,
        mode: TransactionMode,
        operations: Vec<Operation>,
    },
    Close {
        database: String,
    },
    DeleteDatabase {
        database: String,
    },
    /// Version 2. Ask the browser to exempt this origin's storage from best-effort eviction (navigator.storage.persist). The pack never asks on its own; when to ask is the engine's decision.
    Persist,
    /// Version 2. Whether this origin's storage is already persistent (navigator.storage.persisted).
    Persisted,
    /// Version 2. The browser's own approximation of this origin's usage and quota (navigator.storage.estimate). Advisory only.
    Estimate,
    /// Version 2. Classify whether IndexedDB is usable here, by opening and deleting a probe database inside the namespace.
    Availability,
}

/// Every outcome the engine must handle; the pack retries nothing.
#[derive(Debug, Clone, PartialEq)]
pub enum StoreResult {
    Opened {
        version: i64,
        /// The version before this open; equal to version when nothing was upgraded, 0 for a new database.
        upgraded_from: i64,
        /// The size limits in force. Present whenever the pack was registered with options (version 2).
        limits: Option<StoreLimits>,
        /// Whether this open created the database (it did not exist before). Present in version 2. A database found newly created where the engine's other evidence says it existed was lost: cleared or evicted.
        created: Option<bool>,
    },
    /// The stored database is newer than the version asked for: this page is out of date.
    VersionConflict {
        stored: i64,
    },
    /// At the stored version, the declared schema and the stored one differ; the connection is not kept. Each problem names a store or index.
    SchemaMismatch {
        problems: Vec<String>,
    },
    /// Another page holds an older version open and did not close it; nothing was upgraded. The pack abandons the attempt.
    Blocked,
    Committed {
        results: Vec<OperationResult>,
    },
    /// Nothing in the transaction was applied. operation is the index of the operation that failed, absent when the browser aborted the transaction as a whole at commit (quota, for example); current is what a conflicting putIf found (null when absent).
    Aborted {
        reason: AbortReason,
        operation: Option<i64>,
        current: Option<RawJson>,
    },
    /// transact or close on a database this page has not opened, or whose connection was closed by a version change.
    NotOpen,
    Closed,
    DatabaseDeleted,
    /// A malformed schema, key, range or limit, a database name outside the rules of the pack's namespace, or a value or transaction over its size limit, found before touching the database.
    InvalidRequest {
        problem: String,
    },
    /// This browser or context has no usable IndexedDB (for example some private modes). The exception's name only.
    Unavailable {
        reason: String,
    },
    /// The engine cancelled the request. A transaction cancelled while running is aborted, so nothing in it was applied.
    Cancelled,
    /// The answer to persist. A refusal, or a rejected promise, is granted false.
    Persisted {
        granted: bool,
    },
    /// The answer to persisted: whether storage is persistent now.
    Persistence {
        persistent: bool,
    },
    /// The answer to estimate: non-negative byte counts the browser approximates. A count the browser did not report is absent, never zero.
    Estimate {
        usage: Option<i64>,
        quota: Option<i64>,
    },
    /// The answer to availability. reason is an exception name only, for Refused and Broken.
    Availability {
        availability: AvailabilityClass,
        reason: Option<String>,
    },
    /// This browser has no such API (for example no navigator.storage.persist): never reported as a refusal.
    Unsupported,
}

#[derive(Debug, Clone, PartialEq)]
pub enum StoreFact {
    /// Another page upgraded or deleted this database. The pack closed this page's connection so it would not block; the engine reopens at the new version when its code understands it. newVersion is 0 for a deletion.
    VersionChanged {
        database: String,
        new_version: i64,
    },
    /// Version 2. The browser closed this page's connection abnormally: the origin's storage was cleared or evicted while it was open. The pack does not reopen; later requests on it are NotOpen until the engine opens it again.
    ConnectionLost {
        database: String,
    },
}

pub fn decode_index_schema(value: &Value, path: &str) -> Result<IndexSchema, DecodeError> {
    let props = wire::closed(wire::properties(value, path)?, path, &["name", "keyPath", "unique", "multiEntry", "keyPaths"])?;
    let f_name = wire::required(props, path, "name", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    let f_key_path = wire::required(props, path, "keyPath", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    let f_unique = wire::required(props, path, "unique", |v0: &Value, p0: &str| wire::boolean(v0, p0))?;
    let f_multi_entry = wire::required(props, path, "multiEntry", |v0: &Value, p0: &str| wire::boolean(v0, p0))?;
    let f_key_paths = wire::optional(props, path, "keyPaths", |v0: &Value, p0: &str| wire::list(v0, p0, |v1: &Value, p1: &str| wire::string(v1, p1)))?;
    Ok(IndexSchema { name: f_name, key_path: f_key_path, unique: f_unique, multi_entry: f_multi_entry, key_paths: f_key_paths })
}

pub fn decode_store_schema(value: &Value, path: &str) -> Result<StoreSchema, DecodeError> {
    let props = wire::closed(wire::properties(value, path)?, path, &["name", "keyPath", "indexes", "keyPaths"])?;
    let f_name = wire::required(props, path, "name", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    let f_key_path = wire::required(props, path, "keyPath", |v0: &Value, p0: &str| wire::string(v0, p0))?;
    let f_indexes = wire::required(props, path, "indexes", |v0: &Value, p0: &str| wire::list(v0, p0, |v1: &Value, p1: &str| decode_index_schema(v1, p1)))?;
    let f_key_paths = wire::optional(props, path, "keyPaths", |v0: &Value, p0: &str| wire::list(v0, p0, |v1: &Value, p1: &str| wire::string(v1, p1)))?;
    Ok(StoreSchema { name: f_name, key_path: f_key_path, indexes: f_indexes, key_paths: f_key_paths })
}

pub fn decode_store_limits(value: &Value, path: &str) -> Result<StoreLimits, DecodeError> {
    let props = wire::closed(wire::properties(value, path)?, path, &["maxValueBytes", "maxTransactionBytes"])?;
    let f_max_value_bytes = wire::required(props, path, "maxValueBytes", |v0: &Value, p0: &str| wire::int(v0, p0))?;
    let f_max_transaction_bytes = wire::required(props, path, "maxTransactionBytes", |v0: &Value, p0: &str| wire::int(v0, p0))?;
    Ok(StoreLimits { max_value_bytes: f_max_value_bytes, max_transaction_bytes: f_max_transaction_bytes })
}

pub fn decode_transaction_mode(value: &Value, path: &str) -> Result<TransactionMode, DecodeError> {
    wire::enumeration(value, path, &[("readonly", TransactionMode::Readonly), ("readwrite", TransactionMode::Readwrite)])
}

pub fn decode_key_range(value: &Value, path: &str) -> Result<KeyRange, DecodeError> {
    let props = wire::closed(wire::properties(value, path)?, path, &["lower", "upper", "lowerOpen", "upperOpen"])?;
    let f_lower = wire::optional(props, path, "lower", |v0: &Value, p0: &str| wire::json(v0, p0))?;
    let f_upper = wire::optional(props, path, "upper", |v0: &Value, p0: &str| wire::json(v0, p0))?;
    let f_lower_open = wire::required(props, path, "lowerOpen", |v0: &Value, p0: &str| wire::boolean(v0, p0))?;
    let f_upper_open = wire::required(props, path, "upperOpen", |v0: &Value, p0: &str| wire::boolean(v0, p0))?;
    Ok(KeyRange { lower: f_lower, upper: f_upper, lower_open: f_lower_open, upper_open: f_upper_open })
}

pub fn decode_operation(value: &Value, path: &str) -> Result<Operation, DecodeError> {
    match wire::tag(value, path, "op")?.as_str() {
        "get" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["op", "store", "key"])?;
            wire::required(props, path, "op", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "get"))?;
            let f_store = wire::required(props, path, "store", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            let f_key = wire::required(props, path, "key", |v0: &Value, p0: &str| wire::json(v0, p0))?;
            Ok(Operation::Get { store: f_store, key: f_key })
        }
        "put" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["op", "store", "value"])?;
            wire::required(props, path, "op", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "put"))?;
            let f_store = wire::required(props, path, "store", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            let f_value = wire::required(props, path, "value", |v0: &Value, p0: &str| wire::json(v0, p0))?;
            Ok(Operation::Put { store: f_store, value: f_value })
        }
        "putIf" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["op", "store", "value", "expected"])?;
            wire::required(props, path, "op", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "putIf"))?;
            let f_store = wire::required(props, path, "store", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            let f_value = wire::required(props, path, "value", |v0: &Value, p0: &str| wire::json(v0, p0))?;
            let f_expected = wire::required(props, path, "expected", |v0: &Value, p0: &str| wire::json(v0, p0))?;
            Ok(Operation::PutIf { store: f_store, value: f_value, expected: f_expected })
        }
        "delete" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["op", "store", "key"])?;
            wire::required(props, path, "op", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "delete"))?;
            let f_store = wire::required(props, path, "store", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            let f_key = wire::required(props, path, "key", |v0: &Value, p0: &str| wire::json(v0, p0))?;
            Ok(Operation::Delete { store: f_store, key: f_key })
        }
        "query" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["op", "store", "index", "range", "limit", "reverse"])?;
            wire::required(props, path, "op", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "query"))?;
            let f_store = wire::required(props, path, "store", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            let f_index = wire::optional(props, path, "index", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            let f_range = wire::optional(props, path, "range", |v0: &Value, p0: &str| decode_key_range(v0, p0))?;
            let f_limit = wire::required(props, path, "limit", |v0: &Value, p0: &str| wire::int(v0, p0))?;
            let f_reverse = wire::required(props, path, "reverse", |v0: &Value, p0: &str| wire::boolean(v0, p0))?;
            Ok(Operation::Query { store: f_store, index: f_index, range: f_range, limit: f_limit, reverse: f_reverse })
        }
        "count" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["op", "store", "index", "range"])?;
            wire::required(props, path, "op", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "count"))?;
            let f_store = wire::required(props, path, "store", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            let f_index = wire::optional(props, path, "index", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            let f_range = wire::optional(props, path, "range", |v0: &Value, p0: &str| decode_key_range(v0, p0))?;
            Ok(Operation::Count { store: f_store, index: f_index, range: f_range })
        }
        "deleteRange" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["op", "store", "range"])?;
            wire::required(props, path, "op", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "deleteRange"))?;
            let f_store = wire::required(props, path, "store", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            let f_range = wire::optional(props, path, "range", |v0: &Value, p0: &str| decode_key_range(v0, p0))?;
            Ok(Operation::DeleteRange { store: f_store, range: f_range })
        }
        other => Err(wire::unknown_variant(&format!("{}.op", path), other)),
    }
}

pub fn decode_operation_result(value: &Value, path: &str) -> Result<OperationResult, DecodeError> {
    match wire::tag(value, path, "kind")?.as_str() {
        "Found" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "value"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Found"))?;
            let f_value = wire::required(props, path, "value", |v0: &Value, p0: &str| wire::json(v0, p0))?;
            Ok(OperationResult::Found { value: f_value })
        }
        "Missing" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Missing"))?;
            Ok(OperationResult::Missing)
        }
        "Put" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "key"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Put"))?;
            let f_key = wire::required(props, path, "key", |v0: &Value, p0: &str| wire::json(v0, p0))?;
            Ok(OperationResult::Put { key: f_key })
        }
        "Deleted" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Deleted"))?;
            Ok(OperationResult::Deleted)
        }
        "Queried" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "values"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Queried"))?;
            let f_values = wire::required(props, path, "values", |v0: &Value, p0: &str| wire::list(v0, p0, |v1: &Value, p1: &str| wire::json(v1, p1)))?;
            Ok(OperationResult::Queried { values: f_values })
        }
        "Counted" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "count"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Counted"))?;
            let f_count = wire::required(props, path, "count", |v0: &Value, p0: &str| wire::int(v0, p0))?;
            Ok(OperationResult::Counted { count: f_count })
        }
        "RangeDeleted" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "RangeDeleted"))?;
            Ok(OperationResult::RangeDeleted)
        }
        other => Err(wire::unknown_variant(&format!("{}.kind", path), other)),
    }
}

pub fn decode_availability_class(value: &Value, path: &str) -> Result<AvailabilityClass, DecodeError> {
    wire::enumeration(value, path, &[("Available", AvailabilityClass::Available), ("Missing", AvailabilityClass::Missing), ("Refused", AvailabilityClass::Refused), ("Broken", AvailabilityClass::Broken)])
}

pub fn decode_abort_reason(value: &Value, path: &str) -> Result<AbortReason, DecodeError> {
    wire::enumeration(value, path, &[("conflict", AbortReason::Conflict), ("constraint", AbortReason::Constraint), ("invalidKey", AbortReason::InvalidKey), ("quota", AbortReason::Quota), ("unknownStore", AbortReason::UnknownStore), ("other", AbortReason::Other)])
}

pub fn decode_store_request(value: &Value, path: &str) -> Result<StoreRequest, DecodeError> {
    match wire::tag(value, path, "operation")?.as_str() {
        "open" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation", "database", "version", "stores", "dropStores"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "open"))?;
            let f_database = wire::required(props, path, "database", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            let f_version = wire::required(props, path, "version", |v0: &Value, p0: &str| wire::int(v0, p0))?;
            let f_stores = wire::required(props, path, "stores", |v0: &Value, p0: &str| wire::list(v0, p0, |v1: &Value, p1: &str| decode_store_schema(v1, p1)))?;
            let f_drop_stores = wire::required(props, path, "dropStores", |v0: &Value, p0: &str| wire::list(v0, p0, |v1: &Value, p1: &str| wire::string(v1, p1)))?;
            Ok(StoreRequest::Open { database: f_database, version: f_version, stores: f_stores, drop_stores: f_drop_stores })
        }
        "transact" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation", "database", "mode", "operations"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "transact"))?;
            let f_database = wire::required(props, path, "database", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            let f_mode = wire::required(props, path, "mode", |v0: &Value, p0: &str| decode_transaction_mode(v0, p0))?;
            let f_operations = wire::required(props, path, "operations", |v0: &Value, p0: &str| wire::list(v0, p0, |v1: &Value, p1: &str| decode_operation(v1, p1)))?;
            Ok(StoreRequest::Transact { database: f_database, mode: f_mode, operations: f_operations })
        }
        "close" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation", "database"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "close"))?;
            let f_database = wire::required(props, path, "database", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            Ok(StoreRequest::Close { database: f_database })
        }
        "deleteDatabase" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation", "database"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "deleteDatabase"))?;
            let f_database = wire::required(props, path, "database", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            Ok(StoreRequest::DeleteDatabase { database: f_database })
        }
        "persist" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "persist"))?;
            Ok(StoreRequest::Persist)
        }
        "persisted" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "persisted"))?;
            Ok(StoreRequest::Persisted)
        }
        "estimate" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "estimate"))?;
            Ok(StoreRequest::Estimate)
        }
        "availability" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "availability"))?;
            Ok(StoreRequest::Availability)
        }
        other => Err(wire::unknown_variant(&format!("{}.operation", path), other)),
    }
}

pub fn decode_store_result(value: &Value, path: &str) -> Result<StoreResult, DecodeError> {
    match wire::tag(value, path, "kind")?.as_str() {
        "Opened" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "version", "upgradedFrom", "limits", "created"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Opened"))?;
            let f_version = wire::required(props, path, "version", |v0: &Value, p0: &str| wire::int(v0, p0))?;
            let f_upgraded_from = wire::required(props, path, "upgradedFrom", |v0: &Value, p0: &str| wire::int(v0, p0))?;
            let f_limits = wire::optional(props, path, "limits", |v0: &Value, p0: &str| decode_store_limits(v0, p0))?;
            let f_created = wire::optional(props, path, "created", |v0: &Value, p0: &str| wire::boolean(v0, p0))?;
            Ok(StoreResult::Opened { version: f_version, upgraded_from: f_upgraded_from, limits: f_limits, created: f_created })
        }
        "VersionConflict" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "stored"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "VersionConflict"))?;
            let f_stored = wire::required(props, path, "stored", |v0: &Value, p0: &str| wire::int(v0, p0))?;
            Ok(StoreResult::VersionConflict { stored: f_stored })
        }
        "SchemaMismatch" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "problems"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "SchemaMismatch"))?;
            let f_problems = wire::required(props, path, "problems", |v0: &Value, p0: &str| wire::list(v0, p0, |v1: &Value, p1: &str| wire::string(v1, p1)))?;
            Ok(StoreResult::SchemaMismatch { problems: f_problems })
        }
        "Blocked" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Blocked"))?;
            Ok(StoreResult::Blocked)
        }
        "Committed" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "results"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Committed"))?;
            let f_results = wire::required(props, path, "results", |v0: &Value, p0: &str| wire::list(v0, p0, |v1: &Value, p1: &str| decode_operation_result(v1, p1)))?;
            Ok(StoreResult::Committed { results: f_results })
        }
        "Aborted" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "reason", "operation", "current"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Aborted"))?;
            let f_reason = wire::required(props, path, "reason", |v0: &Value, p0: &str| decode_abort_reason(v0, p0))?;
            let f_operation = wire::optional(props, path, "operation", |v0: &Value, p0: &str| wire::int(v0, p0))?;
            let f_current = wire::optional(props, path, "current", |v0: &Value, p0: &str| wire::json(v0, p0))?;
            Ok(StoreResult::Aborted { reason: f_reason, operation: f_operation, current: f_current })
        }
        "NotOpen" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "NotOpen"))?;
            Ok(StoreResult::NotOpen)
        }
        "Closed" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Closed"))?;
            Ok(StoreResult::Closed)
        }
        "DatabaseDeleted" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "DatabaseDeleted"))?;
            Ok(StoreResult::DatabaseDeleted)
        }
        "InvalidRequest" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "problem"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "InvalidRequest"))?;
            let f_problem = wire::required(props, path, "problem", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            Ok(StoreResult::InvalidRequest { problem: f_problem })
        }
        "Unavailable" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "reason"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Unavailable"))?;
            let f_reason = wire::required(props, path, "reason", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            Ok(StoreResult::Unavailable { reason: f_reason })
        }
        "Cancelled" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Cancelled"))?;
            Ok(StoreResult::Cancelled)
        }
        "Persisted" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "granted"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Persisted"))?;
            let f_granted = wire::required(props, path, "granted", |v0: &Value, p0: &str| wire::boolean(v0, p0))?;
            Ok(StoreResult::Persisted { granted: f_granted })
        }
        "Persistence" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "persistent"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Persistence"))?;
            let f_persistent = wire::required(props, path, "persistent", |v0: &Value, p0: &str| wire::boolean(v0, p0))?;
            Ok(StoreResult::Persistence { persistent: f_persistent })
        }
        "Estimate" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "usage", "quota"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Estimate"))?;
            let f_usage = wire::optional(props, path, "usage", |v0: &Value, p0: &str| wire::int(v0, p0))?;
            let f_quota = wire::optional(props, path, "quota", |v0: &Value, p0: &str| wire::int(v0, p0))?;
            Ok(StoreResult::Estimate { usage: f_usage, quota: f_quota })
        }
        "Availability" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "availability", "reason"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Availability"))?;
            let f_availability = wire::required(props, path, "availability", |v0: &Value, p0: &str| decode_availability_class(v0, p0))?;
            let f_reason = wire::optional(props, path, "reason", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            Ok(StoreResult::Availability { availability: f_availability, reason: f_reason })
        }
        "Unsupported" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Unsupported"))?;
            Ok(StoreResult::Unsupported)
        }
        other => Err(wire::unknown_variant(&format!("{}.kind", path), other)),
    }
}

pub fn decode_store_fact(value: &Value, path: &str) -> Result<StoreFact, DecodeError> {
    match wire::tag(value, path, "kind")?.as_str() {
        "VersionChanged" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "database", "newVersion"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "VersionChanged"))?;
            let f_database = wire::required(props, path, "database", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            let f_new_version = wire::required(props, path, "newVersion", |v0: &Value, p0: &str| wire::int(v0, p0))?;
            Ok(StoreFact::VersionChanged { database: f_database, new_version: f_new_version })
        }
        "ConnectionLost" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "database"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "ConnectionLost"))?;
            let f_database = wire::required(props, path, "database", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            Ok(StoreFact::ConnectionLost { database: f_database })
        }
        other => Err(wire::unknown_variant(&format!("{}.kind", path), other)),
    }
}

pub fn encode_index_schema(value: &IndexSchema) -> Value {
    wire::of_object(vec![Some(("name", wire::of_string(&value.name))), Some(("keyPath", wire::of_string(&value.key_path))), Some(("unique", wire::of_bool(*&value.unique))), Some(("multiEntry", wire::of_bool(*&value.multi_entry))), (&value.key_paths).as_ref().map(|x0| ("keyPaths", wire::of_list(x0, |x1| wire::of_string(x1))))])
}

pub fn encode_store_schema(value: &StoreSchema) -> Value {
    wire::of_object(vec![Some(("name", wire::of_string(&value.name))), Some(("keyPath", wire::of_string(&value.key_path))), Some(("indexes", wire::of_list(&value.indexes, |x0| encode_index_schema(x0)))), (&value.key_paths).as_ref().map(|x0| ("keyPaths", wire::of_list(x0, |x1| wire::of_string(x1))))])
}

pub fn encode_store_limits(value: &StoreLimits) -> Value {
    wire::of_object(vec![Some(("maxValueBytes", wire::of_int(*&value.max_value_bytes))), Some(("maxTransactionBytes", wire::of_int(*&value.max_transaction_bytes)))])
}

pub fn encode_transaction_mode(value: &TransactionMode) -> Value {
    match value {
        TransactionMode::Readonly => wire::of_string("readonly"),
        TransactionMode::Readwrite => wire::of_string("readwrite"),
    }
}

pub fn encode_key_range(value: &KeyRange) -> Value {
    wire::of_object(vec![(&value.lower).as_ref().map(|x0| ("lower", wire::of_json(x0))), (&value.upper).as_ref().map(|x0| ("upper", wire::of_json(x0))), Some(("lowerOpen", wire::of_bool(*&value.lower_open))), Some(("upperOpen", wire::of_bool(*&value.upper_open)))])
}

pub fn encode_operation(value: &Operation) -> Value {
    match value {
        Operation::Get { store: f_store, key: f_key } => wire::of_object(vec![Some(("op", wire::of_string("get"))), Some(("store", wire::of_string(f_store))), Some(("key", wire::of_json(f_key)))]),
        Operation::Put { store: f_store, value: f_value } => wire::of_object(vec![Some(("op", wire::of_string("put"))), Some(("store", wire::of_string(f_store))), Some(("value", wire::of_json(f_value)))]),
        Operation::PutIf { store: f_store, value: f_value, expected: f_expected } => wire::of_object(vec![Some(("op", wire::of_string("putIf"))), Some(("store", wire::of_string(f_store))), Some(("value", wire::of_json(f_value))), Some(("expected", wire::of_json(f_expected)))]),
        Operation::Delete { store: f_store, key: f_key } => wire::of_object(vec![Some(("op", wire::of_string("delete"))), Some(("store", wire::of_string(f_store))), Some(("key", wire::of_json(f_key)))]),
        Operation::Query { store: f_store, index: f_index, range: f_range, limit: f_limit, reverse: f_reverse } => wire::of_object(vec![Some(("op", wire::of_string("query"))), Some(("store", wire::of_string(f_store))), (f_index).as_ref().map(|x0| ("index", wire::of_string(x0))), (f_range).as_ref().map(|x0| ("range", encode_key_range(x0))), Some(("limit", wire::of_int(*f_limit))), Some(("reverse", wire::of_bool(*f_reverse)))]),
        Operation::Count { store: f_store, index: f_index, range: f_range } => wire::of_object(vec![Some(("op", wire::of_string("count"))), Some(("store", wire::of_string(f_store))), (f_index).as_ref().map(|x0| ("index", wire::of_string(x0))), (f_range).as_ref().map(|x0| ("range", encode_key_range(x0)))]),
        Operation::DeleteRange { store: f_store, range: f_range } => wire::of_object(vec![Some(("op", wire::of_string("deleteRange"))), Some(("store", wire::of_string(f_store))), (f_range).as_ref().map(|x0| ("range", encode_key_range(x0)))]),
    }
}

pub fn encode_operation_result(value: &OperationResult) -> Value {
    match value {
        OperationResult::Found { value: f_value } => wire::of_object(vec![Some(("kind", wire::of_string("Found"))), Some(("value", wire::of_json(f_value)))]),
        OperationResult::Missing => wire::of_object(vec![Some(("kind", wire::of_string("Missing")))]),
        OperationResult::Put { key: f_key } => wire::of_object(vec![Some(("kind", wire::of_string("Put"))), Some(("key", wire::of_json(f_key)))]),
        OperationResult::Deleted => wire::of_object(vec![Some(("kind", wire::of_string("Deleted")))]),
        OperationResult::Queried { values: f_values } => wire::of_object(vec![Some(("kind", wire::of_string("Queried"))), Some(("values", wire::of_list(f_values, |x0| wire::of_json(x0))))]),
        OperationResult::Counted { count: f_count } => wire::of_object(vec![Some(("kind", wire::of_string("Counted"))), Some(("count", wire::of_int(*f_count)))]),
        OperationResult::RangeDeleted => wire::of_object(vec![Some(("kind", wire::of_string("RangeDeleted")))]),
    }
}

pub fn encode_availability_class(value: &AvailabilityClass) -> Value {
    match value {
        AvailabilityClass::Available => wire::of_string("Available"),
        AvailabilityClass::Missing => wire::of_string("Missing"),
        AvailabilityClass::Refused => wire::of_string("Refused"),
        AvailabilityClass::Broken => wire::of_string("Broken"),
    }
}

pub fn encode_abort_reason(value: &AbortReason) -> Value {
    match value {
        AbortReason::Conflict => wire::of_string("conflict"),
        AbortReason::Constraint => wire::of_string("constraint"),
        AbortReason::InvalidKey => wire::of_string("invalidKey"),
        AbortReason::Quota => wire::of_string("quota"),
        AbortReason::UnknownStore => wire::of_string("unknownStore"),
        AbortReason::Other => wire::of_string("other"),
    }
}

pub fn encode_store_request(value: &StoreRequest) -> Value {
    match value {
        StoreRequest::Open { database: f_database, version: f_version, stores: f_stores, drop_stores: f_drop_stores } => wire::of_object(vec![Some(("operation", wire::of_string("open"))), Some(("database", wire::of_string(f_database))), Some(("version", wire::of_int(*f_version))), Some(("stores", wire::of_list(f_stores, |x0| encode_store_schema(x0)))), Some(("dropStores", wire::of_list(f_drop_stores, |x0| wire::of_string(x0))))]),
        StoreRequest::Transact { database: f_database, mode: f_mode, operations: f_operations } => wire::of_object(vec![Some(("operation", wire::of_string("transact"))), Some(("database", wire::of_string(f_database))), Some(("mode", encode_transaction_mode(f_mode))), Some(("operations", wire::of_list(f_operations, |x0| encode_operation(x0))))]),
        StoreRequest::Close { database: f_database } => wire::of_object(vec![Some(("operation", wire::of_string("close"))), Some(("database", wire::of_string(f_database)))]),
        StoreRequest::DeleteDatabase { database: f_database } => wire::of_object(vec![Some(("operation", wire::of_string("deleteDatabase"))), Some(("database", wire::of_string(f_database)))]),
        StoreRequest::Persist => wire::of_object(vec![Some(("operation", wire::of_string("persist")))]),
        StoreRequest::Persisted => wire::of_object(vec![Some(("operation", wire::of_string("persisted")))]),
        StoreRequest::Estimate => wire::of_object(vec![Some(("operation", wire::of_string("estimate")))]),
        StoreRequest::Availability => wire::of_object(vec![Some(("operation", wire::of_string("availability")))]),
    }
}

pub fn encode_store_result(value: &StoreResult) -> Value {
    match value {
        StoreResult::Opened { version: f_version, upgraded_from: f_upgraded_from, limits: f_limits, created: f_created } => wire::of_object(vec![Some(("kind", wire::of_string("Opened"))), Some(("version", wire::of_int(*f_version))), Some(("upgradedFrom", wire::of_int(*f_upgraded_from))), (f_limits).as_ref().map(|x0| ("limits", encode_store_limits(x0))), (f_created).as_ref().map(|x0| ("created", wire::of_bool(*x0)))]),
        StoreResult::VersionConflict { stored: f_stored } => wire::of_object(vec![Some(("kind", wire::of_string("VersionConflict"))), Some(("stored", wire::of_int(*f_stored)))]),
        StoreResult::SchemaMismatch { problems: f_problems } => wire::of_object(vec![Some(("kind", wire::of_string("SchemaMismatch"))), Some(("problems", wire::of_list(f_problems, |x0| wire::of_string(x0))))]),
        StoreResult::Blocked => wire::of_object(vec![Some(("kind", wire::of_string("Blocked")))]),
        StoreResult::Committed { results: f_results } => wire::of_object(vec![Some(("kind", wire::of_string("Committed"))), Some(("results", wire::of_list(f_results, |x0| encode_operation_result(x0))))]),
        StoreResult::Aborted { reason: f_reason, operation: f_operation, current: f_current } => wire::of_object(vec![Some(("kind", wire::of_string("Aborted"))), Some(("reason", encode_abort_reason(f_reason))), (f_operation).as_ref().map(|x0| ("operation", wire::of_int(*x0))), (f_current).as_ref().map(|x0| ("current", wire::of_json(x0)))]),
        StoreResult::NotOpen => wire::of_object(vec![Some(("kind", wire::of_string("NotOpen")))]),
        StoreResult::Closed => wire::of_object(vec![Some(("kind", wire::of_string("Closed")))]),
        StoreResult::DatabaseDeleted => wire::of_object(vec![Some(("kind", wire::of_string("DatabaseDeleted")))]),
        StoreResult::InvalidRequest { problem: f_problem } => wire::of_object(vec![Some(("kind", wire::of_string("InvalidRequest"))), Some(("problem", wire::of_string(f_problem)))]),
        StoreResult::Unavailable { reason: f_reason } => wire::of_object(vec![Some(("kind", wire::of_string("Unavailable"))), Some(("reason", wire::of_string(f_reason)))]),
        StoreResult::Cancelled => wire::of_object(vec![Some(("kind", wire::of_string("Cancelled")))]),
        StoreResult::Persisted { granted: f_granted } => wire::of_object(vec![Some(("kind", wire::of_string("Persisted"))), Some(("granted", wire::of_bool(*f_granted)))]),
        StoreResult::Persistence { persistent: f_persistent } => wire::of_object(vec![Some(("kind", wire::of_string("Persistence"))), Some(("persistent", wire::of_bool(*f_persistent)))]),
        StoreResult::Estimate { usage: f_usage, quota: f_quota } => wire::of_object(vec![Some(("kind", wire::of_string("Estimate"))), (f_usage).as_ref().map(|x0| ("usage", wire::of_int(*x0))), (f_quota).as_ref().map(|x0| ("quota", wire::of_int(*x0)))]),
        StoreResult::Availability { availability: f_availability, reason: f_reason } => wire::of_object(vec![Some(("kind", wire::of_string("Availability"))), Some(("availability", encode_availability_class(f_availability))), (f_reason).as_ref().map(|x0| ("reason", wire::of_string(x0)))]),
        StoreResult::Unsupported => wire::of_object(vec![Some(("kind", wire::of_string("Unsupported")))]),
    }
}

pub fn encode_store_fact(value: &StoreFact) -> Value {
    match value {
        StoreFact::VersionChanged { database: f_database, new_version: f_new_version } => wire::of_object(vec![Some(("kind", wire::of_string("VersionChanged"))), Some(("database", wire::of_string(f_database))), Some(("newVersion", wire::of_int(*f_new_version)))]),
        StoreFact::ConnectionLost { database: f_database } => wire::of_object(vec![Some(("kind", wire::of_string("ConnectionLost"))), Some(("database", wire::of_string(f_database)))]),
    }
}

/// Parses untrusted JSON text into a IndexSchema, or says where and why it is not one.
pub fn parse_index_schema(json: &str) -> Result<IndexSchema, DecodeError> {
    wire::parse(json, decode_index_schema)
}

/// Serializes a IndexSchema to wire JSON text.
pub fn serialize_index_schema(value: &IndexSchema) -> String {
    encode_index_schema(value).to_string()
}

/// Parses untrusted JSON text into a StoreSchema, or says where and why it is not one.
pub fn parse_store_schema(json: &str) -> Result<StoreSchema, DecodeError> {
    wire::parse(json, decode_store_schema)
}

/// Serializes a StoreSchema to wire JSON text.
pub fn serialize_store_schema(value: &StoreSchema) -> String {
    encode_store_schema(value).to_string()
}

/// Parses untrusted JSON text into a StoreLimits, or says where and why it is not one.
pub fn parse_store_limits(json: &str) -> Result<StoreLimits, DecodeError> {
    wire::parse(json, decode_store_limits)
}

/// Serializes a StoreLimits to wire JSON text.
pub fn serialize_store_limits(value: &StoreLimits) -> String {
    encode_store_limits(value).to_string()
}

/// Parses untrusted JSON text into a TransactionMode, or says where and why it is not one.
pub fn parse_transaction_mode(json: &str) -> Result<TransactionMode, DecodeError> {
    wire::parse(json, decode_transaction_mode)
}

/// Serializes a TransactionMode to wire JSON text.
pub fn serialize_transaction_mode(value: &TransactionMode) -> String {
    encode_transaction_mode(value).to_string()
}

/// Parses untrusted JSON text into a KeyRange, or says where and why it is not one.
pub fn parse_key_range(json: &str) -> Result<KeyRange, DecodeError> {
    wire::parse(json, decode_key_range)
}

/// Serializes a KeyRange to wire JSON text.
pub fn serialize_key_range(value: &KeyRange) -> String {
    encode_key_range(value).to_string()
}

/// Parses untrusted JSON text into a Operation, or says where and why it is not one.
pub fn parse_operation(json: &str) -> Result<Operation, DecodeError> {
    wire::parse(json, decode_operation)
}

/// Serializes a Operation to wire JSON text.
pub fn serialize_operation(value: &Operation) -> String {
    encode_operation(value).to_string()
}

/// Parses untrusted JSON text into a OperationResult, or says where and why it is not one.
pub fn parse_operation_result(json: &str) -> Result<OperationResult, DecodeError> {
    wire::parse(json, decode_operation_result)
}

/// Serializes a OperationResult to wire JSON text.
pub fn serialize_operation_result(value: &OperationResult) -> String {
    encode_operation_result(value).to_string()
}

/// Parses untrusted JSON text into a AvailabilityClass, or says where and why it is not one.
pub fn parse_availability_class(json: &str) -> Result<AvailabilityClass, DecodeError> {
    wire::parse(json, decode_availability_class)
}

/// Serializes a AvailabilityClass to wire JSON text.
pub fn serialize_availability_class(value: &AvailabilityClass) -> String {
    encode_availability_class(value).to_string()
}

/// Parses untrusted JSON text into a AbortReason, or says where and why it is not one.
pub fn parse_abort_reason(json: &str) -> Result<AbortReason, DecodeError> {
    wire::parse(json, decode_abort_reason)
}

/// Serializes a AbortReason to wire JSON text.
pub fn serialize_abort_reason(value: &AbortReason) -> String {
    encode_abort_reason(value).to_string()
}

/// Parses untrusted JSON text into a StoreRequest, or says where and why it is not one.
pub fn parse_store_request(json: &str) -> Result<StoreRequest, DecodeError> {
    wire::parse(json, decode_store_request)
}

/// Serializes a StoreRequest to wire JSON text.
pub fn serialize_store_request(value: &StoreRequest) -> String {
    encode_store_request(value).to_string()
}

/// Parses untrusted JSON text into a StoreResult, or says where and why it is not one.
pub fn parse_store_result(json: &str) -> Result<StoreResult, DecodeError> {
    wire::parse(json, decode_store_result)
}

/// Serializes a StoreResult to wire JSON text.
pub fn serialize_store_result(value: &StoreResult) -> String {
    encode_store_result(value).to_string()
}

/// Parses untrusted JSON text into a StoreFact, or says where and why it is not one.
pub fn parse_store_fact(json: &str) -> Result<StoreFact, DecodeError> {
    wire::parse(json, decode_store_fact)
}

/// Serializes a StoreFact to wire JSON text.
pub fn serialize_store_fact(value: &StoreFact) -> String {
    encode_store_fact(value).to_string()
}

/// Decode-then-encode by type name. Used only by the shared conformance runner.
pub fn conformance_round_trip(type_name: &str, value: &Value) -> Option<Result<Value, DecodeError>> {
    match type_name {
        "IndexSchema" => Some(decode_index_schema(value, "$").map(|decoded| encode_index_schema(&decoded))),
        "StoreSchema" => Some(decode_store_schema(value, "$").map(|decoded| encode_store_schema(&decoded))),
        "StoreLimits" => Some(decode_store_limits(value, "$").map(|decoded| encode_store_limits(&decoded))),
        "TransactionMode" => Some(decode_transaction_mode(value, "$").map(|decoded| encode_transaction_mode(&decoded))),
        "KeyRange" => Some(decode_key_range(value, "$").map(|decoded| encode_key_range(&decoded))),
        "Operation" => Some(decode_operation(value, "$").map(|decoded| encode_operation(&decoded))),
        "OperationResult" => Some(decode_operation_result(value, "$").map(|decoded| encode_operation_result(&decoded))),
        "AvailabilityClass" => Some(decode_availability_class(value, "$").map(|decoded| encode_availability_class(&decoded))),
        "AbortReason" => Some(decode_abort_reason(value, "$").map(|decoded| encode_abort_reason(&decoded))),
        "StoreRequest" => Some(decode_store_request(value, "$").map(|decoded| encode_store_request(&decoded))),
        "StoreResult" => Some(decode_store_result(value, "$").map(|decoded| encode_store_result(&decoded))),
        "StoreFact" => Some(decode_store_fact(value, "$").map(|decoded| encode_store_fact(&decoded))),
        _ => None,
    }
}
