// <auto-generated by limen-contract-gen>
// GENERATED FILE — DO NOT EDIT. Change the contract and run `npm run contract:generate`.
// source: contract/coordination.contract.json
// unit: limen.coordination@1
// contract-fingerprint: sha256:510dfbcd2f3f7966b842d518d209a511ada3ffb30132853f291e9d5fa8342684
// generator: limen-contract-gen/1 (rust-unit)
// content-hash: sha256:1c351cfe3dfaf21e742629af9ef104d49457c399aac0fc38d49731bd04e5923a
// </auto-generated>
//! Coordination among tabs, windows, frames and workers of one application (LCP-040), without shared mutable state: each context's engine keeps its own state, and only JSON messages cross. Channels are same-origin broadcast (BroadcastChannel, or a SharedWorker hub the host serves); frame messaging is point-to-point with one exact origin, never a wildcard, and accepts only messages from that frame at that origin. Every message is size-bounded and checked as JSON before an engine sees it; the engine decodes its own schema. Web Locks are coordination mechanics: holding one means only that no other context holds it; what that means (a leader, a writer) is the engine's. A context that disappears releases its locks, so the next contender acquires.


use serde_json::Value;

use crate::runtime::{wire, DecodeError, RawJson};

/// The identity of this generated contract unit, exchanged in the handshake.
pub mod contract {
    pub const UNIT: &str = "limen.coordination";
    pub const VERSION: i64 = 1;
    pub const FINGERPRINT: &str = "sha256:510dfbcd2f3f7966b842d518d209a511ada3ffb30132853f291e9d5fa8342684";
}

/// This page instance, issued at random by the pack; how other contexts tell messages apart.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ContextId(pub String);

/// Opaque; issued by this page's pack.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct LockHandle(pub String);

/// Opaque; a frame or parent this page listens to.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct PeerId(pub String);

/// broadcast: BroadcastChannel. hub: a SharedWorker relay the host serves.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Via {
    Broadcast,
    Hub,
}

impl Via {
    /// The wire text of this value.
    pub fn as_wire(&self) -> &'static str {
        match self {
            Via::Broadcast => "broadcast",
            Via::Hub => "hub",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum LockMode {
    Exclusive,
    Shared,
}

impl LockMode {
    /// The wire text of this value.
    pub fn as_wire(&self) -> &'static str {
        match self {
            LockMode::Exclusive => "exclusive",
            LockMode::Shared => "shared",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum UndeliverableReason {
    NotJson,
    Malformed,
    TooLarge,
}

impl UndeliverableReason {
    /// The wire text of this value.
    pub fn as_wire(&self) -> &'static str {
        match self {
            UndeliverableReason::NotJson => "not-json",
            UndeliverableReason::Malformed => "malformed",
            UndeliverableReason::TooLarge => "too-large",
        }
    }
}

/// wrong-origin: the sender's origin is not the declared one. wrong-source: right origin, but not the declared frame. not-json: the message was not bounded JSON.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum RefusedReason {
    WrongOrigin,
    WrongSource,
    NotJson,
}

impl RefusedReason {
    /// The wire text of this value.
    pub fn as_wire(&self) -> &'static str {
        match self {
            RefusedReason::WrongOrigin => "wrong-origin",
            RefusedReason::WrongSource => "wrong-source",
            RefusedReason::NotJson => "not-json",
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub enum FrameTarget {
    /// An iframe named in HTML by data-frame-target.
    Frame {
        name: String,
    },
    /// The page this document is framed in.
    Parent,
}

#[derive(Debug, Clone, PartialEq)]
pub enum CoordinationRequest {
    Identity,
    Open {
        channel: String,
        via: Via,
    },
    Close {
        channel: String,
    },
    /// To every other context with the channel open; never back to this one.
    Broadcast {
        channel: String,
        message: RawJson,
    },
    /// wait false answers Busy at once if another context holds it; steal takes it from the holder, which hears LockLost.
    Acquire {
        name: String,
        mode: LockMode,
        wait: bool,
        steal: bool,
    },
    Release {
        lock: LockHandle,
    },
    /// origin must be an exact origin (scheme, host, port); no wildcard, no opaque origin.
    Listen {
        target: FrameTarget,
        origin: String,
    },
    Post {
        peer: PeerId,
        message: RawJson,
    },
    Unlisten {
        peer: PeerId,
    },
}

#[derive(Debug, Clone, PartialEq)]
pub enum CoordinationResult {
    Identity {
        context: ContextId,
    },
    Opened {
        channel: String,
        context: ContextId,
    },
    AlreadyOpen,
    Closed,
    NotOpen,
    Sent,
    /// The serialized message is longer than limit characters.
    TooLarge {
        limit: i64,
    },
    Acquired {
        lock: LockHandle,
    },
    Busy,
    Released,
    UnknownLock,
    Listening {
        peer: PeerId,
    },
    InvalidOrigin {
        problem: String,
    },
    NotFound,
    /// The frame was removed, or navigated away from the declared origin.
    PeerGone,
    UnknownPeer,
    Unlistened,
    Unsupported,
    Cancelled,
}

#[derive(Debug, Clone, PartialEq)]
pub enum CoordinationFact {
    Received {
        channel: String,
        from: ContextId,
        message: RawJson,
    },
    /// Something arrived on the channel that the pack will not pass on.
    Undeliverable {
        channel: String,
        reason: UndeliverableReason,
    },
    /// Another context stole the lock; this context no longer holds it.
    LockLost {
        lock: LockHandle,
    },
    PeerMessage {
        peer: PeerId,
        message: RawJson,
    },
    /// A message that was not delivered; origin is what the browser reported.
    PeerRefused {
        peer: PeerId,
        origin: String,
        reason: RefusedReason,
    },
}

pub fn decode_context_id(value: &Value, path: &str) -> Result<ContextId, DecodeError> {
    wire::string(value, path).map(ContextId)
}

pub fn decode_lock_handle(value: &Value, path: &str) -> Result<LockHandle, DecodeError> {
    wire::string(value, path).map(LockHandle)
}

pub fn decode_peer_id(value: &Value, path: &str) -> Result<PeerId, DecodeError> {
    wire::string(value, path).map(PeerId)
}

pub fn decode_via(value: &Value, path: &str) -> Result<Via, DecodeError> {
    wire::enumeration(value, path, &[("broadcast", Via::Broadcast), ("hub", Via::Hub)])
}

pub fn decode_lock_mode(value: &Value, path: &str) -> Result<LockMode, DecodeError> {
    wire::enumeration(value, path, &[("exclusive", LockMode::Exclusive), ("shared", LockMode::Shared)])
}

pub fn decode_undeliverable_reason(value: &Value, path: &str) -> Result<UndeliverableReason, DecodeError> {
    wire::enumeration(value, path, &[("not-json", UndeliverableReason::NotJson), ("malformed", UndeliverableReason::Malformed), ("too-large", UndeliverableReason::TooLarge)])
}

pub fn decode_refused_reason(value: &Value, path: &str) -> Result<RefusedReason, DecodeError> {
    wire::enumeration(value, path, &[("wrong-origin", RefusedReason::WrongOrigin), ("wrong-source", RefusedReason::WrongSource), ("not-json", RefusedReason::NotJson)])
}

pub fn decode_frame_target(value: &Value, path: &str) -> Result<FrameTarget, DecodeError> {
    match wire::tag(value, path, "kind")?.as_str() {
        "frame" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "name"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "frame"))?;
            let f_name = wire::required(props, path, "name", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            Ok(FrameTarget::Frame { name: f_name })
        }
        "parent" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "parent"))?;
            Ok(FrameTarget::Parent)
        }
        other => Err(wire::unknown_variant(&format!("{}.kind", path), other)),
    }
}

pub fn decode_coordination_request(value: &Value, path: &str) -> Result<CoordinationRequest, DecodeError> {
    match wire::tag(value, path, "operation")?.as_str() {
        "identity" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "identity"))?;
            Ok(CoordinationRequest::Identity)
        }
        "open" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation", "channel", "via"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "open"))?;
            let f_channel = wire::required(props, path, "channel", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            let f_via = wire::required(props, path, "via", |v0: &Value, p0: &str| decode_via(v0, p0))?;
            Ok(CoordinationRequest::Open { channel: f_channel, via: f_via })
        }
        "close" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation", "channel"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "close"))?;
            let f_channel = wire::required(props, path, "channel", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            Ok(CoordinationRequest::Close { channel: f_channel })
        }
        "broadcast" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation", "channel", "message"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "broadcast"))?;
            let f_channel = wire::required(props, path, "channel", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            let f_message = wire::required(props, path, "message", |v0: &Value, p0: &str| wire::json(v0, p0))?;
            Ok(CoordinationRequest::Broadcast { channel: f_channel, message: f_message })
        }
        "acquire" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation", "name", "mode", "wait", "steal"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "acquire"))?;
            let f_name = wire::required(props, path, "name", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            let f_mode = wire::required(props, path, "mode", |v0: &Value, p0: &str| decode_lock_mode(v0, p0))?;
            let f_wait = wire::required(props, path, "wait", |v0: &Value, p0: &str| wire::boolean(v0, p0))?;
            let f_steal = wire::required(props, path, "steal", |v0: &Value, p0: &str| wire::boolean(v0, p0))?;
            Ok(CoordinationRequest::Acquire { name: f_name, mode: f_mode, wait: f_wait, steal: f_steal })
        }
        "release" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation", "lock"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "release"))?;
            let f_lock = wire::required(props, path, "lock", |v0: &Value, p0: &str| decode_lock_handle(v0, p0))?;
            Ok(CoordinationRequest::Release { lock: f_lock })
        }
        "listen" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation", "target", "origin"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "listen"))?;
            let f_target = wire::required(props, path, "target", |v0: &Value, p0: &str| decode_frame_target(v0, p0))?;
            let f_origin = wire::required(props, path, "origin", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            Ok(CoordinationRequest::Listen { target: f_target, origin: f_origin })
        }
        "post" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation", "peer", "message"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "post"))?;
            let f_peer = wire::required(props, path, "peer", |v0: &Value, p0: &str| decode_peer_id(v0, p0))?;
            let f_message = wire::required(props, path, "message", |v0: &Value, p0: &str| wire::json(v0, p0))?;
            Ok(CoordinationRequest::Post { peer: f_peer, message: f_message })
        }
        "unlisten" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["operation", "peer"])?;
            wire::required(props, path, "operation", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "unlisten"))?;
            let f_peer = wire::required(props, path, "peer", |v0: &Value, p0: &str| decode_peer_id(v0, p0))?;
            Ok(CoordinationRequest::Unlisten { peer: f_peer })
        }
        other => Err(wire::unknown_variant(&format!("{}.operation", path), other)),
    }
}

pub fn decode_coordination_result(value: &Value, path: &str) -> Result<CoordinationResult, DecodeError> {
    match wire::tag(value, path, "kind")?.as_str() {
        "Identity" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "context"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Identity"))?;
            let f_context = wire::required(props, path, "context", |v0: &Value, p0: &str| decode_context_id(v0, p0))?;
            Ok(CoordinationResult::Identity { context: f_context })
        }
        "Opened" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "channel", "context"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Opened"))?;
            let f_channel = wire::required(props, path, "channel", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            let f_context = wire::required(props, path, "context", |v0: &Value, p0: &str| decode_context_id(v0, p0))?;
            Ok(CoordinationResult::Opened { channel: f_channel, context: f_context })
        }
        "AlreadyOpen" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "AlreadyOpen"))?;
            Ok(CoordinationResult::AlreadyOpen)
        }
        "Closed" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Closed"))?;
            Ok(CoordinationResult::Closed)
        }
        "NotOpen" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "NotOpen"))?;
            Ok(CoordinationResult::NotOpen)
        }
        "Sent" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Sent"))?;
            Ok(CoordinationResult::Sent)
        }
        "TooLarge" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "limit"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "TooLarge"))?;
            let f_limit = wire::required(props, path, "limit", |v0: &Value, p0: &str| wire::int(v0, p0))?;
            Ok(CoordinationResult::TooLarge { limit: f_limit })
        }
        "Acquired" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "lock"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Acquired"))?;
            let f_lock = wire::required(props, path, "lock", |v0: &Value, p0: &str| decode_lock_handle(v0, p0))?;
            Ok(CoordinationResult::Acquired { lock: f_lock })
        }
        "Busy" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Busy"))?;
            Ok(CoordinationResult::Busy)
        }
        "Released" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Released"))?;
            Ok(CoordinationResult::Released)
        }
        "UnknownLock" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "UnknownLock"))?;
            Ok(CoordinationResult::UnknownLock)
        }
        "Listening" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "peer"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Listening"))?;
            let f_peer = wire::required(props, path, "peer", |v0: &Value, p0: &str| decode_peer_id(v0, p0))?;
            Ok(CoordinationResult::Listening { peer: f_peer })
        }
        "InvalidOrigin" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "problem"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "InvalidOrigin"))?;
            let f_problem = wire::required(props, path, "problem", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            Ok(CoordinationResult::InvalidOrigin { problem: f_problem })
        }
        "NotFound" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "NotFound"))?;
            Ok(CoordinationResult::NotFound)
        }
        "PeerGone" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "PeerGone"))?;
            Ok(CoordinationResult::PeerGone)
        }
        "UnknownPeer" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "UnknownPeer"))?;
            Ok(CoordinationResult::UnknownPeer)
        }
        "Unlistened" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Unlistened"))?;
            Ok(CoordinationResult::Unlistened)
        }
        "Unsupported" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Unsupported"))?;
            Ok(CoordinationResult::Unsupported)
        }
        "Cancelled" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Cancelled"))?;
            Ok(CoordinationResult::Cancelled)
        }
        other => Err(wire::unknown_variant(&format!("{}.kind", path), other)),
    }
}

pub fn decode_coordination_fact(value: &Value, path: &str) -> Result<CoordinationFact, DecodeError> {
    match wire::tag(value, path, "kind")?.as_str() {
        "Received" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "channel", "from", "message"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Received"))?;
            let f_channel = wire::required(props, path, "channel", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            let f_from = wire::required(props, path, "from", |v0: &Value, p0: &str| decode_context_id(v0, p0))?;
            let f_message = wire::required(props, path, "message", |v0: &Value, p0: &str| wire::json(v0, p0))?;
            Ok(CoordinationFact::Received { channel: f_channel, from: f_from, message: f_message })
        }
        "Undeliverable" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "channel", "reason"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "Undeliverable"))?;
            let f_channel = wire::required(props, path, "channel", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            let f_reason = wire::required(props, path, "reason", |v0: &Value, p0: &str| decode_undeliverable_reason(v0, p0))?;
            Ok(CoordinationFact::Undeliverable { channel: f_channel, reason: f_reason })
        }
        "LockLost" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "lock"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "LockLost"))?;
            let f_lock = wire::required(props, path, "lock", |v0: &Value, p0: &str| decode_lock_handle(v0, p0))?;
            Ok(CoordinationFact::LockLost { lock: f_lock })
        }
        "PeerMessage" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "peer", "message"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "PeerMessage"))?;
            let f_peer = wire::required(props, path, "peer", |v0: &Value, p0: &str| decode_peer_id(v0, p0))?;
            let f_message = wire::required(props, path, "message", |v0: &Value, p0: &str| wire::json(v0, p0))?;
            Ok(CoordinationFact::PeerMessage { peer: f_peer, message: f_message })
        }
        "PeerRefused" => {
            let props = wire::closed(wire::properties(value, path)?, path, &["kind", "peer", "origin", "reason"])?;
            wire::required(props, path, "kind", |v0: &Value, p0: &str| wire::literal_string(v0, p0, "PeerRefused"))?;
            let f_peer = wire::required(props, path, "peer", |v0: &Value, p0: &str| decode_peer_id(v0, p0))?;
            let f_origin = wire::required(props, path, "origin", |v0: &Value, p0: &str| wire::string(v0, p0))?;
            let f_reason = wire::required(props, path, "reason", |v0: &Value, p0: &str| decode_refused_reason(v0, p0))?;
            Ok(CoordinationFact::PeerRefused { peer: f_peer, origin: f_origin, reason: f_reason })
        }
        other => Err(wire::unknown_variant(&format!("{}.kind", path), other)),
    }
}

pub fn encode_context_id(value: &ContextId) -> Value {
    wire::of_string(&value.0)
}

pub fn encode_lock_handle(value: &LockHandle) -> Value {
    wire::of_string(&value.0)
}

pub fn encode_peer_id(value: &PeerId) -> Value {
    wire::of_string(&value.0)
}

pub fn encode_via(value: &Via) -> Value {
    match value {
        Via::Broadcast => wire::of_string("broadcast"),
        Via::Hub => wire::of_string("hub"),
    }
}

pub fn encode_lock_mode(value: &LockMode) -> Value {
    match value {
        LockMode::Exclusive => wire::of_string("exclusive"),
        LockMode::Shared => wire::of_string("shared"),
    }
}

pub fn encode_undeliverable_reason(value: &UndeliverableReason) -> Value {
    match value {
        UndeliverableReason::NotJson => wire::of_string("not-json"),
        UndeliverableReason::Malformed => wire::of_string("malformed"),
        UndeliverableReason::TooLarge => wire::of_string("too-large"),
    }
}

pub fn encode_refused_reason(value: &RefusedReason) -> Value {
    match value {
        RefusedReason::WrongOrigin => wire::of_string("wrong-origin"),
        RefusedReason::WrongSource => wire::of_string("wrong-source"),
        RefusedReason::NotJson => wire::of_string("not-json"),
    }
}

pub fn encode_frame_target(value: &FrameTarget) -> Value {
    match value {
        FrameTarget::Frame { name: f_name } => wire::of_object(vec![Some(("kind", wire::of_string("frame"))), Some(("name", wire::of_string(f_name)))]),
        FrameTarget::Parent => wire::of_object(vec![Some(("kind", wire::of_string("parent")))]),
    }
}

pub fn encode_coordination_request(value: &CoordinationRequest) -> Value {
    match value {
        CoordinationRequest::Identity => wire::of_object(vec![Some(("operation", wire::of_string("identity")))]),
        CoordinationRequest::Open { channel: f_channel, via: f_via } => wire::of_object(vec![Some(("operation", wire::of_string("open"))), Some(("channel", wire::of_string(f_channel))), Some(("via", encode_via(f_via)))]),
        CoordinationRequest::Close { channel: f_channel } => wire::of_object(vec![Some(("operation", wire::of_string("close"))), Some(("channel", wire::of_string(f_channel)))]),
        CoordinationRequest::Broadcast { channel: f_channel, message: f_message } => wire::of_object(vec![Some(("operation", wire::of_string("broadcast"))), Some(("channel", wire::of_string(f_channel))), Some(("message", wire::of_json(f_message)))]),
        CoordinationRequest::Acquire { name: f_name, mode: f_mode, wait: f_wait, steal: f_steal } => wire::of_object(vec![Some(("operation", wire::of_string("acquire"))), Some(("name", wire::of_string(f_name))), Some(("mode", encode_lock_mode(f_mode))), Some(("wait", wire::of_bool(*f_wait))), Some(("steal", wire::of_bool(*f_steal)))]),
        CoordinationRequest::Release { lock: f_lock } => wire::of_object(vec![Some(("operation", wire::of_string("release"))), Some(("lock", encode_lock_handle(f_lock)))]),
        CoordinationRequest::Listen { target: f_target, origin: f_origin } => wire::of_object(vec![Some(("operation", wire::of_string("listen"))), Some(("target", encode_frame_target(f_target))), Some(("origin", wire::of_string(f_origin)))]),
        CoordinationRequest::Post { peer: f_peer, message: f_message } => wire::of_object(vec![Some(("operation", wire::of_string("post"))), Some(("peer", encode_peer_id(f_peer))), Some(("message", wire::of_json(f_message)))]),
        CoordinationRequest::Unlisten { peer: f_peer } => wire::of_object(vec![Some(("operation", wire::of_string("unlisten"))), Some(("peer", encode_peer_id(f_peer)))]),
    }
}

pub fn encode_coordination_result(value: &CoordinationResult) -> Value {
    match value {
        CoordinationResult::Identity { context: f_context } => wire::of_object(vec![Some(("kind", wire::of_string("Identity"))), Some(("context", encode_context_id(f_context)))]),
        CoordinationResult::Opened { channel: f_channel, context: f_context } => wire::of_object(vec![Some(("kind", wire::of_string("Opened"))), Some(("channel", wire::of_string(f_channel))), Some(("context", encode_context_id(f_context)))]),
        CoordinationResult::AlreadyOpen => wire::of_object(vec![Some(("kind", wire::of_string("AlreadyOpen")))]),
        CoordinationResult::Closed => wire::of_object(vec![Some(("kind", wire::of_string("Closed")))]),
        CoordinationResult::NotOpen => wire::of_object(vec![Some(("kind", wire::of_string("NotOpen")))]),
        CoordinationResult::Sent => wire::of_object(vec![Some(("kind", wire::of_string("Sent")))]),
        CoordinationResult::TooLarge { limit: f_limit } => wire::of_object(vec![Some(("kind", wire::of_string("TooLarge"))), Some(("limit", wire::of_int(*f_limit)))]),
        CoordinationResult::Acquired { lock: f_lock } => wire::of_object(vec![Some(("kind", wire::of_string("Acquired"))), Some(("lock", encode_lock_handle(f_lock)))]),
        CoordinationResult::Busy => wire::of_object(vec![Some(("kind", wire::of_string("Busy")))]),
        CoordinationResult::Released => wire::of_object(vec![Some(("kind", wire::of_string("Released")))]),
        CoordinationResult::UnknownLock => wire::of_object(vec![Some(("kind", wire::of_string("UnknownLock")))]),
        CoordinationResult::Listening { peer: f_peer } => wire::of_object(vec![Some(("kind", wire::of_string("Listening"))), Some(("peer", encode_peer_id(f_peer)))]),
        CoordinationResult::InvalidOrigin { problem: f_problem } => wire::of_object(vec![Some(("kind", wire::of_string("InvalidOrigin"))), Some(("problem", wire::of_string(f_problem)))]),
        CoordinationResult::NotFound => wire::of_object(vec![Some(("kind", wire::of_string("NotFound")))]),
        CoordinationResult::PeerGone => wire::of_object(vec![Some(("kind", wire::of_string("PeerGone")))]),
        CoordinationResult::UnknownPeer => wire::of_object(vec![Some(("kind", wire::of_string("UnknownPeer")))]),
        CoordinationResult::Unlistened => wire::of_object(vec![Some(("kind", wire::of_string("Unlistened")))]),
        CoordinationResult::Unsupported => wire::of_object(vec![Some(("kind", wire::of_string("Unsupported")))]),
        CoordinationResult::Cancelled => wire::of_object(vec![Some(("kind", wire::of_string("Cancelled")))]),
    }
}

pub fn encode_coordination_fact(value: &CoordinationFact) -> Value {
    match value {
        CoordinationFact::Received { channel: f_channel, from: f_from, message: f_message } => wire::of_object(vec![Some(("kind", wire::of_string("Received"))), Some(("channel", wire::of_string(f_channel))), Some(("from", encode_context_id(f_from))), Some(("message", wire::of_json(f_message)))]),
        CoordinationFact::Undeliverable { channel: f_channel, reason: f_reason } => wire::of_object(vec![Some(("kind", wire::of_string("Undeliverable"))), Some(("channel", wire::of_string(f_channel))), Some(("reason", encode_undeliverable_reason(f_reason)))]),
        CoordinationFact::LockLost { lock: f_lock } => wire::of_object(vec![Some(("kind", wire::of_string("LockLost"))), Some(("lock", encode_lock_handle(f_lock)))]),
        CoordinationFact::PeerMessage { peer: f_peer, message: f_message } => wire::of_object(vec![Some(("kind", wire::of_string("PeerMessage"))), Some(("peer", encode_peer_id(f_peer))), Some(("message", wire::of_json(f_message)))]),
        CoordinationFact::PeerRefused { peer: f_peer, origin: f_origin, reason: f_reason } => wire::of_object(vec![Some(("kind", wire::of_string("PeerRefused"))), Some(("peer", encode_peer_id(f_peer))), Some(("origin", wire::of_string(f_origin))), Some(("reason", encode_refused_reason(f_reason)))]),
    }
}

/// Parses untrusted JSON text into a ContextId, or says where and why it is not one.
pub fn parse_context_id(json: &str) -> Result<ContextId, DecodeError> {
    wire::parse(json, decode_context_id)
}

/// Serializes a ContextId to wire JSON text.
pub fn serialize_context_id(value: &ContextId) -> String {
    encode_context_id(value).to_string()
}

/// Parses untrusted JSON text into a LockHandle, or says where and why it is not one.
pub fn parse_lock_handle(json: &str) -> Result<LockHandle, DecodeError> {
    wire::parse(json, decode_lock_handle)
}

/// Serializes a LockHandle to wire JSON text.
pub fn serialize_lock_handle(value: &LockHandle) -> String {
    encode_lock_handle(value).to_string()
}

/// Parses untrusted JSON text into a PeerId, or says where and why it is not one.
pub fn parse_peer_id(json: &str) -> Result<PeerId, DecodeError> {
    wire::parse(json, decode_peer_id)
}

/// Serializes a PeerId to wire JSON text.
pub fn serialize_peer_id(value: &PeerId) -> String {
    encode_peer_id(value).to_string()
}

/// Parses untrusted JSON text into a Via, or says where and why it is not one.
pub fn parse_via(json: &str) -> Result<Via, DecodeError> {
    wire::parse(json, decode_via)
}

/// Serializes a Via to wire JSON text.
pub fn serialize_via(value: &Via) -> String {
    encode_via(value).to_string()
}

/// Parses untrusted JSON text into a LockMode, or says where and why it is not one.
pub fn parse_lock_mode(json: &str) -> Result<LockMode, DecodeError> {
    wire::parse(json, decode_lock_mode)
}

/// Serializes a LockMode to wire JSON text.
pub fn serialize_lock_mode(value: &LockMode) -> String {
    encode_lock_mode(value).to_string()
}

/// Parses untrusted JSON text into a UndeliverableReason, or says where and why it is not one.
pub fn parse_undeliverable_reason(json: &str) -> Result<UndeliverableReason, DecodeError> {
    wire::parse(json, decode_undeliverable_reason)
}

/// Serializes a UndeliverableReason to wire JSON text.
pub fn serialize_undeliverable_reason(value: &UndeliverableReason) -> String {
    encode_undeliverable_reason(value).to_string()
}

/// Parses untrusted JSON text into a RefusedReason, or says where and why it is not one.
pub fn parse_refused_reason(json: &str) -> Result<RefusedReason, DecodeError> {
    wire::parse(json, decode_refused_reason)
}

/// Serializes a RefusedReason to wire JSON text.
pub fn serialize_refused_reason(value: &RefusedReason) -> String {
    encode_refused_reason(value).to_string()
}

/// Parses untrusted JSON text into a FrameTarget, or says where and why it is not one.
pub fn parse_frame_target(json: &str) -> Result<FrameTarget, DecodeError> {
    wire::parse(json, decode_frame_target)
}

/// Serializes a FrameTarget to wire JSON text.
pub fn serialize_frame_target(value: &FrameTarget) -> String {
    encode_frame_target(value).to_string()
}

/// Parses untrusted JSON text into a CoordinationRequest, or says where and why it is not one.
pub fn parse_coordination_request(json: &str) -> Result<CoordinationRequest, DecodeError> {
    wire::parse(json, decode_coordination_request)
}

/// Serializes a CoordinationRequest to wire JSON text.
pub fn serialize_coordination_request(value: &CoordinationRequest) -> String {
    encode_coordination_request(value).to_string()
}

/// Parses untrusted JSON text into a CoordinationResult, or says where and why it is not one.
pub fn parse_coordination_result(json: &str) -> Result<CoordinationResult, DecodeError> {
    wire::parse(json, decode_coordination_result)
}

/// Serializes a CoordinationResult to wire JSON text.
pub fn serialize_coordination_result(value: &CoordinationResult) -> String {
    encode_coordination_result(value).to_string()
}

/// Parses untrusted JSON text into a CoordinationFact, or says where and why it is not one.
pub fn parse_coordination_fact(json: &str) -> Result<CoordinationFact, DecodeError> {
    wire::parse(json, decode_coordination_fact)
}

/// Serializes a CoordinationFact to wire JSON text.
pub fn serialize_coordination_fact(value: &CoordinationFact) -> String {
    encode_coordination_fact(value).to_string()
}

/// Decode-then-encode by type name. Used only by the shared conformance runner.
pub fn conformance_round_trip(type_name: &str, value: &Value) -> Option<Result<Value, DecodeError>> {
    match type_name {
        "ContextId" => Some(decode_context_id(value, "$").map(|decoded| encode_context_id(&decoded))),
        "LockHandle" => Some(decode_lock_handle(value, "$").map(|decoded| encode_lock_handle(&decoded))),
        "PeerId" => Some(decode_peer_id(value, "$").map(|decoded| encode_peer_id(&decoded))),
        "Via" => Some(decode_via(value, "$").map(|decoded| encode_via(&decoded))),
        "LockMode" => Some(decode_lock_mode(value, "$").map(|decoded| encode_lock_mode(&decoded))),
        "UndeliverableReason" => Some(decode_undeliverable_reason(value, "$").map(|decoded| encode_undeliverable_reason(&decoded))),
        "RefusedReason" => Some(decode_refused_reason(value, "$").map(|decoded| encode_refused_reason(&decoded))),
        "FrameTarget" => Some(decode_frame_target(value, "$").map(|decoded| encode_frame_target(&decoded))),
        "CoordinationRequest" => Some(decode_coordination_request(value, "$").map(|decoded| encode_coordination_request(&decoded))),
        "CoordinationResult" => Some(decode_coordination_result(value, "$").map(|decoded| encode_coordination_result(&decoded))),
        "CoordinationFact" => Some(decode_coordination_fact(value, "$").map(|decoded| encode_coordination_fact(&decoded))),
        _ => None,
    }
}
